### ISSUE TITLE
where can I find v1.2.0 documentation site?

### ISSUE THREAD

**Issue by crazyxhz** [pedronauck/docz#1002]
Is this project still maintained?
The v2 is very buggy so I switched to v1.2.0(also a lot of bug but at least it can run)
But the doc site https://www.docz.site/ is for v2 only, where can I find the old doc site?

**Comment by crazyxhz** [comment]
find doc site repo https://github.com/pedronauck/docz-website. Master branch, fresh install, still can not run...
![image](https://user-images.githubusercontent.com/6551888/62909721-618c7700-bdb0-11e9-9d70-3e75c49eacd5.png)

**Comment by tylergraf** [comment]
I can't run v2 either.
![image](https://user-images.githubusercontent.com/751054/62916481-87ccfb00-bd4d-11e9-9c7c-1cf812b291a7.png)

**Comment by shengbeiniao** [comment]
some problem and V2 is too large for me~

**Comment by thunderBiscuit** [comment]
Really looking for the docs for 1.2 as well! V2 is still very new and all examples of projects using docz live right now are on 1.2 or less. We are definitely interested in eventually migrating to v2, but are finding that it is much easier to get off the ground using 1.2 and looking at examples that are live. Any chance we can see the docs for 1.2 or less somewhere?

**Comment by rakannimer** [comment]
I deployed the v1.2 docs to : https://docz-v1.surge.sh/

Hope that helps !

**Comment by rakannimer** [comment]
Added a link to the v1 docs on the [README](https://github.com/pedronauck/docz#-v1-docs)
