### ISSUE TITLE
Trying to setup with create-react-app

### ISSUE THREAD

**Issue by gustavo-depaula** [pedronauck/docz#104]
## Question

# **Description**
Steps:
* created app with create-react-app
* installed packages
* created a sample .mdx file inside src/
* run yarn docz dev
* error :(

# *Give more information about your doubt*
![image](https://user-images.githubusercontent.com/732422/42119489-f3f5c49a-7be2-11e8-91d8-58d7460dbf5c.png)

**Comment by pedronauck** [comment]
I'll check it out @gustavo-depaula 🙏

**Comment by vivek12345** [comment]
@gustavo-depaula what version of node are you on?

**Comment by gustavo-depaula** [comment]
@vivek12345 node 10

**Comment by gustavo-depaula** [comment]
Eita. I was able to run it. I restarted my pc, switched from node 10 to 6, and back to 10 again and it worked. I don't know exactly what happened, but thank you guys!

**Comment by marceloavf** [comment]
No problem @gustavo-depaula, If it still happens feel free to comment or open a new issue!

Thank you!
