### ISSUE TITLE
Elements broken in Playground

### ISSUE THREAD

**Issue by nicholasess** [pedronauck/docz#108]
## Bug Report

**Describe the bug**
When I add a set of elements that are larger as the width of the playground, it breaks the element

**To Reproduce**
![captura de tela 2018-07-01 as 15 39 10](https://user-images.githubusercontent.com/3238901/42137592-5539c932-7d45-11e8-98f0-945bd0dbdf5d.png)

**Enviroment**

* OS: macOS High Sierra 10.13.4
* Node/yarn version: 8.5.0/1.6.0

**Comment by marceloavf** [comment]
Hey @nicholasess, thank you for the feedback.

I was debugging it here and seems to be everything fine with the example.

Could you please provide an example code or repository for this bug, please?

**Comment by nicholasess** [comment]
@marceloavf Yes, this is the repository that i created.
https://github.com/nicholasess/docz-example/blob/master/src/components/Button.mdx#L21
