### ISSUE TITLE
Compiling hangs when building modules

### ISSUE THREAD

**Issue by tsnolan23** [pedronauck/docz#112]
## Bug Report

I've installed and configured Docz within my project, and when I have no `.mdx` files in the directory, and run `docz dev`, the server starts up completely fine. I navigate to `http://localhost:3000` and see the Docz app with a 404 error (which is expected since I have no files created). This tells me that docz is configured fine (I'm using webpack 4 and babel 6 in combination with the babel6 plugin).

Now, when I actually add a simple `intro.mdx` file and run `docz dev`, it hangs on building modules.

This is the contents of the file:

```
---
name: Intro
---

# Hello World
```

```shell
> kwuikit@1.0.0 docs C:\xampp\htdocs\kwuikit
> docz dev

i  info      Removing old app files
i  info      Creating new docz files
i  info      Setup entries socket on port 8089

Compiling

* Client [Loading bar ] building modules (55%) 377/378 modules 1 active
  docs\intro.mdx <!--- HANGS RIGHT HERE
```

**Expected behavior**

I would expect with such a simple file that it properly loads the page, and I would see an Intro page when I navigate to `http://localhost:3000`

**Enviroment**

* OS: Windows 10
* Node/npm version: [Node v8.9.3/NPM v5.5.1]
* Docz version: v0.4.0

**Comment by nicholasess** [comment]
@tsnolan23 add after name: Intro, route: /

```
name: Intro
route: /
```
Now refresh the browser, i guess that will work!

**Comment by tsnolan23** [comment]
I tried that as well with the route specified, that doesn't actually solve the compiling issue.  It still hangs when compiling even with this:

```
---
name: Intro
route: /
---

# Hello World
```

**Comment by nicholasess** [comment]
@tsnolan23 Can you give me a repository with example? I need to try reproduce your problem.

**Comment by tsnolan23** [comment]
It's in a private repo, I'll try to reproduce in another repo and post here.

**Comment by tsnolan23** [comment]
@nicholasess Thanks for looking at this. I updated all my babel dependencies to the latest version of 6 and removed some unused dependencies, and it seems to not hang anymore. Closing this for now. Will update you if I find the root cause at some point.
