### ISSUE TITLE
Suggestion: Use create-react-context for 16.0+ compatibility

### ISSUE THREAD

**Issue by mAAdhaTTah** [pedronauck/docz#118]
Currently, docz requires React 16.4+. I believe this is mostly due to the user of the new `createContext`, a feature landed in React 16.3 and used for docz's theming. For my project, I need to use React 16.2 because Enzyme, the testing library I'm using, doesn't yet support the new features added in 16.3, so I need to use React 16.2 in my project to run my tests.

If docz swapped out its usage of createContext for the [`create-react-context`](https://github.com/jamiebuilds/create-react-context) library, I'd be able to continue to use 16.2 in my tests.

I'd also be willing to do this work, if this is something you'd accept.

**Comment by pedronauck** [comment]
Good @mAAdhaTTah I think that's possible, I'll see to make that soon as possible!

**Comment by pedronauck** [comment]
Fixed on #119

**Comment by mAAdhaTTah** [comment]
Thanks! mdx-js is using createContext, so I opened an issue there as well: https://github.com/mdx-js/mdx/issues/178

**Comment by mAAdhaTTah** [comment]
@pedronauck I'm not sure how you're bundling, but it appears you bundle the dependencies into the distribution files. I fixed the above issue in mdx-js, but I can't use the version with the fix because your bundle comes with it built in already. Additionally, shipping minified bundles makes it difficult to debug generally (altho in this case, was not a big deal).

Is this something you could change? I'll open an issue to track it.
