### ISSUE TITLE
Wrong path for components in Windows

### ISSUE THREAD

**Issue by marceloavf** [pedronauck/docz#12]
## Bug Report

**Describe the bug**

When try to run dev project it return an error about wrong imports from components without the slash bar, probably something with windows path.

**To Reproduce**

1. Run `npm install`
2. Run `npm dev`

```shell
 ERROR  Failed to compile with 3 errors                                                                                                                                  09:20:48

These dependencies were not found:

* srccomponentsAlert.mdx in ./.docz/app/imports.js
* srccomponentsButton.mdx in ./.docz/app/imports.js
* srcindex.mdx in ./.docz/app/imports.js

To install them, you can run: npm install --save srccomponentsAlert.mdx srccomponentsButton.mdx srcindex.mdx
```

**Enviroment**

* OS: Windows 10
* Node/npm version: v10.4.0 / 6.0.0

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/5435657/41290242-a4e79086-6e22-11e8-851e-fddddad8bd60.png)

**Comment by LiuDianshi** [comment]
I got the same error.

**Comment by itaditya** [comment]
@pedronauck I see you have labelled as `help wanted`. I'd love to help. Can you suggest some places I should check out to track the cause of the bug. This will give me a good headstart

**Comment by marceloavf** [comment]
I tried to check some places but don't find an approachable way to debug `docz-core`

**Comment by marceloavf** [comment]
@itaditya if you could please test the pull request branch in your machine

**Comment by pantharshit00** [comment]
Ya, will be using bash for windows for now meanwhile that pull request merges into master

**Comment by marceloavf** [comment]
We need a review to merge it in #31
