### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mhf-ir** [pedronauck/docz#120]
RTL support and fully i18n.

Documentations is for users so many users with many locales whole world.

**Comment by pedronauck** [comment]
I @mhf-ir, sorry the too late response, I think that this makes a lot of sense. I'll move this issue to our roadmap, please give us your vote there 🙏 

### [⬅️ RTL (Right to left) support on default theme](http://feedback.docz.site/roadmap/p/rtl-right-to-left-support-on-default-theme)
