### ISSUE TITLE
if `base` configuration parameter is set, then document menu doesn't work

### ISSUE THREAD

**Issue by istarkov** [pedronauck/docz#121]
## Bug Report

**Describe the bug**

If `base` option in `doczrc.js` is set, then document  menu isn't working
[Example config](https://github.com/istarkov/rifm/blob/adbaaf189b365ab22b1390980ced7f501905a4fb/doczrc.js#L4)

[Result](https://istarkov.github.io/rifm/docs-readme)

How result should look

![image](https://user-images.githubusercontent.com/5077042/42350029-739a9efe-80b7-11e8-821c-6ca53df41b56.png)

**Comment by pedronauck** [comment]
thanks @istarkov, I'll check that 🙏

**Comment by istarkov** [comment]
@pedronauck Thank you! 
non minified code in npm would help to check it to everyone ;-),
Trying to find by myself the exact place there the problem is, but all that a,o,e in
```
            const r = Object.values(t),
              o = getMenusFromEntries(r).sort((e, t) => sortBy(e, t)),
              a = r
                .sort((e, t) => sortBy(e.name, t.name))
                .sort(
                  (e, t) =>
                    'descending' === n.ordering
                      ? t.order - e.order
                      : e.order - t.order
```
make me crazy ;-)

**Comment by pedronauck** [comment]
Fixed on release [v0.5.3](https://github.com/pedronauck/docz/releases/tag/v0.5.3)

**Comment by istarkov** [comment]
Wow, it was fast!!! Thank you. Incredible app, creating documentstion with is like a magic!

**Comment by pedronauck** [comment]
I glad you liked it @istarkov, I fork your repo, made somes tests and everything is fine now... I made a pr for you updating the docz versions ✌️
