### ISSUE TITLE
`docz build` failing on 0.5.3

### ISSUE THREAD

**Issue by kylealwyn** [pedronauck/docz#124]
## Bug Report

`docz build` fails on 0.5.3. `docz dev` works fine. Adding `--debug` provides nothing of value.

**Reproduction Steps**
```
git clone git@github.com:sappira-inc/refractal.git
yarn
yarn docs:build
```

**Enviroment**

* OS: OSX 10.13.3
* Node/npm version: Node 8 / yarn 1.7

**Additional context/Screenshots**
![screen shot 2018-07-06 at 12 53 35 pm](https://user-images.githubusercontent.com/14184138/42397713-c5e6d272-811b-11e8-8461-59c1e582ad89.png)

**Comment by pedronauck** [comment]
Please, try to update to new version of docz, if this still happening we can reopen this issue!

**Comment by kylealwyn** [comment]
Getting same error on 0.7.0. `docz dev` still working fine :/ I've verified every page in dev mode works.

![screen shot 2018-07-23 at 3 56 28 pm](https://user-images.githubusercontent.com/14184138/43107272-1558bf46-8e91-11e8-9311-8b5ad2783a6c.png)

**Comment by pedronauck** [comment]
Hey @kylealwyn, can you create a repo with a basic example of your code?

**Comment by kylealwyn** [comment]
https://github.com/sappira-inc/refractal

**Comment by pedronauck** [comment]
@kylealwyn your bug keeps happening even in the new versions of docz. I was reading about it and is something related to some package that can't be minified 😕 So, I'll close your issue in favor of that, if you could resolve, please give a shot :v:

**Comment by Pabloicaza** [comment]
@kylealwyn did you get it to work?? Having the same issue here 😅. 

```
"dependencies": {
    "apollo-client": "^2.3.1",
    "autoprefixer": "^8.5.0",
    "classnames": "^2.2.5",
    "file-loader": "^2.0.0",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.9.2",
    "lost": "^8.2.1",
    "node-sass-chokidar": "^1.3.0",
    "postcss-flexbugs-fixes": "^3.3.1",
    "postcss-inline-svg": "^3.1.1",
    "react-apollo": "^2.1.4",
    "react-inlinesvg": "^0.8.1",
    "rupture-sass": "^0.3.0",
    "styled-components": "^3.4.5"
  },
```
```
"devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.0",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^1.0.0",
    "docz": "^0.10.3",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "postcss-loader": "^3.0.0",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-router-dom": "^4.3.1",
    "sass-loader": "^7.1.0",
    "standard": "^11.0.1",
    "style-loader": "^0.23.0",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "url-loader": "^1.1.1",
    "webpack": "^4.17.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.7",
    "webpack-hot-client": "^4.1.1"
  }
```

**Comment by kylealwyn** [comment]
@Pabloicaza negative - still no luck. did you end up finding the issue?

**Comment by Pabloicaza** [comment]
I ended overwriting the config optimization and making `minimize: false` on doczrc.js file.
No idea if that is a good practice but works fine for me.
@kylealwyn 
```
export default {
 modifyBundlerConfig: config => {
    config.optimization = {
        runtimeChunk: true,
        nodeEnv: 'production',
        namedModules: true,
        noEmitOnErrors: true,
        splitChunks: {
          chunks: 'all',
          name: 'vendors'
        },
        minimize: false,
    }
    return config;
  }
}
```
