### ISSUE TITLE
docz-plugin-css with @zeit/next-sass

### ISSUE THREAD

**Issue by borsden** [pedronauck/docz#126]
Hi guys, firstly, thanks for your library, it was love at first sight, when i found it. But i have some problem when tried to use it with next.js, especially with @zeit/next-sass. It use `extract-text-webpack-plugin`, and when  install `docz-plugin-css`, which use webpack 4, all fails. I found some issues with similiar problems, for example: https://github.com/zeit/next-plugins/issues/101 .
So, i decided move docz dev server into docker, and container builds, server started, port throwed, but page with docs (localhost:3000) is unavailable. 
Then, i tried move it in separate inner directory `docs` and specify the directory with components, but when i create `mdx` file there, it does not shown. My `doczrc.js` looks like this:
```
import { css } from 'docz-plugin-css'

const srcPath = '../src';

export default {
  plugins: [
    css({
      preprocessor: 'sass',
      cssmodules: true,
      loaderOpts: {
        includePaths: [srcPath]
      },
    }),
  ],
  src: srcPath
}
```
Is there any chances to get it work? Maybe other solutions?

**Comment by borsden** [comment]
I found workaround. We can specify in package.json required version of webpack.
```
"resolutions": {
    "@zeit/next-sass/webpack": "3.10.0"
  }
```

**Comment by pedronauck** [comment]
For sure, we're find a solution to build all dependencies inside docz to avoid this kinda compatibility!
