### ISSUE TITLE
Zero-configuration usage with Create React App

### ISSUE THREAD

**Issue by stereobooster** [pedronauck/docz#130]
I want to ask what your opinion about Create React App zero-config experience. Do you plan to have it or is it out of scope? 

**Description**

Right now if I add `docz` to the c-r-a based project, first I get issue with `webpack-hot-client` (like here https://github.com/pedronauck/docz/issues/47). Fixed by `yarn add webpack-hot-client`.

Second issue is with `css-modules`, which doesn't work out of box. Fixed by `yarn add docz-plugin-css` and editing `doczrc.js`

Third issue: it appears I misconfigured css-loader and it doesn't work (I will figure out what is wrong with it).

I would say this is not zero-config experience, where is it is possible to figure out and fix all those small things it takes time and this time multiplies by the number of people who use it.

**PS**

In case it is not clear from the tone, I have no negative feelings and do not place any pressure, this is general question. Thank you for this project it looks promising. It seems like it can eventually shadow styleguidist and https://idyll-lang.org/ and maybe static website generators like phenolic, gatsby (I have a lot of ideas around it).

**PS2**

The more I face this kind of issues, the more I think that the issue is in Webpack. With something zero-config, like Parcel, a lot of those things would work out of the box 🤔

**Comment by pedronauck** [comment]
Thanks a lot @stereobooster and really sorry about the too late response 🙏 
What you said makes a lot of sense, today our biggest challenge is to get better our core and give the best developer experience to our users, this always has been our main goal and always will.

So, of course, you have our eyes over this and we're trying a lot to fix this! I'm really happy that you liked and has a lot of ideas for docz, please feel free to give us your ideas 🙏 

I'll close this issue by now ok? 🤘
