### ISSUE TITLE
404 error then refresh page at GitHub pages

### ISSUE THREAD

**Issue by koddr** [pedronauck/docz#131]
## Bug Report

**Describe the bug**

I see 404 error then refresh page at GitHub pages.

**To Reproduce**

1. Go to https://koddr.github.io/react-goodshare-components/
2. Click on Provider --> Facebook
3. Refresh page (F5 or cmd+R)
4. See 404 error

```shell
No error trace, just standard GitHub 404 error page.
```

**Enviroment**

* OS: macOS 10.13.5, Google Chrome (latest)
* Node/npm version: 10.x/6.x

**Additional context/Screenshots**

[![Image from Gyazo](https://i.gyazo.com/5e0d0d76e127c1e991a3eac689c55960.gif)](https://gyazo.com/5e0d0d76e127c1e991a3eac689c55960)

**Comment by mAAdhaTTah** [comment]
GitHub doesn't support SPA's like docz. See #25.

**Comment by basarat** [comment]
Need to use hashRouter : https://github.com/pedronauck/docz/issues/25#issuecomment-397741159

**Comment by basarat** [comment]
Can't be done. Hash router is not supported anymore as of today. It was supported for a while but removed in `v1` : https://github.com/pedronauck/docz/issues/908#issuecomment-500277357
