### ISSUE TITLE
Playground summary field

### ISSUE THREAD

**Issue by HakanKaraoglu** [pedronauck/docz#134]
I have a request, How can I write a description to the result area of a playground component?
![docz](https://user-images.githubusercontent.com/12962730/42534002-2f55dbd8-8494-11e8-93ff-646e8a29e079.JPG)

For example, I just want to comment on this yellow marked section.

**Comment by pedronauck** [comment]
Hi @HakanKaraoglu, we have a feature request on our roadmap about that, please vote there's :v:
http://feedback.docz.site/roadmap/p/integration-with-jsdocs

**Comment by HakanKaraoglu** [comment]
Hi @pedronauck ,

I'm voted. I will be waiting for developments

Thank you 👍
