### ISSUE TITLE
PropsTable does not render

### ISSUE THREAD

**Issue by ilyanoskov** [pedronauck/docz#138]
## Bug Report

**Describe the bug**

I have a simple Button component with some props. I tried to use PropsTable but it does not even get mounted. What could be the source of this issue? I have also tried to check whether react-docgen parses the PropTypes information and it does. 

**Environment**

* OS: 10.13.5
* Node/npm version: 10.1

**Additional context/Screenshots**

![code](https://preview.ibb.co/jZdrcT/Screen_Shot_2018_07_13_at_12_05_04.png "code") 
![code](https://image.ibb.co/kAumBo/Screen_Shot_2018_07_13_at_12_04_54.png "code") 
![code](https://preview.ibb.co/mrZmBo/Screen_Shot_2018_07_13_at_12_04_44.png "code") 
![code](https://preview.ibb.co/gdboP8/Screen_Shot_2018_07_13_at_12_04_31.png "code")

**Comment by ilyanoskov** [comment]
I pretty much ended up writing my own propTable component, I can share it here when I finalise it

**Comment by zaguiini** [comment]
Funny how only the components named `Button` have that issue

**Comment by pedronauck** [comment]
This is very weird @ilyanoskov since we already have `babel-plugin-react-docgen` inside. Can you share more details about this or maybe your solution?

**Comment by ilyanoskov** [comment]
With 0.9.2 I no longer have this issue. @felipeduardo do you have this issue?
