### ISSUE TITLE
Long text does not get wrapped in code block

### ISSUE THREAD

**Issue by ilyanoskov** [pedronauck/docz#141]
## Bug Report

**Describe the bug**

I have renamed a .md file into .mdx and the text does not get wrapped. I have attached screenshots to showcase the bug. 

The browser is Safari 11.1.1 

![code](https://preview.ibb.co/k0mmGy/Screen_Shot_2018_07_16_at_10_19_03.png "code") 
![code](https://preview.ibb.co/fjBa9J/Screen_Shot_2018_07_16_at_10_18_36.png "code")

**Comment by pedronauck** [comment]
Fixed on [v0.5.9](https://github.com/pedronauck/docz/releases/tag/v0.5.9) 👍
