### ISSUE TITLE
Missing dependencies in docz-core

### ISSUE THREAD

**Issue by cspotcode** [pedronauck/docz#1451]
## Bug Report

**Describe the bug**

docz-core imports tslib, cross-spawn, and opn, but it does not declare these in its dependencies array.  yarn 2 logs errors in these situations.  Though these dependencies are conveniently hoisted by npm as transitive dependencies, there's not necessarily any guarantee of that going forward.

**To Reproduce**

```
npm install -g yarn
mkdir repro && cd repro
yarn set version 2
yarn init
yarn add docz react react-dom
yarn docz dev
```

**Expected behavior**

No yarn errors.  docz-core's `package.json` declares dependencies on `tslib`, `cross-spawn`, and `opn`.

**Environment**

- docz version: 2.3.1
- OS: Ubuntu 18.04.4 LTS
- Node/npm version: node v13.3.0, yarn v2.0.0-rc.31, npm v6.13.1

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/376504/78723819-24a26100-78fa-11ea-96b1-863bd332ac30.png)

**Comment by jedmao** [comment]
I had to `npm install --save-dev docz-core opn` to get the theme to run within Gatsby. These dependencies should probably be marked as `peerDependencies`.

**Comment by jedmao** [comment]
Also, `opn` is deprecated.

**Comment by cspotcode** [comment]
Should this be closed, or are issues only closed once the fix has been released?

**Comment by cspotcode** [comment]
Should this be closed, or are issues only closed once the fix has been released?

**Comment by pedronauck** [comment]
Closing this, if the bug persist please re-open the issue

**Comment by cspotcode** [comment]
The bug persists, but I don't have permission to re-open this issue.

To reproduce the bug, I ran the exact reproduction steps in this issue and confirmed that the error message is the same.

The fix is simple: when code uses a dependency, it should be declared as a dependency in that code's package.json.

For example, docz-core uses cross-spawn but does not declare cross-spawn as a dependency.  The solution is for docz-core to declare a dependency on cross-spawn.  This can be a peer dependency if that makes the most sense, or it can be a regular dependency.
