### ISSUE TITLE
`base` in config doesn't work

### ISSUE THREAD

**Issue by meafmira** [pedronauck/docz#147]
## Bug Report

**Describe the bug**

`base` field in doczrc.js config does not affect any file and don't change paths in index.html.

**Enviroment**

* OS: macOS 10.13.6 (17G65)
* Node/yarn: v8.11.2/1.7.0

**Comment by pedronauck** [comment]
Fixed on [v0.6.0](https://github.com/pedronauck/docz/releases/tag/v0.6.0) 🚀

**Comment by godmar** [comment]
`base` does not seem to work in 2.0.0-rc.5 either.  When I run `yarn run docz build` some files are placed into the folder I specify, but the html files still access files from the root and links in the menu are not prefixed.  This kind of makes it unusable (?).
