### ISSUE TITLE
Resolve .md files by default

### ISSUE THREAD

**Issue by ssylvia** [pedronauck/docz#149]
It would be great if the docs resolved normal markdown (`.md`) files by default. This would make it easier to reuse standard github readme's as well as transition from or to other documentation systems.

Then any documentation files that only use standard markdown can use `.md` and MDX files can use `.mdx` extension. Similar to `.js` and `.jsx`or `.ts` and `.tsx`.

**Comment by carrickjason** [comment]
Yeah this would be great for composable documentation and should be [supported by default with mdx-js/loader](https://github.com/mdx-js/mdx#imports).  It looks like you have a rule for `.md`(`/\.md?x$/`). I'm not familiar with happypack but could it be interfering?

**Comment by pedronauck** [comment]
Really great idea @ssylvia, I'll try to make this more quickly as possible 🙏 
So, just to follow the rules I'll move this issue to our roadmap, please guys, give us your vote there!

- [🔖 Resolve markdown files by default](http://feedback.docz.site/roadmap/p/resolve-markdown-files-by-default)

**Comment by pedronauck** [comment]
Released in the new [v0.10.0](https://github.com/pedronauck/docz/releases/tag/v0.10.0) 🚀
