### ISSUE TITLE
How does onServerListening in a plugin work?

### ISSUE THREAD

**Issue by jgroth** [pedronauck/docz#150]
How am I supposed to use `onServerListening` in a plugin? I seem to get a reference to the server object created by Webpack, but the only method that seems to be available is the `start` method, but the dev server is already started. Am I missing something here? It would be more useful to be able to use the object returned by the `start`method instead. 

I did some digging and found that `onServerListening` is invoked in [packages/docz-core/src/commands/dev.ts](../blob/master/packages/docz-core/src/commands/dev.ts) 
It would be more useful to pass the reference to `app` there, or maybe `dataServer`?

What I am trying to do is to get the dev server to serve static files from my project root. I am having another build running in parallel with Docz and I want to be able to serve the files generated by that build. Is there a better way to do this than with a plugin? I did not find anything in the documentation about serving static files from the filesystem.

**Comment by pedronauck** [comment]
Hey @jgroth I just release [v0.6.0](https://github.com/pedronauck/docz/releases/tag/v0.6.0) with this new hook called `onCreateApp`, now you can use it to do what you wanted.

So, if you just want to serve static files for docz, you can put these files on `.docz/public` folder and reference in a new `index.html` file, like that:

1. Add your static files on `.docz/public`
2. Add a new `index.html` everywhere on your project and reference it on your `doczrc.js`
```js
export default {
  indexHtml: './index.html'
}
```

3. Use `{{ publicUrl }}` on your `index.html` to serve files:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- THIS IS YOUR STATIC FILE -->
    <link rel="stylesheet" href="{{ publicUrl }}/your-static-file.css">

    <title>{{ title }}</title>
  </head>
  <body>
    <div id="root" />
  </body>
</html>
```

**Comment by jgroth** [comment]
Nice! Thanks, I will try it out :)
