### ISSUE TITLE
Tried anyone to install katex plugin?

### ISSUE THREAD

**Issue by Istom1n** [pedronauck/docz#151]
## Tried anyone to install katex plugin?

**Because the mdPlugins and hastPlugins parameters work separately from each other, I can't understand in what order I need to install and connect such plugins as: remark, remark-math, remark-rehype, rehype-stringify, rehype-katex.**
*More information about those plugins you can find [here](https://www.npmjs.com/package/rehype-katex).*

**Comment by pedronauck** [comment]
You need to pass all your options in the same object like that:
https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/config/mdx.ts#L7-L26

I don't like this pattern too, but is the way adopted by mdx 😕

**Comment by kinxiel** [comment]
Discussion already closed but don't know if it would help someone but I also had some problems using 'remark-math' and 'katex'. In my case, I get the katex rendering working but I am getting it rendered twice with the properly rendered and non-rendered text (e.g. $ a^2 $, I get both a<sup>2</sup> and a^2 as the result.

Don't know why it works but including the 'katex' cdn in the index.html made it render properly. Still trying to figure out what's happening.

**doczrc.js**

```
import math from 'remark-math';
import katex from 'remark-html-katex';
import html from 'remark-html';
export default {
  indexHtml: './index.html',
  mdPlugins: [math, html, katex]
};
```

**index.html**

```
<!DOCTYPE html>
<html lang="{{ lang }}">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.css" integrity="sha384-D+9gmBxUQogRLqvARvNLmA9hS2x//eK1FhVb9PiU86gmcrBrJAQT8okdJ4LMp2uv"
        crossorigin="anonymous">

    <!-- The loading of KaTeX is deferred to speed up page rendering -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/katex.min.js" integrity="sha384-483A6DwYfKeDa0Q52fJmxFXkcPCFfnXMoXblOkJ4JcA8zATN6Tm78UNL72AKk+0O"
        crossorigin="anonymous"></script>

    <!-- To automatically render math in text elements, include the auto-render extension: -->
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.10.0-rc.1/dist/contrib/auto-render.min.js" integrity="sha384-yACMu8JWxKzSp/C1YV86pzGiQ/l1YUfE8oPuahJQxzehAjEt2GiQuy/BIvl9KyeF"
        crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>
    <title>{{ title }}</title>
    {{ head }}
</head>

<body>
    <div id="root" />
    {{ footer }}
</body>

</html>
```
