### ISSUE TITLE
how to set local css file path in indexHtml template?

### ISSUE THREAD

**Issue by lwxyfer** [pedronauck/docz#152]
how to set local css file path in indexHtml template?

I try some ways, but not work.

**Comment by pedronauck** [comment]
Update your docz to the new [v0.6.0](https://github.com/pedronauck/docz/releases/tag/v0.6.0), then:

1. Add your static files on `.docz/public`
2. Add a new `index.html` everywhere on your project and reference it on your `doczrc.js`
```js
export default {
  indexHtml: './index.html'
}
```

3. Use `{{ publicUrl }}` on your `index.html` to serve files:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- THIS IS YOUR STATIC FILE -->
    <link rel="stylesheet" href="{{ publicUrl }}/your-static-file.css">

    <title>{{ title }}</title>
  </head>
  <body>
    <div id="root" />
  </body>
</html>
```
