### ISSUE TITLE
Include an external asset for component documentation

### ISSUE THREAD

**Issue by tsnolan23** [pedronauck/docz#154]
## Question

Is it possible to include an external resource somehow? We've got several components that require an external resource that is normally included in the `<head>` of the HTML. In the `<Playground>` those are obviously not available, so they don't render properly.

For example, a Google Maps API key or an external stylesheet?

**Comment by pedronauck** [comment]
Please @tsnolan23, see #152 to get your answer ✌️

**Comment by tsnolan23** [comment]
@pedronauck I'm sorry, I tried to see if this was already asked, couldn't find it. Thank you!

**Comment by pedronauck** [comment]
Your welcome, feel free to ask what you want @tsnolan23 🙏
