### ISSUE TITLE
NODE_ENV is always set to production

### ISSUE THREAD

**Issue by cvle** [pedronauck/docz#155]
## Bug Report

**Describe the bug**
I think since this https://github.com/pedronauck/docz/commit/f6b6260c1bf63d7758f32cb4e6518ca7ea51d39b. NODE_ENV is always production no matter what I set. I believe because no matter what command is run, this files gets included and overwrite any previously set NODE_ENV.

**To Reproduce**

1. docz dev
2. See that NODE_ENV is set to production, but should be development

**Comment by pedronauck** [comment]
Fixed on [v0.6.2](https://github.com/pedronauck/docz/releases/tag/v0.6.2) 👍
