### ISSUE TITLE
How to add a local image to a page

### ISSUE THREAD

**Issue by moedong** [pedronauck/docz#157]
How to add a local image to a page

like add `![xxx](./images/xxx.png)`  into mdx file, it consoles that the picture is not found

**Comment by pedronauck** [comment]
Unfortunately, you can scape string to use something like `require` to require local images. If you want to load images locally you need to use `<img>` tag instead:

```md
# Hello world

This is my document

<img src={require('./my-local-img.jpg')} />
```

**Comment by pedronauck** [comment]
I'll try to create some remark plugin to lead with that ✌️

**Comment by nicholasess** [comment]
There is limitation of mdx, but you can use the example from Pedro.

I will close the issue for the inactivity

**Comment by magicspon** [comment]
I was able to use an image like this:

```mdx
import img from '../../../static/nutkins.jpg'

<Playground>
	<ThemeProvider theme={theme}>
		<Avatar image={img} />
	</ThemeProvider>
</Playground>
```

**Comment by Stevemoretz** [comment]
This works without resizing:

```mdx
![Shimmer Effect Placeholder](../../public/assets/screenshots/shimmer-effect-placeholder.gif)
```

This works with also resizing:

```tsx
import img from '../../public/assets/screenshots/shimmer-effect-placeholder.gif'
<img src={img} alt={"Shimmer Effect Placeholder"} style={{maxWidth : 350}}/>
```
