### ISSUE TITLE
The menu order is not always alphabetical

### ISSUE THREAD

**Issue by tsnolan23** [pedronauck/docz#158]
## Bug Report

**Describe the bug**

When there are a lot of items  in a menu, it seems that the menu order is being messed up.  For example, I created this repo:

https://github.com/tsnolan23/docz-menu-order-issue

There are 26 menu items under the "Components" menu.  I didn't modify the order in any of the files, yes, the 2 of the files are out of position.

**To Reproduce**

1. Clone that repo
2. Install dependencies
3. `npm run docs`
4. Look at the menu order

**Expected behavior**

If no order has been modified, everything should be sorted alphabetically. 

**Enviroment**

* OS: Windows 10
* Node/npm version: v8.9.3 / v5.5.1

**Additional context/Screenshots**

![menu_order](https://user-images.githubusercontent.com/12575994/43015006-ce0b412e-8c13-11e8-8c19-8d4fc204b4f3.JPG)

**Comment by moedong** [comment]
If you do not mind, we can manually set the menu order, such as

```
---
name: Button
menu: Components
order: 100
---
```
the bigger the order  number, the more the front

**Comment by tsnolan23** [comment]
@moedong Not really sure that's a solution to the problem...I don't want to have to maintain the order of any components directly, I just want them alphabetical. 

I understand that order is an option, but it doesn't solve the underlying problem in this case, it just masks it.

**Comment by pedronauck** [comment]
✅ Fixed on [v0.7.1](https://github.com/pedronauck/docz/releases/tag/v0.7.1)
