### ISSUE TITLE
Error when trying to load minified css

### ISSUE THREAD

**Issue by EmaSuriano** [pedronauck/docz#160]
## Bug Report

**Describe the bug**
I'm using a library (react-tippy) which requires to load a css file in order to look as expected. When I load the component which imports that css file, I get an error of Unexpected token .*

*A clear and concise description of what the bug is.*
I get the following error on the console which stops the server from starting ..

``` shell
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .tippy-touch{cursor:pointer!important}.tippy-notransition{transition:none!important}.tippy-popper{max-width:400px;-webkit-perspective:800px;perspective:800px;z-index:9999;outline:0;transition-timing-function:cubic-bezier( ...
```

**To Reproduce**

In order to 
1. git clone https://github.com/EmaSuriano/docz-css-bug-example.git
2. yarn install
3. yarn dev

**Expected behavior**

Start the server as expected.
<img width="939" alt="screen shot 2018-07-20 at 19 11 11" src="https://user-images.githubusercontent.com/3399429/43027468-ca656f4e-8c50-11e8-9ade-bc06350db1c4.png">

**Enviroment**

* OS: OSX
* Node/npm version: 10.6.0

**Additional context/Screenshots**

The workaround I found was to format the file with prettier and it seems the server to be working. The problem with is that I have to store the file in my codebase, which I really don't want to do because if the owner of the library made a change on the styles I have to manually change it ..

This is the branch with the work around --> https://github.com/EmaSuriano/docz-css-bug-example/tree/formatting-css-file

**Comment by tsnolan23** [comment]
@EmaSuriano  The docz CSS plugin should resolve your problem:

https://github.com/pedronauck/docz/tree/master/packages/docz-plugin-css

**Comment by tsnolan23** [comment]
@EmaSuriano I was able to get your project running by modifying the bundler config without the CSS plugin:

```
// doczrc.js
export default {
  modifyBundlerConfig: config => {
    config.module.rules.push({
      test: /\.css$/,
      use: ["style-loader", "css-loader"]
    });
    return config;
  }
};
```
It did require additional dependencies, then, though - `style-loader` and `css-loader`.

Not sure if that's the proper way to achieve the result, but it does work!

**Comment by EmaSuriano** [comment]
It works! 🎉 
But I'm thinking if this bug should be fixed in `docz-plugin-css` because this kind of transformation should be taking care of by this plugin ...

**Comment by tsnolan23** [comment]
Yeah, not  disagreeing with that!

**Comment by EmaSuriano** [comment]
Hi @pedronauck, I updated the version of `docz` and `docz-plugin-css` to 0.7.0 and the problem still persists :( This is the [repo](https://github.com/EmaSuriano/docz-css-bug-example), could you please check it out?

**Comment by pedronauck** [comment]
Sorry @EmaSuriano, I was excluding imports from `node_modules` at loaders 🙄 Now I think that is fixed on [v0.7.0](https://github.com/pedronauck/docz/releases/tag/v0.7.1)

**Comment by ekaoddlass** [comment]
@tsnolan23's fix here https://github.com/pedronauck/docz/issues/160#issuecomment-406883661 works for me, in case others are browsing this issue.

**Comment by kunokdev** [comment]
Hello, while I am using @tsnolan23 's config I get zero errors, but none of CSS was loaded.

```
export default {

  modifyBundlerConfig: config => {
    config.resolve.extensions.push(".scss")
    config.module.rules.push({
      test: /\.scss$/,
      use: ["style-loader", "css-loader", "sass-loader"],
    })

    return config
  },
}
```

and 

```
import { css } from "docz-plugin-css"

export default {
  plugins: [
    css({
      preprocessor: "sass",
      cssmodules: true,
    }),
  ],

}
```
throws error that it needs appropriate loader. 

```
Failed to compile.

./src/components/Avatar/styles.module.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import "../../_vars";
|
| .avatar {
```

Basicallty, I am using CRA2 with Sass and CSS modules, this way:
```
// @flow
import React from "react"

import styles from "./styles.module.scss"

type PropTypes = { value: string }

const Avatar = ({ value }: PropTypes) => (
  <div className={styles.avatar}>{value && value.substring(0, 1)}</div>
)

export default Avatar
``` 
Any suggestions?

**Comment by kunokdev** [comment]
importing 3rd party CSS such as of `semantic-ui-css` fails to compile, even tho I am using the css plugin:

```
Module parse failed: Unexpected character '@' (11:0)
You may need an appropriate loader to handle this file type.
|  *
|  */
> @import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
| /*!
|  * # Semantic UI 2.4.0 - Reset
```

**Comment by uguryildirim** [comment]
@kunokdev here is my solution (this is not best practice but work);

first copy compiled semantic.min.css and fonts to in /public folder. Change fonts path in semantic.min.css.

doczrc.js
`indexHtml: './index.html',
  modifyBundlerConfig: config => {
    config.entry.app.push('./public/semantic.min.css');
    config.module.rules.push({
      test: /\.css$/,
      use: ['style-loader', 'css-loader'],
    });
    return config;
  },`

index.html
`<!DOCTYPE html>
<html lang="{{ lang }}">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="{{ description }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="/public/semantic.css" />

    <title>{{ title }}</title>
    {{ head }}
  </head>

  <body>
    <div id="root" />
    {{ footer }}
  </body>
</html>`

this is work on my project.
