### ISSUE TITLE
How to make docz ignore README?

### ISSUE THREAD

**Issue by lucalves** [pedronauck/docz#1628]
## Question

Hello guys, I built the project with the `yarn build`, but docz is displaying the README file that is at the root in the deploy.

How can I ignore the readme and show only the rest?

**Comment by 1degrees** [comment]
![image](https://user-images.githubusercontent.com/30748321/119287244-b5f8a200-bc78-11eb-95de-bd353433ec19.png)

[Docz configuration](https://www.docz.site/docs/project-configuration)

**Comment by lucalves** [comment]
Thanks, @1degrees!
