### ISSUE TITLE
Some errors were encountered when parsing the FUNDING.yml file

### ISSUE THREAD

**Issue by BaseMax** [pedronauck/docz#1631]
Some errors were encountered when parsing the FUNDING.yml file:

    Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.

Learn more about formatting FUNDING.yml.

![Screenshot_2021-05-29_03-23-32](https://user-images.githubusercontent.com/2658040/120048774-40505580-c02d-11eb-8a32-d14d6b7232b1.png)

**Comment by LeslieOA** [comment]
@BaseMax +1 on this. 
@pedronauck You should [apply to get sponsored here on GitHub](https://github.com/sponsors/accounts).
There are many people who'd be very happy to fund your hard work, especially if it's frictionless. 🙂

**Comment by pedronauck** [comment]
Fixed, thanks to the tips 🙏🏻
