### ISSUE TITLE
Looks like abandoned, alternatives?

### ISSUE THREAD

**Issue by xobotyi** [pedronauck/docz#1632]
This projects seems to be abandoned (it is not even starting wit all defaults).

Any alternatives? (not the storybook or docosaurus as they're quite different and dont have good typescript config).

**Comment by pedronauck** [comment]
Hi dude, we're working again in order to reborn the project, update it and put it back on trails again :)

**Comment by xobotyi** [comment]
@pedronauck well thats a great news! =)

**Comment by pedronauck** [comment]
This is a thread explain what's happened https://github.com/pedronauck/docz/issues/1634

**Comment by Sebosek** [comment]
Let me ask again, is the project still alive?

**Comment by renatobenks** [comment]
Yes, we're working on a new major version @Sebosek, that hopefully will be launched soon. Just in the last month that we were on vacation where we drop off the project a little bit, but we're tracking most of the issues here because basically all of them are going to be closed in v3. As soon as we get there, we'll communicate it a little more clearly.

**Comment by Stevemoretz** [comment]
> Yes, we're working on a new major version @Sebosek, that hopefully will be launched soon. Just in the last month that we were on vacation where we drop off the project a little bit, but we're tracking most of the issues here because basically all of them are going to be closed in v3. As soon as we get there, we'll communicate it a little more clearly.

It's been almost 6 months any updates?
One important question does v3 contains multi version docz? Almost every documentation needs different ends up with multiple versions these days.

**Comment by nemonemi** [comment]
For others looking into this issue https://github.com/doczjs/docz/issues/1634
