### ISSUE TITLE
Can not give function to themeConfig

### ISSUE THREAD

**Issue by Florian-Guillot-Axa** [pedronauck/docz#165]
## Bug Report

**Describe the bug**

when using themeConfig on config, can't give function to theme.

**To Reproduce**

```js
// docz.js
export default {
  themeConfig: {
    colors: {
      myFirstColor: '#123456',
      mySecondColor: 'notAColor',
      myThirdColor: 'foo:bar',
      myFunction: color => color
    },
    mb: foo => foo + 'bar',
    customProp: 'foo:baz'
  }
};

//my_component.js
import { withTheme } from 'emotion-theming'
export default withTheme((props) => { console.log(props.theme); return null})

// console
breakpoints: {mobile: 420, tablet: 920, desktop: 1120}
colors: 
    ...
    link: "#0B5FFF"
    myFirstColor: "#123456"
    mySecondColor: "notAColor"
    myThirdColor: "foo:bar"
    ...
customProp: "foo:baz"
description: "My awesome app using Docz"
mode: "light"
mq: ƒ ()
ordering: "descending"
prismTheme: {...}
styles: {body: {…}, container: {…}, h1: {…}, h2: {…}, h3: {…}, …}
```

**Expected behavior**

theme.colors.myFunction should exists and be a function
theme.mb should exists and be a function

**Enviroment**

* OS: [10.13.4]
* Node/npm version: Node 8.11.3 /npm 5.6.0/Yarn 1.7.0

Does the default theme reject functions ? theme.mq is a function, and I can override it

**Comment by pedronauck** [comment]
This is something not possible, because we need to parse as json the config!

**Comment by giladgray** [comment]
@pedronauck there's a big note about using the `doczrc.js` so you _can_ do non-JSON things, so why can't we leverage that to allow functions in the config? 

is there a particular technical reason that the user theme config must be serializable?
