### ISSUE TITLE
Shape of Array not been displayed with Flow

### ISSUE THREAD

**Issue by Swapnull** [pedronauck/docz#167]
## Bug Report

Similar to https://github.com/pedronauck/docz/issues/153 but with flow. 

When using flow and defining the Prop Types as an array with a type, docz only outputs that it is an array. 
eg. 
```javascript
type Props = {
  /** Array of objects with the shape of label: string, content: any */
  tabs: Array<{ label: string, content: any }>
};
```
Produces
<img width="909" alt="screen shot 2018-07-25 at 12 10 09" src="https://user-images.githubusercontent.com/4456346/43197731-f6c4c1be-9003-11e8-8399-106c6e8f7dc0.png">

**Expected behavior**

running react-docgen produces
```sh
{"description":"","displayName":"Tabs","methods":[],"props":{"tabs":{"flowType":
{"name":"Array","elements":[{"name":"signature","type":"object","raw":"{ label: string, content: any
 }","signature":{"properties":[{"key":"label","value":{"name":"string","required":true}},
{"key":"content","value":{"name":"any","required":true}}]}}],"raw":"Array<{ label: string,content: any 
}>"},"required":true,"description":"Array of objects with the shape of label: string, content: any"}}}
```

If possible, grab the signature from there.

**Enviroment**

* OS: OSX 10.13.4
* Node/npm version: Node 8/npm 5
* Docz version: 0.7.1

**Comment by pedronauck** [comment]
Fixed on [v0.8.0](https://github.com/pedronauck/docz/releases/tag/v0.8.0)
