### ISSUE TITLE
Does not work with SVGR

### ISSUE THREAD

**Issue by danielbayerlein** [pedronauck/docz#169]
## Bug Report

**Describe the bug**

**docz** does not work with [SVGR](https://github.com/smooth-code/svgr). I get the following error:

```
Failed to execute 'createElement' on 'Document': The tag name provided ('/static/img/test.svg') is not a valid name.
```

**To Reproduce**

1. Add `@svgr/webpack` as dependency
2. Add the SVGR-loader to the webpack configuration:
```js
{
  test: /\.svg$/,
  use: {
    loader: '@svgr/webpack',
    options: {
      icon: true
    }
  }
}
```
3. Add a dummy `test.svg` to the `/svg` folder
4. Create a dummy `index.mdx` file at the project root
```js
---
name: Icon
---

import { Playground } from 'docz'
import Icon from './svg/test.svg'

# Icon

<Playground>
  <Icon />
</Playground>
```
5. Start `docz`...

I also tested it with a `modifyBundlerConfig` with the same result.

```js
modifyBundlerConfig: config => {
  config.module.rules.push({
    test: /\.svg$/,
    use: {
      loader: '@svgr/webpack',
      options: {
        icon: true
      }
    }
  })

  return config
}
```

**Expected behavior**

The icon is displayed.

**Enviroment**

* OS: macOS 10.13.5
* Node/npm version: Node.js v8.11.3 / npm 6.2.0

**Comment by danielbayerlein** [comment]
Another test with [svg-inline-loader](https://github.com/webpack-contrib/svg-inline-loader) produced the same error. Looks like a problem with webpack loaders.

**Comment by pedronauck** [comment]
By default we're using `file-loader` as svg loader, so what you can do is replace it to use svgr loader:

```
export default {
  modifyBundlerConfig: config => {
    const idx = config.module.rules.findIndex(
      r => r.test.toString() === '/\\.(svg)(\\?.*)?$/'
    )

    config.module.rules[idx] = {
      test: /\.svg$/,
      use: {
        loader: '@svgr/webpack',
      },
    }

    return config
  },
}
```

**Comment by danielbayerlein** [comment]
Thank you 🌻

**Comment by danielbayerlein** [comment]
Now you can use the `docz-plugin-svgr` plugin! 🕺
