### ISSUE TITLE
How to resolve font files in css files?

### ISSUE THREAD

**Issue by nerijusgood** [pedronauck/docz#174]
## How can I resolve font, image and other files imported in CSS, while using PostCSS preprocessor?

**I loaded all the postcss plugins via docz-plugin-css and it works fine, but font files (and other files) always causes error:**

```
These relative modules were not found:

* ../fonts/icons/icomoon.eot in ./node_modules/css-loader??ref--10-1!./node_modules/postcss-loader/lib??ref--10-2!./client/jtj.css
```

How can I include other loader like, file-loader or url-loader?

**Comment by pedronauck** [comment]
You can use `modifyBundlerConfig` to add custom loaders:

```js
// doczrc.js
export default {
  modifyBundlerConfig: (config) => {
    /* your loader logic here */
    return config
  }
}
```
