### ISSUE TITLE
Documentation CSS/SASS/LESS/Stylus variables and mixins

### ISSUE THREAD

**Issue by olavoasantos** [pedronauck/docz#175]
# Description
This feature would allow creating a documentation of CSS and CSS preprocessors variables and mixins. This would be quite useful, not only as a reference for developers, but it would also aid the documentation for Design Systems.

**Comment by pedronauck** [comment]
Please @olavoasantos, can you write your suggestion with a better description on [our roadmap](http://feedback.docz.site/roadmap)?
