### ISSUE TITLE
Docz app hangs when using with typescript component

### ISSUE THREAD

**Issue by maksimsemenov** [pedronauck/docz#177]
## Bug Report

**Describe the bug**
When I'm trying to use a Docz with a typescript component, it just hangs the whole tab without any errors and shows an empty screen
<img width="1680" alt="screen shot 2018-07-31 at 10 21 44 am" src="https://user-images.githubusercontent.com/3608139/43439209-922ad110-94ab-11e8-8f3f-5844bc685f15.png">

**To Reproduce**
1. Import a component from `*.tsx` file
2. Navigate to this component
3. See the Docz app hanging there

[Reproduce repo](https://github.com/maksimsemenov/docz-bug)
Note that if I import component from `Input1.js` everything works fine

**Expected behavior**
It should show a component page

**Enviroment**
* OS: OSX 10.13.6
* Node/npm version: node 8.11.1/ npm 6.2.0

P.S. The project is awesome, btw. Thaks a lot for doing such a great job

**Comment by pedronauck** [comment]
If you want to use typescript you need to enable it on your `doczrc.js` like that:

```js
export default {
  typescript: true
}
```

Or you can pass as an argument to cli

```bash
$ docz dev --ts
```
