### ISSUE TITLE
typescript/PropsTable: having trouble getting the layout of the table to look right

### ISSUE THREAD

**Issue by benhinchley** [pedronauck/docz#178]
## Question
I have recently transitioned the [documentation](https://sajari-sdk-react.netlify.com/) for [@sajari/sdk-react]() to docz, and there are a few little kinks I am struggling to determine the cause of. The main one being the layout of the `<PropsTable />` component.

The issue is highlighted here on our [`<Input />`](https://sajari-sdk-react.netlify.com/components/input#props) component.

**Comment by Swapnull** [comment]
Maybe the best solution to this is to make the description optional to give the rest of the table more room? So we could invoke it like `<PropsTable of={Input} description={false}>`.

This should hopefully be a relatively small change https://github.com/pedronauck/docz/blob/f7cb0b6f4ee80769aa7bc3050ac24241fe270933/packages/docz/src/components/PropsTable.tsx#L117.

**Comment by pedronauck** [comment]
Please update docz to the latest version, this issue was resolved 🙏
