### ISSUE TITLE
Failed to compile: Unexpected token

### ISSUE THREAD

**Issue by MrKumaPants** [pedronauck/docz#179]
## Bug Report

**Describe the bug**

Just installed docz and webpack. No custom docz config. No mdx files.

**To Reproduce**

```shell
 ERROR  Failed to compile with 1 errors                                                                                                      11:38:56 AM

 error  in ./.docz/app/index.jsx

Syntax Error: SyntaxError: /Users/ntomsic/Projects/cmaas/aw-mono/packages/ns-web-core-ui/.docz/app/index.jsx: Unexpected token (16:18)

  14 | const render = (Component = Root) => {
  15 |   onPreRender()
> 16 |   ReactDOM.render(<Component imports={imports} />, root, onPostRender)
     |                   ^
  17 | }
  18 |
  19 | if (module.hot) {


 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Comment by pedronauck** [comment]
Can you give me a sample of your `package.json` @MrKumaPants ?

**Comment by Swapnull** [comment]
@MrKumaPants Do you have babel installed? It looks like it is not compiling the JSX. You need to install babel and babel-preset-react.
 
[@babel/preset-react](https://www.npmjs.com/package/@babel/preset-react) for babel 7 - Still in beta, but is pretty widely used. 

[babel-preset-react](https://www.npmjs.com/package/babel-preset-react) for babel 6. - You will also need the [docz-plugin-babel6](https://github.com/pedronauck/docz/tree/master/packages/docz-plugin-babel6) if you choose to use this.

**Comment by pedronauck** [comment]
I'll close this issue in favor of the missed response!
