### ISSUE TITLE
vue support

### ISSUE THREAD

**Issue by sobolevn** [pedronauck/docz#18]
This tool looks amazing! 🎉 Do you have any plans for `vue` support?

**Comment by jhonmike** [comment]
support in multi libs, as there are cases where we need to maintain components of more than one lib in the company, my case :'( AngularJS1.x  and VueJS

**Comment by pedronauck** [comment]
Hi @sobolevn, for sure we have plans for Vue. I think that the better way is creating a plugin called `docz-plugin-vue` that integrates Vue components with React.

Some good choice is using something like [Vuera](https://github.com/akxcv/vuera) or [react-vue](https://github.com/SmallComfort/react-vue)!

Pr are welcome ✌️

**Comment by marceloavf** [comment]
@sobolevn Started the Vue support plugin here https://github.com/marceloavf/docz-plugin-vue

**Comment by marceloavf** [comment]
@morficus the repository was archived in favor of using a branch inside this repository

We have a working in progress here https://github.com/mdx-js/mdx/pull/239 and also a PR in this repository as we can see here https://github.com/pedronauck/docz/pull/95

If you can help us, feel free to comment and give your opinion in these links, it still a hard work, unfortunately

**Comment by marceloavf** [comment]
Read the comment above @robodude please.
