### ISSUE TITLE
Can't copy html output of Playground.

### ISSUE THREAD

**Issue by cheolee** [pedronauck/docz#181]
## Bug Report

When I copy the html output of `Playground` component, it copy the jsx code rather than html code.

**To Reproduce**

1. Make any `Playground` on docs.
2. Click `html` output button.
3. Click copy icon.
4. Paste the copied text on anywhere.

**Expected behavior**

Copy `html` code to clipboard rather than `jsx` code.

**Enviroment**

* OS: OSX 10.13.6
* Node/npm version: Node 8.9.1, npm 6.1.0, docz 0.8.0

**Additional context/Screenshots**

<img width="521" alt="2018-08-01 12 23 42" src="https://user-images.githubusercontent.com/5275823/43499291-c2e2e4c0-9585-11e8-8856-a0a992f2026d.png">

If click the copy button on screenshot, it copies `<TextField placeholder="플레이스홀더" />`.

P.S.
I use docz to document design system libraries of my company.
I really love docz. Thank you for the awesome project.

**Comment by pedronauck** [comment]
Fixed on release [v0.9.5](https://github.com/pedronauck/docz/releases/tag/v0.9.5)
