### ISSUE TITLE
tsx support

### ISSUE THREAD

**Issue by huodon** [pedronauck/docz#19]
My project created by  [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript). I tried to import `.tsx` component but got 'This relative module was not found'  message.  Is the usage incorrect or is it not yet supported?

**Comment by pedronauck** [comment]
Did you put the `.tsx` extension at import?

```
import { Something } from './Something.tsx'`
```

I don't even know why this is mandatory on mdx 😞

**Comment by albinekb** [comment]
You need to enable typescript via CLI `--typescript` or your docz config file.

**Comment by huodon** [comment]
docz using babel7 compile tsx, It does not support `const enum` , So i can't use it for now . 
Thanks @albinekb .

**Comment by pedronauck** [comment]
You can modify your bundler config to use `ts-loader` instead of babel plugin @huodon

**Comment by huodon** [comment]
Thank you @pedronauck , the problem was solved. 👍

**Comment by cvle** [comment]
@huodon How did you use `ts-loader` instead? I tried and I failed.

**Comment by pedronauck** [comment]
@cvle if you want to use `ts-loader` you can just use [docz-plugin-babel6](https://github.com/pedronauck/docz/blob/master/packages/docz-plugin-babel6) that implements ts-loader together with babel 6 ✌️

**Comment by mbrn** [comment]
if i want to use ts-loader with options: transpileOnly, how can i implement this to doczrc.js

**Comment by pedronauck** [comment]
You can do something like we did on docz-plugin-babel6 @mbrn 
https://github.com/pedronauck/docz/blob/master/packages/docz-plugin-babel6/src/index.ts
