### ISSUE TITLE
indexHtml property in the config prevents docz from running

### ISSUE THREAD

**Issue by christoph-fricke** [pedronauck/docz#191]
## Bug Report

**Describe the bug**

I added the `indexHtml` property in the `doczrc.js` config to provide a html file. My src property is `'./src'` and I have a `template.html` (content below) in the src folder to override the `index.html`. I tried multiple values for `indexHtml` like:
- `./template.html`
- `./template`
- `template.html`
- `template`
- `/template.html`
- `/template`

All variations cause the script to crash. Bug trace is below.

**To Reproduce**

1. Clone provided repo
2. Install dependencies
3. Run `npm run docz:dev`
4. See console output

```shell
×  fatal     Failed to process your server: TypeError: d is not a function
    at writeAppFiles (C:\Users\chris\Documents\docz-bug\node_modules\docz-core\dist\index.js:1:7906)
```

** Repo with code to reproduce **
https://github.com/christoph-fricke/docz-bug

**Expected behavior**

Override the index.html and insert Roboto font.

**Enviroment**

* OS: Windows 10 1803 Build 17134.165
* Node/npm version: Node 10.3.0/ npm 6.1.0

**Additional context/Screenshots**
Content of template.html:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,500,700">
</head>

<body>
    <div id="root" />
</body>

</html>
```

**Comment by pedronauck** [comment]
Sorry, but the ìndex.html` is not relative to your source folder, but to the root folder. So you need to change the path to be like this:

```js
export default {
  indexHtml: './src/template.html'
}
```
