### ISSUE TITLE
Layout does not scale for Android phone

### ISSUE THREAD

**Issue by evantbyrne** [pedronauck/docz#192]
Tested website in Chrome on Android. Neither home page nor documentation section scales.

**Comment by subodhpareek18** [comment]
Could you please attach a screenshot of what you see?

**Comment by evantbyrne** [comment]
![screenshot_20180805-192114](https://user-images.githubusercontent.com/138734/43720066-6fdbd684-995d-11e8-9fe3-0d28041fd161.png)

**Comment by pedronauck** [comment]
Please open this issue on https://github.com/pedronauck/docz-website 🙏
