### ISSUE TITLE
Decorator error.

### ISSUE THREAD

**Issue by hamzaerbay** [pedronauck/docz#193]
## Question
I'm using `react app rewired` and `mobx`, 
I'm getting decorator error when I try to build.
**Description**
![image](https://user-images.githubusercontent.com/5136093/43703203-eb46ccc2-9910-11e8-8223-54e3a5f1ef2a.png)

**Comment by pedronauck** [comment]
You need to use a babel plugin to add decorators since they are not supported by default on docz!

**Comment by Joe1220** [comment]
I cannot use babel plugin for decorators... How can i use decorator? please help me..
