### ISSUE TITLE
Markdown ``` crashes the application if no code specified (``` vs ```javascript)

### ISSUE THREAD

**Issue by ilyanoskov** [pedronauck/docz#195]
## Bug Report

whenever I have some code that I need to put in code block it crashes the application if I don't specify exact code format.

/```/ - this will not work

/```javascript/ - this will work

Error message: 
undefined is not an object (evaluating 'e.props.props.className')

**Comment by pedronauck** [comment]
Fixed on [v0.9.6](https://github.com/pedronauck/docz/releases/tag/v0.9.6)
