### ISSUE TITLE
How do I set which md file is the homepage?

### ISSUE THREAD

**Issue by hayk94** [pedronauck/docz#198]
## Question

**How do I set which md file is the homepage?**

**Comment by hayk94** [comment]
```
---
name: Home
route: /
---
```

This should be put in the md path. I wasn't able to find anything about this in the docs. It would be nice to add it.

**Comment by hayk94** [comment]
```
---
name: Home
route: /
---
```

This should be put in the md path. I wasn't able to find anything about this in the docs. It would be nice to add it.

**Comment by pedronauck** [comment]
Have [this section](https://www.docz.site/introduction/customizing#document-settings) on website!

**Comment by crswll** [comment]
Trying to figure out how to do this and the link above no longer works unfortunately. This one seems close but it's not super clear: https://www.docz.site/docs/document-settings
