### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by programmer-yang** [pedronauck/docz#20]
I follow the steps on the website [here](https://www.docz.site/introduction/getting-started)
my directory structure:
```
index.mdx
package.json
yarn.lock
```
But my page has no content

look:
![image](https://user-images.githubusercontent.com/8612167/41328680-f7b58e88-6efb-11e8-9d62-709894d03cc2.png)

**Comment by pedronauck** [comment]
Which operational system you're using?

**Comment by programmer-yang** [comment]
@pedronauck 
mac
node: v8.11.1
npm: 5.6.0
yanr:1.6.0

**Comment by pedronauck** [comment]
Do you can show your project source code?

**Comment by programmer-yang** [comment]
[here](https://github.com/programmer-yang/test-react-compoents-doc)

**Comment by MrBoutte101** [comment]
getting the same error.

mac
node: 8.9.3
npm: 5.5.1
yarn: 1.2.1

**Comment by Swapnull** [comment]
If you put the front matter of `route: '/'` it will fix it. eg. 
```
---
name: Hello World
route: '/'
---

# Hello World
Im an MDX file! 
```
I am not sure if is is supposed to pick up `<source>/index.mdx` as the front page? May be a cool idea if possible @pedronauck

**Comment by pedronauck** [comment]
Thanks to help here @Swapnull, maybe this can be a good idea.

**Comment by overra** [comment]
I just discovered the custom `.babelrc` I had for my existing next.js code base was causing this issue. 

I noticed `load-cfg` checks for `${name}.json` so I tried creating a `babel.json` with `babel-preset-react-app` specifically for docz but I wasn't able to get it running successfully.

Is docz intended to be used alongside the full app?

**Comment by overra** [comment]
I just realized I didn't have the babel 7 version of `babel-preset-react-app` installed. Now it's working fine and next.js uses `.babelrc` while docz uses `babel.json`.
