### ISSUE TITLE
Window scroll event doesn't fire.

### ISSUE THREAD

**Issue by loganfromlogan** [pedronauck/docz#204]
## Bug Report

**Describe the bug**
I have a component that registers a window scroll event when it mounts (and removes it when it unmounts). However, the scroll event is never triggered.

**To Reproduce**

1. Go to https://hungry-franklin-2ebeaf.netlify.com/src-sticky-bar-doc
2. Open the console (A "scrolling" message is presented w/e the scroll event is tirggered)
3. Scroll down to the bottom of the page
4. No message in console (and bar doesn't stick)

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

https://github.com/SeaMonster-Studios/react-components/tree/master/src/StickyBar

**Environment**

* OS: macOS 10.13.6
* Node 10.7.0
* NPM 6.2.0

**Comment by pedronauck** [comment]
Fixed in the newest release!
