### ISSUE TITLE
There are not toc in menu

### ISSUE THREAD

**Issue by zWingz** [pedronauck/docz#206]
## Bug Report
versions 0.9.6

```javascript
// doczrc
import { css } from 'docz-plugin-css'
export default {
  themeConfig: {
    mode: 'light',
  },
  hashRouter: true,
  plugins: [
    css({
      preprocessor: 'sass'
    })
  ]
}
```

```
// index.mdx
---
name: Usage
route: /
order: 1
---
# Usage

## Image
....
## Preview
....
```

**Expected behavior**

like
![image](https://user-images.githubusercontent.com/13031838/43935365-3963263a-9c86-11e8-97d1-b53b9c9d3749.png)

**Environment**

* OSX 10.12.6
* Node 8/npm 5

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/13031838/43934823-b6667374-9c83-11e8-90e8-7203f6fb74a4.png)
![image](https://user-images.githubusercontent.com/13031838/43934833-be1c9d28-9c83-11e8-84f0-06a4ac85dd3b.png)

**Comment by zWingz** [comment]
i find a example website, like [https://github.com/EmaSuriano/react-hotkey-tooltip](https://github.com/EmaSuriano/react-hotkey-tooltip)

clone the repo and `npm run docz:dva`

the problem as same as me.
![image](https://user-images.githubusercontent.com/13031838/43943000-a19307b8-9cac-11e8-836a-1c3a874bb701.png)


but [https://react-hotkey-tooltip.netlify.com/#/](https://react-hotkey-tooltip.netlify.com/#/) is right

![image](https://user-images.githubusercontent.com/13031838/43943012-a8207eee-9cac-11e8-99c8-d440ffda2e3b.png)

**Comment by zWingz** [comment]
i find an example like [https://github.com/EmaSuriano/react-hotkey-tooltip](https://github.com/EmaSuriano/react-hotkey-tooltip)

clone the repo and `npm run docz:dev`

The same problem exists
![image](https://user-images.githubusercontent.com/13031838/43943854-a1812f86-9caf-11e8-9d60-de27e8f24edf.png)

but the [website](https://react-hotkey-tooltip.netlify.com/#/) has no problem
![image](https://user-images.githubusercontent.com/13031838/43943869-b10f219c-9caf-11e8-9d4c-6bd9675a7a86.png)

**Comment by wldcordeiro** [comment]
I've noticed this occurring as well, seems to be a regression of some sort.

**Comment by pedronauck** [comment]
I forked [react-hotkey-tooltip](https://github.com/EmaSuriano/react-hotkey-tooltip) and installed the [last version](https://github.com/pedronauck/docz/releases) of docz and everything is fine now 🙏

**Comment by wldcordeiro** [comment]
@zWingz Are you on latest `docz`? That might be what you need.

**Comment by chris-lyu** [comment]
On latest(0.10.3), still having this issue, so I downloaded the Example Basic, same issue, after I click on the Button component, the Components dropdown just collapses.

**Comment by zWingz** [comment]
@wldcordeiro 
![image](https://user-images.githubusercontent.com/13031838/44243606-90eebf00-a202-11e8-88fe-20cfdab6e6a2.png)

**Comment by zWingz** [comment]
Example Basic
clone the `docz` and `run` example

![image](https://user-images.githubusercontent.com/13031838/44243709-21c59a80-a203-11e8-9eeb-aff0eb549d8a.png)

**Comment by michelson** [comment]
Hi @pedronauck , I can confirm this is working on the docz default theme, version 0.10.3.
But how could I implement that behavior on a custom theme? I've followed the example and I can only show the root links 

here is the example: https://michelson.github.io/dante2/#/src-index

my menu implementation is as follows

```es6
import React from 'react'
import { Docs, Link } from 'docz'

const Menu = () => (
  <Docs>
    {({ docs }) => (
      <ul>
        {docs.map(doc => (
          <li key={doc.id}>
            <Link to={doc.route}>
              {doc.name}
            </Link>
          </li>
        ))}
      </ul>
    )}
  </Docs>
)

export default Menu
```
