### ISSUE TITLE
npm run build Failed to compile. Cannot find module 'tapable', entire directory deleted

### ISSUE THREAD

**Issue by Strum355** [pedronauck/docz#207]
## Bug Report

When running `npm run build` with the script as provided by the docs, the error seen below happens, the entire directory and its parent directory are deleted (resulting in .git being deleted as well as all my working files) and all thats left is shown in the second screenshot

Directory structure:
```
Hibanana
|-docz
|	|-md
|	|-package.json etc
|-.gitignore
|-.git
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*
No repo exists as the directory was deleted after running the script before i pushed

**Environment**

* OS: Linux Mint 19
* Node/npm version: Node 10.8.0 NPM 6.2.0

**Additional context/Screenshots**

<details>

![image](https://user-images.githubusercontent.com/18282288/43955914-12e3d770-9c9a-11e8-8e54-7e9bc36347a1.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/18282288/43956019-75f1df06-9c9a-11e8-9b0d-fe445554429e.png)

</details>

**Comment by pedronauck** [comment]
Can you show your `doczrc`, `package.json` and `babelrc` files?

**Comment by Strum355** [comment]
Well they were all deleted when i ran `npm run build`, best i can do is try to reproduce them as closely as i can

**Comment by pedronauck** [comment]
Please, try to do that if possible 🙏

**Comment by Strum355** [comment]
doczrc.js
<details>
```js
export default {
    title: 'Banana',
    description: 'This is my awesome documentation',
    src: './md',
    dest: '../',
    protocol: 'http',
    themeConfig: {
        colors: {
        primary: '#A00',
        },
    },
}
```
</details>

package.json
<details>
```json
{
  "name": "dev",
  "version": "1.0.0",
  "scripts": {
    "dev": "docz dev",
    "build": "docz build"
  },
  "dependencies": {
    "docz": "^0.9.6"
  }
}
```
</details>

I believe it may be because i set the output directory to be the parent directory, after which i can only assume that it purges everything before writing the new files, fails because it deleted node_modules and cant find the required modules

**Comment by pedronauck** [comment]
@Strum355 this happened because you set your build destination folder (`dest` flag on doczrc) as `../`, so you deleted the entire folder. Please, set your destination folder to some folder inside the root directory of your project.
