### ISSUE TITLE
Cannot find module 'webpack/schemas/WebpackOptions.json'

### ISSUE THREAD

**Issue by guilhermegm** [pedronauck/docz#208]
## Bug Report

I'm trying to run docz:dev and get the following error:
Cannot find module 'webpack/schemas/WebpackOptions.json' 

**To Reproduce**

1. I have installed react using react-create-app
2. Inside the project created I have installed docz (npm i docz)
3. I have added "docz:dev": "docz dev" in package.json
4. And I tried to run npm run docz:dev

**Environment**

* Ubuntu 18.04 LTS
* Node v10.7.0
* Npm 6.1.0

**Additional context/Screenshots**

![screenshot from 2018-08-10 10-39-31](https://user-images.githubusercontent.com/670000/43961225-b4f25380-9c8a-11e8-98ec-7e12829727a2.png)

**Comment by pedronauck** [comment]
Can you give a shot of your `package.json`?

**Comment by guilhermegm** [comment]
![screenshot from 2018-08-10 14-07-35](https://user-images.githubusercontent.com/670000/43971257-c403a614-9ca6-11e8-9132-12733fc039bf.png)

I just installed react:
https://reactjs.org/docs/create-a-new-react-app.html

and docz (npm i docz)

**Comment by pedronauck** [comment]
Unfortunately, docz doesn't have integration with old webpack version. If you want to use it you need to upgrade your webpack version to 4.

**Comment by peterph-am** [comment]
I also have this issue when installing my packages with npm, however when installed with yarn it runs fine. Does Docz not support npm installations?

**Comment by alexlee-dev** [comment]
@peterph-am I'm also having this issue. Someone opened it as another issue here. Issue #357 .
