### ISSUE TITLE
Unable to use PropsTable

### ISSUE THREAD

**Issue by louis-pvs** [pedronauck/docz#21]
## Bug Report
`getValue` this function in `<PropsTable>` causing error

**Describe the bug**
Once include `PropsTable` component in my mdx file it throw error

**To Reproduce**
1. Go to [Button.mdx](https://github.com/louis-pvs/mrcw/blob/feature/docz/src/Button.mdx)
2. Include `PropsTable` as [describe](https://www.docz.site/introduction/documenting-your-things#built-in-components)
3. See error
```shell
Uncaught TypeError: Cannot read property 'replace' of undefined at getValue 
```

**Expected behavior**
To see the `<PropsTable>` with correct props defined in [`../lib/Button/index.js`](https://github.com/louis-pvs/mrcw/blob/feature/docz/lib/Button/index.js)

**Enviroment**
```json
{
  "engines": {
    "node": "8.11.1",
    "npm": "5.7.1",
    "yarn": "1.6.0"
  }
}
```

**Additional context/Screenshots**
![screen shot 2018-06-13 at 3 32 49 pm](https://user-images.githubusercontent.com/7659194/41336528-19064f82-6f1f-11e8-89b0-d53bc913bf47.png)
![screen shot 2018-06-13 at 3 33 27 pm](https://user-images.githubusercontent.com/7659194/41336548-24c670a4-6f1f-11e8-9544-181abb552ed3.png)

**Comment by emersonlaurentino** [comment]
Hey @louis-pvs I'm having the same problem. 

I belive that problem is `PropTypes.oneOfType`. If you stop use it the error not is shown.

**Comment by pedronauck** [comment]
I didn't try `<PropsTable>` using `oneOfType` in prop types, I will see what's happening. Thanks guys ✌️

**Comment by albinekb** [comment]
Same issue with `.instanceOf`:

```js
propTypes = {
  date: PropTypes.instanceOf(Date),
}
```

Should I open another issue for this?

**Comment by emersonlaurentino** [comment]
@albinekb the problem is similar, so i believe we can keep it here.

these also have the same problem: 
```jsx
propTypes = {
  optionalMessage: PropTypes.instanceOf(Message),
  optionalEnum: PropTypes.oneOf(['News', 'Photos']),
  optionalUnion: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.instanceOf(Message)
  ]),
  optionalArrayOf: PropTypes.arrayOf(PropTypes.number),
  optionalObjectOf: PropTypes.objectOf(PropTypes.number),
  optionalObjectWithShape: PropTypes.shape({
    color: PropTypes.string,
    fontSize: PropTypes.number
  }),
}
```

**Comment by renatorib** [comment]
I started work on that issue.

**Comment by albinekb** [comment]
@renatorib I made my own, if you want to have a look: https://gist.github.com/albinekb/f59feb84273279d1d45f603aee8eb496
![image](https://user-images.githubusercontent.com/5027156/41408416-e5563864-6fd2-11e8-9e75-025535ed460c.png)

**Comment by renatorib** [comment]
Looks great @albinekb
