### ISSUE TITLE
need to skip babelrc on docz

### ISSUE THREAD

**Issue by michelson** [pedronauck/docz#212]
Hi, I'm using docz along with a custom solution for build a npm pkg. Thing is: when I run docz my configuration of babelrc is used and it fails. I've seen that I can change the babel configuration for docz with 'modifyBabelRc' in doczrc file. So I would like to encapsulate the babel config for docz inside the docz config and skip the babelrc config . For that I've set the option `babelrc.babelrc = false`. This is supposed to skip the babelrc ?  if not how can I accomplish that ?
awesome library
best

**Comment by pedronauck** [comment]
You can do it by

```js
export default {
  modifyBabelRc: (config) => {
    config.babelrc = false
    return config
  }
}
```

**Comment by michelson** [comment]
it seems that the babel config is passed through even if the babelrc is set
to false.
I've check that in version 0.9.6

Atte.
Miguel Michelson Martinez
www.vadb.org <http://vadb.org>

**Comment by ronghang** [comment]
The same problem. The babel config is passed through even if the babelrc is set
to false in modifyBabelRc.

**Comment by Kivylius** [comment]
I had the same issue and `config.babelrc = false` doest work in v0.12. I got it working with a bit of hack:

in your `.babelrc', put a unnecessary comma at the end, babel will ignore it, but docz will fail to parse and not use it. e.g:
```
{
    plugins: [ 
        // ....
    ], <--
}
```
