### ISSUE TITLE
Newly created .mdx files give a 404 when reloading the page

### ISSUE THREAD

**Issue by rovansteen** [pedronauck/docz#214]
## Bug Report

**Describe the bug**

If you have `docz` running the newly created `.mdx` file appears nicely in the sidebar and navigating to it works fine but if you reload the page after that it gives you a 404 and you have to restart `docz` to have it appear again.

**To Reproduce**

1. Run `docz:dev`
2. Create a new `.mdx` file
3. Navigate to that newly created `.mdx` file
4. Reload the page
5. 404

**Expected behavior**

After reloading the page it should correctly display all created `.mdx` files that were created when `docz` is running.

**Environment**

* OS: OS X 10.13.6
* Node/npm version: Node 10.0.0

**Comment by pedronauck** [comment]
Try it now with [v0.10.2](https://github.com/pedronauck/docz/releases/tag/v0.10.2) @rovansteen, was a bug inside our cache system 🙏

**Comment by prvnbist** [comment]
I'm getting this issue in v2.1.1, how do I fix it?

**Comment by rodrigolabs** [comment]
> I'm getting this issue in v2.1.1, how do I fix it?

Same here, v2.2.0.
