### ISSUE TITLE
Can't import component

### ISSUE THREAD

**Issue by eskab** [pedronauck/docz#215]
## Bug Report

**Describe the bug**

I just wanted to play with docz and check how it works. I've created sample component and sample page and I get this error:

```
WARNING  Compiled with 1 warnings                                                                                                                                        14:18:41

 warning  in ./src/components/Foo/Foo.mdx

"export 'Foo' was not found in './Foo'
```

Foo.mdx code
```
---
name: Foo
---
import { Foo } from "./Foo"

# Foo

this is foo:

<Foo>sample</Foo>
```

Foo.tsx code
```
import React, { PureComponent } from "react";

export class Foo extends PureComponent {
  render() {
    return this.props.children;
  }
}
```

**Environment**

* OS: macOS 10.13.6
* Node/npm version: Node 10.8.0

Have you seen something similar earlier?

// Right now I'm unable to start docz server (versions 0.10.0 and later):
```
✖  fatal     Failed to process your server: TypeError: Cannot read property 'replace' of undefined
    at getRepoUrl (/aaa/node_modules/docz-core/dist/index.js:1:7375)
    at getInitialConfig (/aaa/node_modules/docz-core/dist/index.js:1:9931)
    at Object.init (/aaa/node_modules/docz-core/dist/index.js:1:10148)
    at Promise.all.Array.from.map (/aaa/node_modules/docz-core/dist/index.js:1:10825)
    at Array.map (<anonymous>)
    at DataServer.init (/aaa/node_modules/docz-core/dist/index.js:1:10802)
    at Object.dev (/aaa/node_modules/docz-core/dist/index.js:1:24808)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by eskab** [comment]
When I change it to default export, there are no errors on the build but after I click "Foo" tab on the left I see blue icon of docz on the right and browser crashes (I have to kill chrome process).

<img width="1394" alt="zrzut ekranu 2018-08-16 o 10 05 11" src="https://user-images.githubusercontent.com/13819284/44196317-e6ac6400-a13b-11e8-807f-145fa0389b78.png">

**Comment by eskab** [comment]
@nicholasess any ideas?

**Comment by nicholasess** [comment]
@eskab do you modify doczrc ou add plugins? I’m trying to think about what is happen...

**Comment by eskab** [comment]
no plugins added, `doczrc.js` has only title:

```
export default {
  title: "Fooo",
};
```

**Comment by AntonSerous** [comment]
Hi guys, I'm facing the same issue and not sure why it happens and how to deal with it. 

Repository to reproduce: https://github.com/AntonSerous/docz-error

Rollup gets it build with no question so I wonder why docz doesn't like it. Please help 🙏 🙏 🙏

**Comment by AntonSerous** [comment]
@pedronauck Could you please reopen? Thanks
