### ISSUE TITLE
Src tree in edit button link

### ISSUE THREAD

**Issue by andresggarcia** [pedronauck/docz#219]
## Description
I have the src of the docs on another branch (not master), and I would like to keep it that way.

I can see in [this line](https://github.com/pedronauck/docz/blob/553f90cd2bcacc0c671a74d505862ad8419a62f2/packages/docz-core/src/utils/repo-info.ts#L13) that the source tree/branch is hardcoded on `master` (please correct me if i'm wrong).

Is there a way of configuring this? If not, could it be implemented?

Thanks!

**Comment by pedronauck** [comment]
Release on [v0.10.3](https://github.com/pedronauck/docz/releases/tag/v0.10.3).
Just add a `editBranch` property on your `doczrc.js`

```js
// doczrc.js
export default {
  editBranch: 'production'
}
```
