### ISSUE TITLE
Require is not defined in Playground

### ISSUE THREAD

**Issue by zWingz** [pedronauck/docz#221]
## Bug Report

`variable` run in `server`
but error in `Playground`

![image](https://user-images.githubusercontent.com/13031838/44068390-4c694a88-9fac-11e8-89a5-e7bfbf9140d6.png)

should i change my code ?

Environment

OS: OSX 10.12.6
Node/npm version: Node 8.11.2/NPM 6.3.0

**Comment by nicholasess** [comment]
@zWingz Can you use the import in start instead of require ?
example:
```
import logo from "./assets/logo.jpg"

<Image src={logo}  width={120} height={120}>
```

**Comment by zWingz** [comment]
@nicholasess ok.

**Comment by zWingz** [comment]
error when defined variable outside `Playground`
```jsx
const a = 1
<Playground>
  <div>{b}</div>
</Playground>
```
![image](https://user-images.githubusercontent.com/13031838/44128109-95464f90-a073-11e8-86d0-28e061dcfd3b.png)

**Comment by nicholasess** [comment]
@zWingz docz is used to show the components in the context, i think that you need to use your logic in component and then the playground will work

**Comment by pedronauck** [comment]
For sure @zWingz, how @nicholasess said, you need to create your javascript logic inside the playground to avoid this type of thing. Is not a good practice keep things out of the context!

**Comment by pedronauck** [comment]
About `require`, I'm doing a new release with this fix soon!

**Comment by zWingz** [comment]
thanks @nicholasess @pedronauck

**Comment by pedronauck** [comment]
Unfortunately is not a good practice for webpack put `require` on playground scope, you can read [this post](https://github.com/dcodeIO/protobuf.js/issues/339) to know more about that
