### ISSUE TITLE
Yarn workspaces support

### ISSUE THREAD

**Issue by brunolemos** [pedronauck/docz#225]
## Bug Report

**Describe the bug**

Compilation fail when importing components from another yarn workspace.

**To Reproduce**

1. Create one `docz` workspace and one `shared` workspace
2. Create components on `shared`
3. Import them on `docz`

```shell
Module parse failed: Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
| 
| export default () => (
>   <Touchable onPress={() => alert('pressed')}>
|     <Text style={styles.text}>Shared Button</Text>
|   </Touchable>

 @ ./src/index.mdx 9:0-61 66:93-99
 @ ./.docz/app/imports.js
 @ ./.docz/app/index.jsx
 @ multi ../node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Environment**

* OS: macOS 10.14
* Node/npm version: Node 8.11.3 / npm 5.6

**Additional context/Screenshots**
If I move the docz code to `shared` it will work. It only works if the components are in the same "project". If you try to import from another workspace it fails. 

If you setup docz in the root directory (outside all workspaces) it fails as well, but with another error.

![image](https://user-images.githubusercontent.com/619186/44122193-23b42598-9ff9-11e8-98f2-60af3432c572.png)

![image](https://user-images.githubusercontent.com/619186/44122216-3ceb3d08-9ff9-11e8-9600-6b8c743879a9.png)

`doczrc.js`
```js
module.exports = {
  themeConfig: {
    colors: {
      primary: 'black',
    },
  },
  typescript: true,
}
```

`docz package.json`
```
{
  "name": "docz",
  "version": "0.0.1",
  "scripts": {
    "start": "docz dev",
    "build": "docz build"
  },
  "dependencies": {
    "shared": "0.0.1"
  },
  "devDependencies": {
    "docz": "^0.10.2"
  }
}
```

`docz/src/index.mdx`
```mdx
---
name: Hello world
---

import Button from 'shared/src/components/common/Button.tsx'

# Hello world

<Button>Click</Button>
```

**Comment by michaelgenesini** [comment]
Similar issue for me running `docz dev` from inside a workspace.
The problem seems to be babel related in build step.
Here my error:
```
...
[./.docz/app/index.jsx] 1.8 KiB {app} [built] [failed] [1 error]
```
```
ERROR in ./.docz/app/index.jsx
Module build failed (from /my-project/node_modules/happypack/loader.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /my-project/node_modules/babel-preset-react-app/index.js
```
If you guys have any hint I can try to fix it.
Thanks

**Comment by brunolemos** [comment]
> @nicholasess: It isn't error from docz and yes for the yarn workspace.

No, Docz needs to prepare the webpack config for this, supporting multiple project roots. I don't know details, but here's an example of a PR: https://github.com/facebook/create-react-app/pull/3741

**Comment by pedronauck** [comment]
For sure @brunolemos I agree with you that is related to docz instead of yarn. But, is not a "problem", is an architecture decision. It's not a good practice import from other packages in a monorepo without transpiling and since they will be in the `node_modules` they won't be transpiled. What you can do in this case is change the loader do transpile from a specific `node_modules` since we're [ignoring all `node_modules`](https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/bundlers/webpack/loaders.ts#L69) folder to be transpiled.

About `create-react-app` I saw this week on twitter that they're dropping support for monorepo. So, I don't think that change the entire structure to support monorepo can be a good choice.

**Comment by aarshaw** [comment]
Anyone have a good workaround for this?

**Comment by pedronauck** [comment]
See how https://github.com/smooth-code/smooth-ui work @aarshaw, they're using docz in a monorepo!

**Comment by mattietea** [comment]
Anybody having this issue when upgrading to v1?

If I have a component inside of `packages/docs` it works fine. The only issue is when I try to import a component from another package. 

```
/packages
    /docs
        - docsrc.js
        - index.mdx
    /ui (@hello/ui)
        - index.tsx
```

```js
// packages/docs/doczrc.js

import path from "path";

export default {
  title: "@hello/ui",
  codeSandbox: false,
  typescript: true,
  modifyBundlerConfig: config => {
    config.resolve.alias = Object.assign({}, config.resolve.alias, {
      "@hello/ui": path.resolve(__dirname, "..", "ui")
    });
    return config;
  }
}
```

```js
// packages/ui/index.tsx

import React from 'react';

export default props => <div {...props} />;
```

```jsx
// packages/docs/index.mdx

---
name: Getting Started
route: /
---

import MyComponent from "@hello/ui";

<MyComponent>Hello</MyComponent>
```
