### ISSUE TITLE
Error on launching npm run docz:dev

### ISSUE THREAD

**Issue by thedaviddias** [pedronauck/docz#230]
## Bug Report

**Describe the bug**

I took the basic example located on the repository, installed all dependencies but are unable to launch DocZ and have an error message.

**Screenshot**

![error-docz](https://user-images.githubusercontent.com/237229/44155052-40c96aae-a07a-11e8-98cb-c4a08691aa68.jpg)

**Environment**

* OS: OSX 10.13.6
* Node/npm version: Node 8.11.3 / npm 5.6.0

**Comment by pedronauck** [comment]
Hey @thedaviddias, can you show your `package.json`?

**Comment by pedronauck** [comment]
Fixed on [v0.10.3](https://github.com/pedronauck/docz/releases/tag/v0.10.3)
