### ISSUE TITLE
webpack-chain licensing issues

### ISSUE THREAD

**Issue by mmmeff** [pedronauck/docz#231]
Hey all,

My company is looking to use docz as the foundation of our new component library documentation site, but we're unable to use it due to the software license set on one of docz-core's dependencies: [webpack-chain is under MPL 2.](https://github.com/mozilla-neutrino/webpack-chain/blob/master/LICENSE) Is there any chance that docz would accept a PR to replace webpack-chain with something else (either an MIT licensed package or something self-built) for managing webpack configs?

Thanks!

**Comment by nicholasess** [comment]
@pedronauck look for this

**Comment by pedronauck** [comment]
To be honest I really like `webpack-chain` and what it can do in terms to write a better webpack configuration. So, let me understand how this can be bad for you?

**Comment by mmmeff** [comment]
@pedronauck I completely agree - `webpack-chain` looks to be an incredibly useful package and you were wise to include it in `docz`. The problem is the licensing is somewhat restrictive because Mozilla's org doesn't vend MIT licensed packages - they vend MPL2. This means that my organization (IMDb@Amazon) is unable to clear usage with legal/infosec. 

This is a go vs no-go issue for my team and we'd love to use this amazing project and help iterate on it.  I recognize the fact that the solution is more than likely a lot of work and reinvention of the wheel, but I'm more than willing to take it on so long as we get your blessing that the PR would be considered.

**Comment by pedronauck** [comment]
Hi @mmmeff, sorry the too late response, but just to point you, I'm working to replace webpack-chain in order to keep a more cleaning MIT toolset on docz, the same thing I'll apply to Lerna ✌️
