### ISSUE TITLE
can we use this with angular?

### ISSUE THREAD

**Issue by stewwan** [pedronauck/docz#235]
## Question
this project looks really amazing, I tried to search but cant understand. Does this project work just for react? how hard would it be to implement an angular version?

**Comment by emersonlaurentino** [comment]
Hey, @stewwan;

The integration with Angular is [planned](http://feedback.docz.site/roadmap/p/integration-with-angular). I suggest you follow the [roadmap](http://feedback.docz.site/).

**Comment by stewwan** [comment]
Thanks. Cant wait for the angular version
