### ISSUE TITLE
Postcss plugin doesn't load postcss.config.js

### ISSUE THREAD

**Issue by mzedeler** [pedronauck/docz#238]
## The `css` plugin for docz seems to ignore all `postcss.config.js` files.

To reproduce:

 * Check out this: https://github.com/mzedeler/docz/commit/33d9e2d596c3b75e40f235d0cea980970c82017f
 * Run `npm install`
 * Run `npm run dev`
 * Open the docz page

**Expected behavior**
 * Inspect the first alert example (blueish background saying `Some message`).
 * The background color should be set to `#5352ED` , not `var(--info)`.

**Environment**

* OS: Ubuntu 18
* Node/npm version: v9.11.2/5.6.0

**Comment by mzedeler** [comment]
I've fixed this by loading the postcss.config.js file and inject it as configuration in doczrc.js.

**Comment by nicholasess** [comment]
@mzedeler please, give me a example of code?

**Comment by mzedeler** [comment]
examples/basic isn't working.On Aug 23, 2018 17:37, Nicholas Eduardo <notifications@github.com> wrote:@mzedeler please, give me a example of code?

**Comment by nicholasess** [comment]
@mzedeler thanks man!
