### ISSUE TITLE
Missing dependency: webpack-hot-client

### ISSUE THREAD

**Issue by danburzo** [pedronauck/docz#24]
## Bug Report

With docz 0.2.3, running `docz dev` fails with the following error:

<img width="652" alt="screen shot 2018-06-13 at 11 57 20" src="https://user-images.githubusercontent.com/205375/41340902-16e73158-6f01-11e8-8444-1190e80e47a9.png">

It can be fixed by installing `webpack-hot-client`, but it should probably be an explicit dependency for the package.

**Comment by pedronauck** [comment]
Sure, thanks for the info @danburzo :pray:

**Comment by pedronauck** [comment]
Close in favor of [release v0.2.4](https://github.com/pedronauck/docz/releases/tag/v0.2.4)

**Comment by mdugue** [comment]
still happening with _0.2.6_
