### ISSUE TITLE
blockquote no support styles

### ISSUE THREAD

**Issue by amily4555** [pedronauck/docz#246]
'use > ' product 'blockquote' 

no support styles

**Comment by nicholasess** [comment]
@amily4555 I don`t understand your question

**Comment by franklinjavier** [comment]
I think he is talking about this 

> blockquote example

**Comment by amily4555** [comment]
@franklinjavier  yes， thank u

**Comment by wldcordeiro** [comment]
Like I said, if you insert a block quote currently, there are styles applied (an indentation from what I can tell) but nothing like the Github grey left border and dimmed text.

**Comment by pedronauck** [comment]
Fixed and will be released in the next version monday ✌️

**Comment by amily4555** [comment]
style error;

![image](https://user-images.githubusercontent.com/2802841/45079889-30c6ab00-b126-11e8-8852-7cc9176d7f01.png)

hope is 

![image](https://user-images.githubusercontent.com/2802841/45080029-87cc8000-b126-11e8-9901-b809c92b1bfb.png)
