### ISSUE TITLE
Looks like sidebar navigation was broken

### ISSUE THREAD

**Issue by lttb** [pedronauck/docz#247]
## Bug Report

There are no "bullet" links of documents' headers in the sidebar. It also looks like that the bug from https://github.com/pedronauck/docz/issues/136 is reproduced (submenu is closed after the refreshing).

So it works well in v0.8.0:

![image](https://user-images.githubusercontent.com/11135392/44512093-25a16300-a6c2-11e8-9edf-9c1dd890ca70.png)

But after v0.9.0 it does not work:

![image](https://user-images.githubusercontent.com/11135392/44512149-4cf83000-a6c2-11e8-929d-1cbd28b8c639.png)

Reproduced on several personal projects and `docz/examples/basic`.

**To Reproduce**

Header links:
1. Open an application page with headers like `## Header Name`
2. There is no link to the header in the sidebar

Closed submenu after refreshing:
1. Open an application page, go to submenu page
2. Refresh the page
3. Sidebar submenu still closed

**Expected behavior**

I'm expected to have header links in the sidebar and opened submenu after refreshing.

**Environment**

* OS: OSX 10.13.6, all browsers
* Node 8.10.0/npm 6.4.0]

**Comment by nicholasess** [comment]
@lttb please, remove path .docz and rerun the docz dev

**Comment by lttb** [comment]
Hi @nicholasess! I've tried to remove `.docz` several times, I've also tried to refresh the `node_modules` (even with forced cleaned cache) but had no success.

But I've found, that with `yarn` it's okay :) with `npm 6.4.0` it does not work.
Maybe there are some troubles with the registry cache, maybe there are some problems with dependencies for `npm` (because you use just the `yarn` lock file only).

Anyway, thank you for the help!

**Comment by nicholasess** [comment]
@lttb really? Thanks a lot for the your comment.

**Comment by loganfromlogan** [comment]
@nicholasess I'm not sure what I have to do with this thread. Are you referring to #204? If so, I did remove the `.docz` directory and ran `docz dev` with yarn. It didn't make a difference for me. The window scroll event still doesn't fire. Also, any reason why you specifically say to use yarn? NPM + docz have issues?

**Comment by nicholasess** [comment]
@loganfromlogan no, your project has docz and your website has the same problem with the issue

**Comment by nicholasess** [comment]
@loganfromlogan and I want to find  in the cases If is necessary use to yarn and not npm, just it.

I’m sorry if you did confused 😕
