### ISSUE TITLE
Generated docs and docz.site seems to be broken in IE11

### ISSUE THREAD

**Issue by mzedeler** [pedronauck/docz#249]
## Bug Report

If I navigate to http://docz.site/ using IE11, the screen is just blank. The same applies to any generated docs, whether in dev mode or on the built docs.

**To Reproduce**

1. Go to http://docz.site/ with IE11

Expected: the docz site
Actual: blank screen and an error in the console complaining about an unexpected closing body tag. A little later, a syntax error is encountered in a JavaScript file.

I have reproduced this error with the example provided in `examples/basic`.

**Comment by mzedeler** [comment]
@pedronauck: I can help fix this bug if you can point me in the direction of where it is probably introduced. This whole monorepo/typescript setup is somewhat confusing.

**Comment by mzedeler** [comment]
I did some digging and believe the bug is somewhere in the transpilation setup here: https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/bundlers/webpack/loaders.ts

**Comment by imeldaloei** [comment]
any luck on this one? 😄we need our guide site to works in IE11 since a good number of our end users use that browser!

**Comment by ahgharian** [comment]
We have the same issue. Would be more than happy to help if there are some pointers as @mzedeler mentioned.

**Comment by mpivaa** [comment]
Hi @mzedeler, can you close properly the "root" `div` in the file below, delete your `.docz` directory and try again?

https://github.com/pedronauck/docz/blob/master/packages/docz-core/templates/index.tpl.html

**Comment by omniverse** [comment]
Could you add `@babel/plugin-transform-template-literals` to the babel config? I see at least two webpack bundles that contain templates. I tried to build the project myself but ran into missing dependencies and one typescript error that I didn't understand.

**Comment by leandroferreira** [comment]
Created an issue on `webpack-serve-overlay` to make sure the vendor bundle is compatible with ES5: https://github.com/G-Rath/webpack-serve-overlay/issues/10

I don't think this project should be transpiling vendor dependencies, but please correct me if I'm wrong and I can start working on a fix for that instead.

**Comment by ncknuna** [comment]
Any updates on this? This would probably keep us from using docz as we need to do QA for IE and would like to do it via our component lib documentation

**Comment by leandroferreira** [comment]
After looking into this, I believe it would be better to move away from `webpack-serve`, since it's deprecated, and enable its [built-in overlay](https://webpack.js.org/configuration/dev-server/#devserver-overlay) instead of using `webpack-serve-overlay`.

**Comment by leandroferreira** [comment]
See https://github.com/pedronauck/docz/issues/456

**Comment by pcast01** [comment]
Is this still being looked into?

**Comment by ebaer** [comment]
Looks like it has been a while since the last post on this.
Has anyone been successful in getting this to transpile to ES5, so it will work on IE11?
If so, could you please post some guidance on how you solved it here?
Thanks
ewb

**Comment by andrew-t-james** [comment]
Is this still issues still being pursed? Any pointers on how to get this to run for IE11?

**Comment by davixyz** [comment]
Yeap, we are also facing this issue. Any pointers?

**Comment by pedronauck** [comment]
Sorry guys, but I think that isn't our focus to support IE11 😕

**Comment by smathson** [comment]
@pedronauck Fair enough, thanks for the heads up. Would you accept a PR that adds a supported browsers section to the readme in that case? Which browsers are currently considered supported? Thanks!

**Comment by imeldaloei** [comment]
@smathson i think listing supported browsers is a great idea! we ended up using storybook because the components we built have to work in IE11 and documentation site is a cheap and easy way to test the components. otherwise we have to spin up a separate react site just for testing IE11

**Comment by pedronauck** [comment]
Yeah, will be awesome @smathson 🙏

**Comment by smathson** [comment]
@pedronauck Happy to put together a PR if you tell me which browsers you want to support for this project. Evergreen only (Firefox/Chrome/Edge)? What about mobile browsers?

**Comment by ncknuna** [comment]
@pedronauck While it's totally understandable to not officially support IE11, would you accept PRs that would make IE11 work with the understanding that it may break in any future releases, as long as those PRs don't degrade performance for supported browsers?

**Comment by davixyz** [comment]
Yes! unfortunately IE11 is still around 2.7% of worldwide traffic and a lot of big companies will still support this browser. It would be awesome if we could have Docz run in IE11 so we can test things on this browser as well.

Browser Stats
https://www.w3counter.com/globalstats.php

**Comment by rupification** [comment]
+1 to this. from IE11 console it seems like its an es5 transpiling issue. using `const` and arrows `=>` functions

**Comment by leahjlou** [comment]
Has anyone found a workaround for this? I've tried adding a `onCreateBabelConfig` to `gatsby-config.json`; I've also tried [`gatsby-plugin-compile-es6-packages`](https://github.com/robwalkerco/gatsby-plugin-compile-es6-packages). I couldn't get either to work.

If there are no workarounds, I may look into trying to contribute a PR if the maintainers would be open to it.

**Comment by rakannimer** [comment]
Hey all,

A PR would be very welcome ! 

If you'd like to give it a shot and have questions or need help please feel free to join [our slack channel](https://join.slack.com/t/docz-workspace/shared_invite/enQtNzc4ODc2ODA3NzUxLWI0ZmYwY2NhNjhkNDFjN2UzYzlmMDcwZjQyZGY4MWQ1NmQwZDVlZDE4MmE3N2I4MWRjZTAxZjY4ODk4NGMzZjg) 👍

**Comment by mzedeler** [comment]
As reporter, I'm just happy to see someone wanting to contribute 🙂

**Comment by leahjlou** [comment]
I figured out a workaround for this so my site runs in IE. It's not completely ideal, but good enough for my use case.

**Step 1**: I installed [gatsby-plugin-compile-es6-packages](https://github.com/robwalkerco/gatsby-plugin-compile-es6-packages) and configured it with this `gatsby-config.js` at the root of my project:

```
// gatsby-config.js
module.exports = {
  plugins: [
    resolve: `gatsby-plugin-compile-es6-packages`,
    options: {
      modules: [
        `copy-text-to-clipboard`,
        `regexpu-core`,
        `unicode-match-property-ecmascript`,
        `unicode-match-property-value-ecmascript`,
        `ulid`
      ]
    }
  ]
}
```

You'll need to add any modules that are using unsupported syntax to the `modules` array (this may be dependent on your project). It took some whack-a-mole to figure out exactly which modules need transformed, and it'll take some maintenance if new deps are added.

**Step 2**: I added a polyfill for `HTMLElement.scrollTo`. I used Gatsby's [browser API's onClientEntry](https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry) for this. I added a `gatsby-browser.js` file to the root of my project with this contents:

```
// gatsby-browser.js
// Called when the Gatsby browser runtime first starts.
exports.onClientEntry = () => {
  if (!HTMLElement.prototype.scrollTo) {
    HTMLElement.prototype.scrollTo = function (left, top) {
      this.scrollTop = top
      this.scrollLeft = left
    }
  }
}
```

I was trying to cover all my bases with just the `gatsby-config.js`, but the `scrollTo` was one where I was struggling to cover all my bases, I thought an explicit polyfill would be fine.

It's a bit hacky, and there are probably ways to improve this approach, but for now my docs site at least runs in IE11. The layout isn't quite right because of CSS grid support. If I really wanted to, I think I'd be able to add some [custom theme files](https://www.docz.site/docs/creating-your-themes) to fix the layout.

**Comment by HiltonGiesenow** [comment]
@leahjlou I'm totally new to Docz but IE is really important for my site. Do you know if this fix would work if it's a completely Docz site (i.e. not added to an existing Gatsby site)? I want this specific site only for docs.

**Comment by rakannimer** [comment]
Hey @HiltonGiesenow 

I'm not sure about the fix in particular but anything that works with docz as a gatsby theme in an existing site should work the same with docz as a stand-alone site.

**Comment by HiltonGiesenow** [comment]
Ok, it's probably just my limited knowledge of the tools to date. If I start with the standalone site, I don't seem able to edit the gatsby-config.js file - it get's overwritten
