### ISSUE TITLE
Allow deploying on GitHub pages

### ISSUE THREAD

**Issue by danburzo** [pedronauck/docz#25]
## Feature Request

I'm not sure if it's something for the default theme or the core package, but:

**Is your feature request related to a problem? Please describe.**

It's currently impossible (I think) to deploy Docz to GitHub Pages, since the latter has now way of working with routes. 

**Describe the solution you'd like**

Either allow using hash routes, such as: https://username.github.io/project/#section (The way [Storybook](https://storybook.js.org/) does it)

or, ideally, generate individual pages for all the sections with SSR.

**Describe alternatives you've considered**

I'm currently investigating whether there's something one can do about it in the current Docz version.

**Teachability, Documentation, Adoption, Migration Strategy**

The hash-route will (probably) manifest itself in a config option that is opt-in. Not sure yet about SSR.

**Comment by danburzo** [comment]
Okay, for the hash routing solution, I guess a possible fix is to allow using either BrowserRouter or HashRouter here, depending on a configuration option (_useHashRouter_?):
https://github.com/pedronauck/docz/blob/9284692fdc12f8be5d2bcccf3fcb141b142660d2/packages/docz/src/theme.tsx#L80

**Comment by pedronauck** [comment]
@danburzo you can deploy the site on github pages by changing the `base` property on project configuration: https://www.docz.site/documentation/project-configuration#basic-config

Did you try this?

**Comment by pedronauck** [comment]
Sure, now I got the message! Of course, I think that can be a good solution change the router type, but I think that is better use some property on configuration for that, like:

```js
//doczrc.js
export default {
  hashRouter: true
}
```

Because is kinda dangerous pass a `Router` component to components!

**Comment by danburzo** [comment]
Sounds good! I'd make a PR, but I haven't used TypeScript before and I'm a bit out of my league here as to how things work :)
