### ISSUE TITLE
Support For Versioning

### ISSUE THREAD

**Issue by inje** [pedronauck/docz#250]
# Feature Request

## 📃 Description
This is a feature request for Docz to support multiple versions of the same library. Commonly projects have **multiple version that need support**, especially when there are non-backwards compatible changes.

## 💁‍♀️ Example
An example of this is Lodash's documentation here:

### Lodash
<img width="312" alt="screen shot 2018-08-23 at 3 07 53 pm" src="https://user-images.githubusercontent.com/4149515/44554612-85aa0080-a6e6-11e8-890c-ca925e7e5659.png">

<img width="301" alt="screen shot 2018-08-23 at 3 08 00 pm" src="https://user-images.githubusercontent.com/4149515/44554610-817de300-a6e6-11e8-93f0-aaa6075c421f.png">

**Comment by pedronauck** [comment]
Hey dude, to follow the pattern, can you open your feature requests on [our roadmap](https://feedback.docz.site)?

**Comment by inje** [comment]
Definitely. [Just opened the feature request on the roadmap](http://feedback.docz.site/roadmap/p/support-for-versioning).

**Comment by Stevemoretz** [comment]
@nicholasess  So this is marked as complete but how to use it? I need this feature but the docs don't even mention it.
