### ISSUE TITLE
JSON error running `docz dev`

### ISSUE THREAD

**Issue by Sawtaytoes** [pedronauck/docz#256]
## Question
Getting a JSON error when running `docz dev`

**Description**
```js
λ yarn docz dev
yarn run v1.9.2
$ [PROJECT]\node_modules\.bin\docz dev
(node:4768) Warning: N-API is an experimental feature and could change at any time.
There was an error loading your config:
SyntaxError: Unexpected token / in JSON at position 46
    at JSON.parse (<anonymous>)
    at loadFile ([PROJECT]\node_modules\load-cfg\dist\index.js:1:601)
    at Object.load ([PROJECT]\node_modules\load-cfg\dist\index.js:1:886)
    at getBabelConfig ([PROJECT]\node_modules\docz-core\dist\index.js:1:12903)
    at Bundler.getConfig ([PROJECT]\node_modules\docz-core\dist\index.js:1:13294)
    at Object.dev ([PROJECT]\node_modules\docz-core\dist\index.js:1:24997)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I installed `docz`: `yarn add docz`, then ran `yarn docz dev` and got this error. Running build does the same.

**Comment by nicholasess** [comment]
@Sawtaytoes Do your package.json is correct?

**Comment by Sawtaytoes** [comment]
What do you mean? My package.json runs. I don't get any `yarn` errors or anything.

**Comment by oieduardorabelo** [comment]
@Sawtaytoes, dockz is trying to load your `package.json` and seems your json structure is wrong.

"There was an error loading your config:" is from `JSON.parse(fs.readFileSync(filepath, 'utf-8'))`:

https://github.com/pedronauck/docz/blob/master/packages/load-cfg/src/index.ts#L23-L35


@nicholasess @pedronauck , perhaps, hiding the stack trace for production in the `catch` above and display a better message? `Your file: ${filepath} could not be loaded.` or something.

for local/development or DEBUG flag, we could throw the stack trace

**Comment by pedronauck** [comment]
Fixed and will be released in the next version monday :v:

**Comment by pedronauck** [comment]
For sure @oieduardorabelo, will be very good if you help us 🙏 I know that `fs-extra` has `throw` option in the `readJson` method, but I prefer to keep the throw because is a good thing see a throw when you make some error on `doczrc`, but to load `babelrc` really can be good omit this...

**Comment by Sawtaytoes** [comment]
This is my `.babelrc`:

```js
{
  "plugins": [
    "add-react-displayname", // Has to be the first plugin for LogRocket
    "extract-hoc/babel", // Has to be before react-hot-loader/babel
    "react-hot-loader/babel",
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-runtime",
  ],
  "presets": [
    [
      "env", {
        "modules": false,
      }
    ],
    "react",
  ],
}
```

I think Babel is more lenient on the JSON you give it. This is the adjusted JSON to get it working:

```js
{
  "plugins": [
    "add-react-displayname",
    "extract-hoc/babel",
    "react-hot-loader/babel",
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-runtime"
  ],
  "presets": [
    [
      "env", {
        "modules": false
      }
    ],
    "react"
  ]
}
```

**Comment by Sawtaytoes** [comment]
I'm having other issues though, but this one's been resolved. Version 0.11.0 pointed me in the correct direction with the updated error message.
