### ISSUE TITLE
Add _redirects section to documentation

### ISSUE THREAD

**Issue by gizmodesbois** [pedronauck/docz#257]
## Feature / Enhancement

Inside the documentation, u are explaining how to [deploy the application on Netlify](https://www.docz.site/introduction/deploying-your-docs#deploying).

It would be great to provide some information about the `_redirects` file that can be provided to avoid 404 page when refreshing inside a page of the doc. [Redirect history push](https://www.netlify.com/docs/redirects/#history-pushstate-and-single-page-apps).

For now, I do a copy at the end of my build but it can be a parameters inside the project configuration (or something else)?

Yes, I would love to do help you implement it if needed.

Thank you.

**Comment by nicholasess** [comment]
@gizmodesbois could you please create a item in [roadmap](https://docz.canny.io/roadmap)? Thanks!
