### ISSUE TITLE
Styles using less named with BEM Naming Convention

### ISSUE THREAD

**Issue by itReverie** [pedronauck/docz#258]
I am not sure if this is an issue of a feature request but it seems that if I named my styles with the  BEM Naming Convention, the styles are not applied. 
![screen shot 2018-08-27 at 7 35 42 pm](https://user-images.githubusercontent.com/4857771/44692330-72719a80-aa30-11e8-8d24-1ee4aaca6cde.png)

**Comment by renatorib** [comment]
This is a issue related to CSS Modules / Less, not docz itself.  
Take a look: https://github.com/css-modules/css-modules/issues/91
