### ISSUE TITLE
Code block 1 redundancy

### ISSUE THREAD

**Issue by Frangte** [pedronauck/docz#260]
## Bug Report

**Describe the bug**

*Code block 1 redundancy*

**Expected behavior**

*Number of lines fit*

**Environment**

* OS: Ubuntu 18
* Node/npm version: Node 8.11.0/npm 5.6.0

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/19859575/44715993-5f6bd280-aae3-11e8-94f1-d34b1abd4def.png)
![image](https://user-images.githubusercontent.com/19859575/44716010-6b579480-aae3-11e8-9bf2-5b8dd6b477cb.png)

**Comment by nicholasess** [comment]
@Frangte I don't understand your question

**Comment by Frangte** [comment]
=))). in `Additional context/Screenshots` the first image, my expect of line number in code block is 6, but it end at 7.

**Comment by Frangte** [comment]
@pedronauck thank for reply and how to fix that.

**Comment by pedronauck** [comment]
Fixed and will be released in the next version monday ✌️
