### ISSUE TITLE
Is it possible to render react class inside the `Playground` component?

### ISSUE THREAD

**Issue by pradel** [pedronauck/docz#261]
## Question
First thank you for this awesome project 🚀 

**Description**
I was wondering, can we render react class inside the `Playground` component?
For example like material ui is doing here https://material-ui.com/demos/dialogs/#simple-dialogs (you need to click on the "Show the source" button).
Thanks!

**Comment by nicholasess** [comment]
@pradel You can write out Playground like a text

**Comment by pradel** [comment]
Maybe more explanation, it's more how to do to write components with state, for example a modal with an open / close state, eg:

```
<Playground>
  {() => {
    class Test extends React.Component {
		state = { ... }
		// Class with a managed state
	}
    return <Test />
  }}
</Playground>
```

**Comment by nicholasess** [comment]
@pradel could please you upgrade docz? We sent a new release that what you want to do, work!

**Comment by sag1v** [comment]
@nicholasess can you post an example? i tried to do it with the latest version but i get:  

>Cannot read property 'toString' of undefined
Stack trace
in Po (created by BasePlayground)
in BasePlayground
in Component (at slideNext.mdx:17)
in div (created by MDXTag)
in MDXTag
in Component (at slideNext.mdx:10)
in Component (created by o)
in o (created by AsyncComponent)
in AsyncComponent (created by t)
in t
in b (created by s)
in s
in Component (created by AsyncRoute)
in div (created by Styled(div))
in Styled(div) (created by ConsumerMemoization)
in div (created by Styled(div))
in Styled(div) (created by ConsumerMemoization)
in div (created by Styled(div))
in Styled(div) (created by Xe)
in Xe (created by ConsumerMemoization)
in ConsumerMemoization
in CopyOnWriteConsumer
in ThemeConfig (created by ht)
in ht (created by AsyncRoute)
in AsyncRoute (created by t)
in t (created by ConsumerMemoization)
in t (created by ConsumerMemoization)
in ConsumerMemoization
in CopyOnWriteConsumer
in MDXProvider (created by DocPreview)
in DocPreview (created by ConsumerMemoization)
in ThemeProvider (created by ConsumerMemoization)
in ConsumerMemoization
in CopyOnWriteConsumer
in ThemeConfig (created by Component)
in Component (created by DoczTheme)
in DefaultWrapper (created by DoczTheme)
in t (created by t)
in t (created by DoczTheme)
in DataServer (created by DoczTheme)
in CopyOnWriteStoreProvider (created by DoczTheme)
in ErrorBoundary (created by DoczTheme)
in DoczTheme (at root.jsx:9)
in Root (created by HotExportedRoot)
in AppContainer (created by HotExportedRoot)
in HotExportedRoot (at index.jsx:15)

**Comment by three60five** [comment]
I think this should have an example in the docz.

**Comment by jamsch** [comment]
The "toString" error is because you need to define `this.state` in your constructor.

**Comment by drcmda** [comment]
react-live can take regular classes and functions without wrap, is this possible in Playground somehow? It would be great to show examples unobstructed by boilerplate. Just a class with lifecycles would be great. I tried to do what @nicholasess said, writing it out as text, but i either don't get what that means, or it doesn't seem to work.

**Comment by danielbayerlein** [comment]
**Here is a working example:**

```javascript
import { Playground } from 'docz'
import Modal from './'

<Playground>
  {() => {
    class Example extends React.Component {
      constructor (props) {
        super(props)

        this.state = {
          showModal: false
        }
      }

      handleShowModal () {
        this.setState({ showModal: true })
      }

      handleCloseModal () {
        this.setState({ showModal: false })
      }

      render () {
        return (
          <React.Fragment>
            {this.state.showModal &&
              <Modal
                title='Title'
                onClose={() => this.handleCloseModal()}
              >
                <p>
                  Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
                  sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
                  At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
                  no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
                  consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
                  sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
                  no sea takimata sanctus est Lorem ipsum dolor sit amet.
                </p>
              </Modal>
            }
            <Button onClick={() => this.handleShowModal()}>Show Modal</Button>
          </React.Fragment>
        )
      }
	  }

    return <Example />
  }}
</Playground>
```

**Comment by pedronauck** [comment]
Fixed in the [v0.12.9](https://github.com/pedronauck/docz/releases/tag/v0.12.9).
Now is possible to render a class directly inside the playground:

```jsx
import { Playground } from 'docz'

<Playground>
  {class Counter extends React.Component {
    constructor() {
      super()
      this.state = { count: 0 }
    }

    componentDidMount() {
      this.interval = setInterval(() => {
        this.setState(state => ({ count: state.count + 1 }))
      }, 1000)
    }

    componentWillUnmount() {
      clearInterval(this.interval)
    }

    render() {
      return (
        <center>
          <h3>
            {this.state.count}
          </h3>
        </center>
      )
    }
  }}
</Playground>
```

**Comment by danielbayerlein** [comment]
@pedronauck Looks like it's no longer possible to render a class directly inside the playground with `docz v0.13.7`.

**Code**

```javascript
<Playground>
  {class Example extends React.Component {
    constructor (props) {
      super(props)

      this.state = { showModal: false }
    }

    handleShowModal () {
      this.setState({ showModal: true })
    }

    handleCloseModal () {
      this.setState({ showModal: false })
    }

    render () {
      return (
        <React.Fragment>
          {this.state.showModal &&
            <Modal
              title='Title'
              onClose={() => this.handleCloseModal()}
            >
              <p>
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
                sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
                At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
                no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
                consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
                sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
                no sea takimata sanctus est Lorem ipsum dolor sit amet.
              </p>
            </Modal>
          }
          <Button onClick={() => this.handleShowModal()}>Show Modal</Button>
        </React.Fragment>
      )
    }
  }}
</Playground>
```

**Error**

```
SyntaxError: Unexpected token (3:21) 1 : (<React.Fragment> 2 : class Example extends React.Component { 3 : constructor(props) { ^
```

**Comment by sunkeysun** [comment]
> Fixed in the [v0.12.9](https://github.com/pedronauck/docz/releases/tag/v0.12.9).
> Now is possible to render a class directly inside the playground:
> 
> ```js-jsx
> import { Playground } from 'docz'
> 
> <Playground>
>   {class Counter extends React.Component {
>     constructor() {
>       super()
>       this.state = { count: 0 }
>     }
> 
>     componentDidMount() {
>       this.interval = setInterval(() => {
>         this.setState(state => ({ count: state.count + 1 }))
>       }, 1000)
>     }
> 
>     componentWillUnmount() {
>       clearInterval(this.interval)
>     }
> 
>     render() {
>       return (
>         <center>
>           <h3>
>             {this.state.count}
>           </h3>
>         </center>
>       )
>     }
>   }}
> </Playground>
> ```

It is not work for v0.13.7.
Error
```
SyntaxError: Unexpected token (3:16) 1 : (<React.Fragment> 2 : class DemoModal extends React.Component { 3 : constructor() { ^
```

**Comment by sw-yx** [comment]
agree. please see #567 as many people have reported this issue

**Comment by HadeAs** [comment]
can someone fix this issue?
