### ISSUE TITLE
Serving static file from node_modules

### ISSUE THREAD

**Issue by donifer** [pedronauck/docz#265]
## Question

**Description**
Hi, I'm trying to use a `css` file in a `link` tag directly from the `node_modules` directory but I haven't figured out a way of doing it yet. Is this possible?

**Comment by nicholasess** [comment]
@donifer the error has recorrency in your project with out docz?

**Comment by donifer** [comment]
It's not project-related, its just a question on how to serve a file directly from `node_modules`

**Comment by pedronauck** [comment]
What you can do in this case is add `docz-plugin-css` and import it from `node_modules`:

```
import 'my-modules/index.css`
```
