### ISSUE TITLE
Using `base` and `hashRouter` produces weird URLs

### ISSUE THREAD

**Issue by wldcordeiro** [pedronauck/docz#268]
## Bug Report

When you set a different `base` and use the `hashRouter` you get weird duplication of URLs.

For example you set `base` to `/foo` and then go to your deployed doc site and click around

you'll end up with something like `/foo/#/foo/<sub>/<sub>/`

**Expected behavior**

The base isn't appended on every URL on top of itself

**Comment by Yurickh** [comment]
[As the documentation suggest](https://www.docz.site/documentation/project-configuration#basic-config), you should always start and end your `base` with a slash.

But I wonder if this would be a nice feature for docz. What do you think @pedronauck?

I could work on either ensuring that `base` always have the slashes by either warning or inserting them when due.

**Comment by wldcordeiro** [comment]
@Yurickh the problem with that is that `base` is used by `react-router` which in its documentation says to not have an ending slash, however I saw the same problem one way or the other.

https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string

> A properly formatted basename should have a leading slash, but no trailing slash.

**Comment by exah** [comment]
Problem is that `base` is used for 

https://github.com/pedronauck/docz/blob/dee78a71fa6c9fc0da893be413034798f10f756c/packages/docz-core/src/bundlers/webpack/config.ts#L49

https://github.com/pedronauck/docz/blob/dee78a71fa6c9fc0da893be413034798f10f756c/packages/docz-core/src/bundlers/webpack/config.ts#L87

https://github.com/pedronauck/docz/blob/dee78a71fa6c9fc0da893be413034798f10f756c/packages/docz-core/src/bundlers/webpack/config.ts#L238

and 

https://github.com/pedronauck/docz/blob/7a84638aa140888b0102885372bcacb9c797c395/packages/docz/src/theme.tsx#L50

---

And this should be a 2 different options (like `base` and `routerBase`).

Demo: http://johngrish.in/components/#/components/box

**Comment by wldcordeiro** [comment]
@exah thanks for digging in, looks like it's what I was expecting! For me I would want to leave this `routerBase` as is `/` and the `base` for webpack I'd want to change for something like github/gitlab pages.

**Comment by pedronauck** [comment]
For sure, thanks guy! The basename on router, in this case, is used to bind `Link` component, but I think that isn't necessary since webpack public path is setted, I'll remove `basename` from router and release in the next release 🙏
