### ISSUE TITLE
Adding more info after compilation finishes

### ISSUE THREAD

**Issue by larsbs** [pedronauck/docz#27]
## Feature Request

**Is your feature request related to a problem? Please describe.**
For newcomers to the project, after compilation finishes nothing is displayed so it can be confusing knowing which port to use.

**Describe the solution you'd like**
Maybe considering adding something like https://github.com/Drawbotics/initial-webpack-message

<img width="969" alt="screen shot 2018-06-13 at 12 30 35" src="https://user-images.githubusercontent.com/1436588/41346032-99d460fa-6f05-11e8-8490-5fbfaa467f49.png">

**Comment by pedronauck** [comment]
Close in favor of [release v0.2.4](https://github.com/pedronauck/docz/releases/tag/v0.2.4)
