### ISSUE TITLE
No way to make it work with webpack 3.9.0 ?

### ISSUE THREAD

**Issue by ghostCoder** [pedronauck/docz#275]
Hi, i am using webpack 3.9.0 and babel 6 in my project, and wanted to integrate docz.

I found the plugin to make it work with babel 6 (https://github.com/pedronauck/docz/tree/master/packages/docz-plugin-babel6), but is there anyway to make it work with webpack 3.9.0 or is webpack 4 a must for integrating docz?

**Comment by nicholasess** [comment]
@ghostCoder We don`t support webpack 3.*, you need to upgrade your webpack to use docz.
