### ISSUE TITLE
How can I import less or sass in Mdx from npm package?

### ISSUE THREAD

**Issue by jansesun** [pedronauck/docz#28]
##  How can I import less or sass in Mdx from npm package?
**Description**
I try to import less in Mdx from node_modules as below:
```
import 'style-mobile';
```

But it does not work in the document site

**Comment by Swapnull** [comment]
Hi, 
I think you need to supply a less loader. Have a look at https://github.com/pedronauck/docz/issues/6 and see if that helps - Looks like this should be put in the documentation somewhere.

**Comment by pedronauck** [comment]
That's a true @Swapnull, I think that create some plugins and put this information on docz.site in really necessary!

By now I'll close this issue in favor of #6
