### ISSUE TITLE
URL with anchor hash tag does not autoscroll upon first visit

### ISSUE THREAD

**Issue by justinkchen** [pedronauck/docz#282]
## Bug Report

**Describe the bug**
When you go to a url like https://www.docz.site/documentation/creating-themes#default-theme-configuration, it will not go to the `default-theme-configuration` section as intended. Instead it just starts at the top. 

**To Reproduce**

1. Go to 'https://www.docz.site/documentation/creating-themes#default-theme-configuration'
2. See the auto scroll not happen

**Expected behavior**
It should go to the appropriate section

**Comment by nicholasess** [comment]
@justinkchen we have a repository separated of docz package.

Can you create the issue in repository correct? https://github.com/pedronauck/docz-website

We accept PR to fixed the error.

Thanks

**Comment by sidewalksalsa** [comment]
@pedronauck @nicholasess - Do you have any initial thoughts on why this is happening? It seems that https://github.com/rafrex/react-router-hash-link supports it.

I also need this resolved for a project, so I am happy to help. Just wanted to see if you could point me in the right direction or if I should just dig.

**Comment by pedronauck** [comment]
Closed in the newest release.
