### ISSUE TITLE
css in js Support

### ISSUE THREAD

**Issue by jansesun** [pedronauck/docz#29]
## css in js Support

**Description**
Can you support css in js? It is very useful to customize components in document.

**Comment by pedronauck** [comment]
In fact, we're suing just css-in-js to create all projects that need css... You can see how we're doing that in the [source code of the theme](https://github.com/pedronauck/docz-website) that we build for docz.site and in the [docz-default-theme source code](https://github.com/doczjs/docz/tree/master/packages/docz-theme-default)!
