### ISSUE TITLE
Playground-local stylesheets

### ISSUE THREAD

**Issue by derekstavis** [pedronauck/docz#290]
Hey 👋

I'm migrating the docs from [`Vanilla Form`](https://github.com/derekstavis/react-vanilla-form), my form state/validation management library. Currently I'm using Styleguidist, so migrating to Docz is pretty easy as all documentation and examples are already in Markdown.

## Background

As the documentation examples are using plain HTML elements, I've used Styleguidist's [`require`](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#require) configuration option to apply [Milligram](milligram.io) styles for better-looking components in playground. This basically requires applies Milligram globally in the docs page.

For the Docz migration I followed the same idea, but using the CSS plugin to achieve it. I could make it work and all playground examples now have Milligram styles, but as a side-effect, Docz theme is completely screwed up, as Milligram uses global CSS.

## Playground Isolation

I like a lot that both Styleguidist and Docz render playgrounds inline (no funky iframes), even understanding that conflicts ranging from HTML IDs to CSS could happen. On the other hand, I've come to believe that having at least styles isolation inside playgrounds is an important thing, because not all libraries are using fancy CSS systems (emotion, styled, css-modules, ...), so their styles could interfere with Docz's own theme.

## Possible solution

Trying to avoid using `iframe`, it seems that Shadow DOM could be a thing here. By Shadow DOM-ing playground's preview and injecting style tags inside the playground we could get the desired styles isolation.

**EDIT:**: After some tinkering, I came with this component to Shadow DOM the example. The only downside is that it breaks HTML preview (for obvious reasons):

```jsx
import React from 'react'
import ShadowDOM from 'react-shadow'
import marx from 'marx-css/css/marx.css'

const Themed = ({children}) =>
  <ShadowDOM include={[marx]}><div>{children}</div></ShadowDOM>

export default Themed
```

I had to match `\.css$` and use `file-loader` in the pipeline to achieve the desired effect.

Even if this is already sufficient for me, having to repeat the theme wrapper every demo makes the demos clunky.

**Comment by pedronauck** [comment]
Hey @derekstavis you can use the new `htmlContext` that doesn't document yet on our docz 🙄But is very simple and should fix your problem:

```
export default {
  htmlContext: {
    head: {
      links: [{ rel: 'stylesheet', href: '/path/of/your/css' }]
    }
  }
}
```

You can see more info about `HtmlContext` here: https://github.com/pedronauck/docz/blob/master/packages/docz-core/src/commands/args.ts#L27-L40

**Comment by Dobby89** [comment]
@pedronauck Could you please expand on how this `htmlContext` is used?

**Comment by donifer** [comment]
@pedronauck I believe the issue he is mentioning is applying the css **only** to the previewer.

> I could make it work and all playground examples now have Milligram styles, but as a side-effect, Docz theme is completely screwed up, as Milligram uses global CSS.

So he is able to load the styles globally but it messes up the Docz theme itself. Is there a workaround for that?

**Comment by Emiliano-Bucci** [comment]
@donifer Hi, i'm also getting the same error (404) when trying to append a custom .css file. `htmlContext: {
    head: {
      links: [{ rel: "stylesheet", href: "./style.css" }]
    }
  }`

Maybe i'm putting the css file in the wrong place? I put it along with the doczrc.js file

**Comment by pedronauck** [comment]
> @pedronauck I believe the issue he is mentioning is applying the css **only** to the previewer.
> 
> > I could make it work and all playground examples now have Milligram styles, but as a side-effect, Docz theme is completely screwed up, as Milligram uses global CSS.
> 
> So he is able to load the styles globally but it messes up the Docz theme itself. Is there a workaround for that?

@donifer, what you can do is pass some class just to playground, but some css that just act in the playground isn't possible :confused:

**Comment by Emiliano-Bucci** [comment]
@pedronauck So even a global style.css isn't possible? Or at least, style the html? Maybe add some custom styles like fonts, colors, etc

**Comment by pedronauck** [comment]
You can put styles using `htmlContext`, but the public url need to be `.docz/public`. But I'm seeing that this is with a bug now, I'm fixing it and making a new release!

**Comment by Emiliano-Bucci** [comment]
Ok, thank you very much! :)

**Comment by Dobby89** [comment]
@pedronauck Do you have any objection to using iframes to load each Playground? I see this issue coming up quite often and iframes seem to be the way to go for similar component styleguide tools.

Without style isolation, there's no way to safely use Docz.

**Comment by pedronauck** [comment]
@Dobby89 I don't have any objections, to be honest, I really think is the best solution since with an iframe we can simulate viewport and be able to work more effectively with responsive queries. But, I tried to transform playground render using iframes, but I didn't get success. I'll try again on v1.

**Comment by giulianok** [comment]
You can do the following in case you don't want to commit `.docz` (since has tmp folders)

```
import fs from "fs";

export default {
  typescript: true,
  htmlContext: {
    head: {
      raw: `<style>${fs.readFileSync(
        process.cwd() + "/src/assets/demo.css"
      )}</style>`
    }
  }
};
```

**Comment by eazy-g** [comment]
@giulianok That's useful, thanks. Now I'm stuck by docz overriding the styles I inlined, since the styles added to 'htmlContext' become the first style tag in the document...any ideas?

Specifically, I'm attempting to define the font-family for the document, and docz is overriding it as Source Sans Pro in a later style tag
