### ISSUE TITLE
support some background prop for the <Playground> component

### ISSUE THREAD

**Issue by hilquias-kil** [pedronauck/docz#292]
When we have a component witch the color is white, we are not able to see it, because the background of the Playground is white.

So it would be nice if we had a prop in Playground component like <Playground bg="black">, that changes the background.

**Comment by pedronauck** [comment]
You can add a `style` or even a `className` property for `Playground`:

```
<Playground style={{ background: 'red' }}>
  <div>what you want</div>
</Playground>
```

**Comment by hilquias-kil** [comment]
Got it, thanks

**Comment by donifer** [comment]
I also have this question, passing `<Playground style={{ background: 'red' }}>` passes the style to the inner components but not the previewer wrapper. Is there a workaround for this?

**Comment by huchenme** [comment]
@pedronauck do not want to repeat it over and over again, is there anyway to create a custom `Playground` with `background` prop?
