### ISSUE TITLE
Page inoperable when selecting pages from side menu.

### ISSUE THREAD

**Issue by johnpittman** [pedronauck/docz#293]
## Bug Report

**Describe the bug**

Unable to use the page after selecting a component from the sidebar.

*A clear and concise description of what the bug is.*

Clicking a nav link renders the page but there is some kind of modal of it that keeps the page from scrolling. The only way to get rid of it is to click the same nav link of the sidebar again. Re-clicking the same sidebar link toggle the modal. I think this has to do with the sidebar.

```javascript
---
name: QuoteProgress
menu: components/interfaces
---

import { Playground, PropsTable } from 'docz';
import QuoteProgress from './index';

# QuoteProgress

## Properties

<PropsTable of={QuoteProgress} />

## Basic usage

<Playground>
  <QuoteProgress stages={[{
      name: 'Pick Consignee',
      key: 'instantQuote,',
      active: false,
    }, {
      name: 'Quote Info',
      key: 'containerInfo,',
      active: false,
    }, {
      name: 'Container Info',
      key: 'kio',
      active: false,
    }]} 
  />
</Playground>
```

![localhost_5555_](https://user-images.githubusercontent.com/6298219/45114572-f869a180-b112-11e8-9505-47546b4ad5eb.png)

**To Reproduce**

2. Click on a page from the sidebar menu multiple times to see the modal toggle

```shell
FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by paesvitor** [comment]
I got the same issue

**Comment by pedronauck** [comment]
Yes, this is fixed in the new version that will be released tonight or tomorrow, thanks guys 🙏
