### ISSUE TITLE
Sub-menu support

### ISSUE THREAD

**Issue by wldcordeiro** [pedronauck/docz#294]
It'd be great to be able to do deeper level with menus. I was thinking the syntax could be  something like this.

```
---
name: FooComponent
parent: Project 1
menu: Components
route: /project-1/components/foo-component
---
```

**Comment by pedronauck** [comment]
That's a really good point dude, we already have an issue on our roadmap that's about the menu order and I think that this can fit together with it, please give us your vote and idea there's and in a near future we can make this changes for you 🙏

**Comment by alexlee-dev** [comment]
Is there any update on this? I saw that it was put on the roadmap has been voted on, and it appears to be labeled as "planned". What stage in development is this at, and how can I help out?

I'm trying to create sub-menus, but not seeing a way to do it yet.

**Comment by alexlee-dev** [comment]
In case any one else finds this later, the good folks at Docz created a new feature to support this in the [v12.4 build](https://github.com/pedronauck/docz/releases/tag/v0.12.4).

**Comment by phaneendra** [comment]
Not sure on how to achieve 3 level sub menus
Adding the below still does not nest menu's Badge and Alert into Components

```
menu: [
    "Home",
    "Getting Started",
    {
      name: "Foundation",
      menu: ["Colors", "Global Styles", "Typography", "Content"]
    },
    {
      name: "Components",
      menu: [
        { name: "DataDisplay", menu: ["Badge"] },
        { name: "Feedback", menu: ["Alert"] },
        "Others"
      ]
    },
    "Utilities"
  ],
```

**Comment by pedronauck** [comment]
@phaneendra isn't possible to achieve this level of menu yet

**Comment by RyanPWalker** [comment]
Any update?
