### ISSUE TITLE
Extract metadata from an existing project

### ISSUE THREAD

**Issue by jmaicaaan** [pedronauck/docz#296]
## Question

**Description**

We have an existing project (React on Electron) built with https://github.com/chentsulin/electron-react-boilerplate/. 

In our case, we already have a stories set-up (https://github.com/storybooks/storybook) and I would like to use/test this library with our existing components.

My plan was to create a repo that is based only on documentation and extract the metadata of the components to our project. I don't like to copy and paste all the components from the `React + Electron` and move it to the "documentation repository" because it can cause a big space to copy and paste it. 

Is it possible to extract the metadata, then bundle it up, and use it for the "documentation repository"?

Thank you in advance.

PS:
We are using babel 6 as it is the babel supported by the boilerplate

**Comment by pedronauck** [comment]
What you can do is public your package as an npm package and consume it on the documentation. But since you're using Babel 6 you won't be able to use docz 😕In the new release v0.11.0 we're dropped support for older versions of babel...

**Comment by jmaicaaan** [comment]
We'll try to use babel 7! Thank you 👍
