### ISSUE TITLE
The css-bkwgfx div is puzzling, after I upgrade to 0.11.0

### ISSUE THREAD

**Issue by cryzzchen** [pedronauck/docz#297]
## Bug Report

The css-bkwgfx div will be rended every even times that clicking the  menu.

![image](https://user-images.githubusercontent.com/3948124/45134486-5bb80a00-b1cd-11e8-9b8a-4e1beef09bf2.png)

**Comment by pedronauck** [comment]
This is fixed in the new version that will be released tomorrow 🙏
