### ISSUE TITLE
Constantly getting missing dep on running on windows

### ISSUE THREAD

**Issue by pantharshit00** [pedronauck/docz#30]
## Bug Report

**Describe the bug**
If I make a MDX file I am getting this wierd missing dep error. I am using the typescript setup

**To Reproduce**
1. Install docz on windows
2. Make a MDX file and run docz

```shell
This dependency was not found:

* componentsButtonButton.mdx in ./.docz/app/imports.js

To install it, you can run: npm install --save componentsButtonButton.mdx
```
https://github.com/javascript-af/ui-lib
It is on the docz branch

**Expected behavior**

It should bootstrap the site and it should run 

**Enviroment**

* OS: Windows 10
* Node/npm version: Node 8.11.2

**Comment by marceloavf** [comment]
Related to #12

**Comment by pantharshit00** [comment]
Using bash on windows for noe. I guess PR #31 will close this issue

**Comment by pantharshit00** [comment]
closing in favour of #12
