### ISSUE TITLE
HTTPS protocol at dev

### ISSUE THREAD

**Issue by franklinjavier** [pedronauck/docz#310]
## Bug Report

Starting dev with `https` protocol instead `http`

**To Reproduce**

1. `yarn docz dev`
```shell
DONE  Compiled successfully in 200ms                                                                                                                                        
Your application is running at https://localhost:3000
```

**Comment by robhowell** [comment]
I was just trying out `docz` and had this issue too - it looked like the build was successful, but when I went to the URL that it provided () I saw the following generic error message provided by Google Chrome:
```
This site can’t be reached
localhost unexpectedly closed the connection.
```

It was only when I found this issue on GitHub that I realised that the non HTTPS version of the URL actually works.

**Comment by robhowell** [comment]
@franklinjavier Btw, here is a short term fix to switch to `http` and show the correct URL in the console:

Create a `doczrc.js` file in the root of your project with the following contents:
```
const config = {
  protocol: 'http'
};

module.exports = config;
```

By default it seems to be running the `http` version but outputting the URL for `https` - setting `http` makes them both use `http`.

I've tried manually setting `https` in that config file too, but didn't have any success.

**Comment by mpivaa** [comment]
I've submitted an PR #321 to fix this issue

**Comment by julioxavierr** [comment]
Can we close this?

**Comment by pedronauck** [comment]
For sure, I'll release some version soon with this fixed!
