### ISSUE TITLE
Can't resolve 'happypack/loader?id=jsx'

### ISSUE THREAD

**Issue by thib3113** [pedronauck/docz#313]
## Bug Report

**Describe the bug**
When I'm building, I'm getting the error

```
C:/Users/thib3/AppData/Roaming/npm/node_modules/docz/node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx
Module not found: Can't resolve 'happypack/loader?id=jsx' in 'C:\Users\thib3\repos\styleguide'
```

**To Reproduce**

1. clone this repo : https://github.com/thib3113/styleguideBug
2. launch `npm run docz:build`
3. See error

*A clear and concise description of what you expected to happen..*
Something working

**Environment**

* OS: Windows 10
* Node/npm version: Node 10.4, Npm 6.4.1

**Comment by justinkchen** [comment]
Maybe related, i'm getting this error in my repo:

```
Module build failed (from ./node_modules/happypack/loader.js):
Error: [BABEL] /Users/justinkchen/workspace/set-protocol-docs/.docz/app/index.jsx: You gave us a visitor for the node type PrivateName but it's not a valid type (While processing: "/Users/justinkchen/workspace/set-protocol-docs/node_modules/babel-preset-docz/dist/index.js$2")
    at Array.reduce (<anonymous>)
```

**Comment by thib3113** [comment]
@justinkchen  I think it's not the same error, you had an error message :
>  You gave us a visitor for the node type PrivateName but it's not a valid type
It's say you maybe had an error in one of your component .

**Comment by justinkchen** [comment]
Hmm...but for some reason it works on older version on docz, not on 0.11.1

**Comment by pedronauck** [comment]
Hi @thib3113, you forgot to add `docz` as `devDependency` on your project... I just ran these commands and everything works fine for me:

```bash
$ npm install --save-dev docz
$ npm run docz:dev
```

![](https://cdn-std.dprcdn.net/files/acc_649651/stITcT)

**Comment by thib3113** [comment]
Hum, I need to retry this morning . But if I remember, installing docz in
local ( !global ) , produce uglyfying error . ( I'll retry )

Le mar. 11 sept. 2018 à 07:28, Pedro Nauck <notifications@github.com> a
écrit :

**Comment by thib3113** [comment]
@pedronauck : After re-reading your answer . My bug is "building", so `npm run build` !

With docz in devdependencies : 
[image](https://user-images.githubusercontent.com/5489218/45346809-9b566b80-b5aa-11e8-953a-d8c3bdc8eccf.png)
 I've found an issue when you just answer "some dependencies can't be minified", but I've try with only one dependencies "docz", and this don't work .

**Comment by pizza-r0b** [comment]
I get this error too when running build. `docz` is added to my dev dependencies.

![image](https://user-images.githubusercontent.com/5282495/53836809-c9a77900-3f45-11e9-9d35-012edb006932.png)
