### ISSUE TITLE
mdx hashtag links are not respecting the 'hashRouter' configuration

### ISSUE THREAD

**Issue by sag1v** [pedronauck/docz#314]
## Bug Report
As a followup to #268 when you set `hashRouter: true`, the hashtag links ignoring it. 
this will result in  a  "page not found".
![docz route bug](https://user-images.githubusercontent.com/9153149/45253772-9e1c4b00-b375-11e8-9e5c-519ba0f8bbd6.jpg)

**To Reproduce**

1. Set  `hashRouter: true`
2. Create a simple `.mdx` file with a local link:  

```
---
name: Getting started
route: /
---

## Hello
```  
3.Click the hashtag link `Hello`
4. You will be navigating to the "page not found": `localhost:port/#hello` 

**Expected behavior**
Navigate to the correct route using the `hashRouter`: `localhost:port/#/#hello`

**Comment by pedronauck** [comment]
Fixed, will be released in the next version 🙏
