### ISSUE TITLE
Performance problems. Need max height on list with overflow scroll and virtual list.

### ISSUE THREAD

**Issue by johnpittman** [pedronauck/docz#317]
## Bug Report

**Describe the bug**

### Problem
- My massive list of components will not fit under one module group you the list needs to be designed to handle that. 
- Reopening and using the list is extremely slow so make sure you're at least using unique key for the "key" prop (the array index will be fine here since the size of the list never changes). 
- Crazy load times. Loading shit tons of components with .mdx is too slow.
- Scroll the page with lots of items is extremely janky too which should not matter at all once the page loads so I'm think there's a list issue or some re-renders going on. It's pretty much unusable. UPDATE:
I find that the page is only janky when scrolling the page scrolls and not inner divs I create within the playground). Are you using some kind of react scroll component that's causing re-renders instead of just overflow: scroll? Removing the Playground fixes a lot but I simple have to create my own page with styles to get no lag.
- React tools is listing two apps loaded:
![image](https://user-images.githubusercontent.com/6298219/45278325-2f80df80-b492-11e8-9ed3-012ad317dcbe.png)

### Improving performance:
- Use a react virtualized list.
- Only get the header information of the .mdx file to to generate the sidebar etc. and implement lazy loading via import('./component') using <universal-component />.
- Look into fuse-box if the above improvements do nothing, although, lazy process will fix it most likely.

![image](https://user-images.githubusercontent.com/6298219/45276217-82549a00-b486-11e8-86e1-eead0fa9f394.png)

*A clear and concise description of what the bug is.*

**To Reproduce**

```shell
FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pedronauck** [comment]
Fixed, will be released in the next version!
