### ISSUE TITLE
Use webfonts in doczrc

### ISSUE THREAD

**Issue by ahgharian** [pedronauck/docz#320]
I'm trying to use a webfont for the docz instance we have but not able to find any documentation as how to achieve this. Is it supported? if so, any documentation you can point me to? if not, would that be a feature request? 

Thanks! 👍

**Comment by pedronauck** [comment]
For sure @ahgharian, you can add some tags on `<head>` by adding a `htmlContext` property on your `doczrc.js`, like that:

```js
// doczrc.js
export default {
  htmlContext: {
    head: {
      links: [{
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css?family=Roboto'
      }]
    }
  },
}
```

Then you're able to use your font however your want :v:
