### ISSUE TITLE
Module resolution off when building/production

### ISSUE THREAD

**Issue by drcmda** [pedronauck/docz#326]
Is there anything special the internal webpack instance does to imports? I noticed my code behaves differently in production until i figured it didn't actually load what i needed it to load, but ran fetching something else. This only happens when i build docz.

Here's an example which i could track down:

<img width="748" alt="screenshot 2018-09-11 at 17 43 12" src="https://user-images.githubusercontent.com/2223602/45371242-65d17280-b5ea-11e8-9c60-4fa17f3a9311.png">

The original mdx code says:

```
---
name: Spring
route: /spring
order: 7
---

import { Playground, PropsTable } from 'docz'
import { Spring, config } from '../src/targets/web/index.js'
```

the folder structure is as follows:

```
react-spring/
  documentation/Spring.mdx
  src/
    targets/web/index.js
    Spring.js
```
I don't understand how it makes `/web/index` (which prepares some globals, then loads `src/Spring` internally into plain `src/Spring` all by itself? Or how and why it then loads `/web/shared/constants` ...

To me it looks like tree shaking is broken.

**Comment by drcmda** [comment]
Indeed, if i switch webpacks treeshaking off all is good

```js
modifyBundlerConfig: (config, dev, args) => {
    return {
      ...config,
      module: {
        ...config.module,
        rules: [
          ...config.module.rules,
          { test: () => true, sideEffects: true },
        ],
      },
    }
  },
```

**Comment by pedronauck** [comment]
Closed for being an old issue. If someone keeps seeing this, please reopen it.
