### ISSUE TITLE
PropsTable does not work with es7 static propTypes

### ISSUE THREAD

**Issue by johnpittman** [pedronauck/docz#329]
## Bug Report

**Describe the bug**

Using es6 classes with 
```javascript
 static propTypes
``` 
does not work with PropsTable. I use static propTypes on every component I have that's not stateless.

![image](https://user-images.githubusercontent.com/6298219/45400966-1c961880-b614-11e8-9416-ef311e741a0e.png)

*A clear and concise description of what the bug is.*

**To Reproduce**

```shell
FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by stefanbuck** [comment]
I'm using docz v0.11.2 with babel 7 and there it works for static prop types. However, it does not work when importing PropTypes from another file. The example below shows only `anotherProp` in the `PropsTable`. Should I raise a separate issue for this?

```js
import BasePropTypes from '../base/PropType';

class LineChart extends Component {
    static propTypes = {
        ...BasePropTypes, // Does not show up in the PropsTable
        anotherProp: PropTypes.array,  // Shows up in the PropsTable
    }
}
```

**Comment by ylin6** [comment]
I am having the same issue where shared PropTypes are not rendering in the Props table. Did you resolve this issue?

**Comment by pedronauck** [comment]
Closed for being an old issue. If someone keeps seeing this, please reopen it.
