### ISSUE TITLE
Allow ThemeProvider to accept multiple children

### ISSUE THREAD

**Issue by denisborovikov** [pedronauck/docz#331]
##  Feature Request

The new upcoming version of [styled-components](https://github.com/styled-components/styled-components) introduced the new way of working with global styles. Instead of direct styles injecting the global styles now a component which should be rendered.

More info [migrating guide](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4),  [API references](https://www.styled-components.com/docs/api#createglobalstyle)

The problem with it that it's not possible to integrate global styles into the docz.

Here what I did it before:

## Wrapper.js

```js
import React from 'react';
import { ThemeProvider } from 'styled-components';
import { theme } from 'shared/theme';
import './global.css';

// Docz application wrapper
const DoczWrapper = ({ children }) => (
  <ThemeProvider theme={theme}>{children}</ThemeProvider>
);

export default DoczWrapper;
```

## global.css.js

```js
injectGlobal`...`;
```

As global styles is a component now, it should be rendered  (`global.css` is `global.css.js` with `createGlobalStyle` inside):

## Wrapper.js
```js
import { GlobalStyle }  from './global.css';

// Docz application wrapper
const DoczWrapper = ({ children }) => (
  <ThemeProvider theme={theme}>
    {children}
    <GlobalStyle />
  </ThemeProvider>
);
```

## global.css.js

```js
export const GlobalStyle = createGlobalStyle` ...`;

```

But `ThemeProvider` expects only single child and throws an error

```
React.Children.only expected to receive a single React element child.
```

It's not also possible to pass `children` prop inside `GlobalStyle`, it's not expected to have `children` at all.

Possible workaround is to modify `GlobalStyle` component

## global.css.js

```js
const GlobalStyle = createGlobalStyle` ...`;
export const GlobalStyleWrapper = ({ children }) => <>{children}<GlobalStyle /></>
```

## Wrapper.js
```js
import { GlobalStyleWrapper }  from './global.css';

// Docz application wrapper
const DoczWrapper = ({ children }) => (
  <ThemeProvider theme={theme}>
    <GlobalStyleWrapper>{children}</GlobalStyleWrapper>
  </ThemeProvider>
);
```

but it would be esier to allow `ThemeProvider` accepts multiple children.

**Comment by mpivaa** [comment]
I think this is not a problem of `docz` itself. Try to wrap the children in a Fragment, like:

```js
<ThemeProvider theme={{ fontFamily: 'Helvetica Neue' }}>
  <React.Fragment>
    <Navigation /> {/* example of other top-level stuff */}
    <GlobalStyle whiteColor />
  </React.Fragment>
</ThemeProvider>
```

**Comment by denisborovikov** [comment]
Shame on me, I forget about the `Fragment`.
