### ISSUE TITLE
react-router shouldn't preserve scroll position

### ISSUE THREAD

**Issue by denisborovikov** [pedronauck/docz#333]
## Bug Report

react-router shouldn't preserve scroll position on opening a new route.

It's ok if you go back in history,  but looks weird when you click on the internal link somewhere in the middle of the page and navigates to the same scroll position of another doc. 

### Expected behavior 

On opening a new route, scroll position resets to top.

**Comment by pedronauck** [comment]
Fixed, will be released in the next version 👍
