### ISSUE TITLE
PropsTable is not working with components encapsulated by React.forwardRef()

### ISSUE THREAD

**Issue by filhocodes** [pedronauck/docz#334]
`<PropsTable of={Input} />` only works when I remove the `React.forwardRef()`. The following code is Typescript, and I also have `typescript: true` on my config.

```tsx
import * as React from "react"
import styled from "styled-components"

// Estilos ---------------------------------------------------------------------

const StyledInput = styled.input.attrs({
  className: "form-control",
})`
  height: 40px;
  margin-bottom: 0;
  font-size: 0.8125rem;
`

const FormRow = styled.div.attrs({
  className: "form-group",
})`
  margin-bottom: 1.25rem;
`

// <Input /> -------------------------------------------------------------------

interface IPInput {
  id: string
  label?: string | false
  placeholder?: string
}

const Input = React.forwardRef(
  (
    { id, label, placeholder, ...extraProps }: IPInput,
    ref: React.RefObject<HTMLInputElement>,
  ) => (
    <FormRow>
      <label
        htmlFor={id}
        className={[false === label ? "sr-only" : ""].join(" ")}
      >
        {false === label && placeholder ? placeholder : label}
      </label>
      <StyledInput
        innerRef={ref}
        id={id}
        placeholder={placeholder}
        {...extraProps}
      />
    </FormRow>
  ),
)

export default Input

```

**Comment by larismourullo** [comment]
Same here! 😢

**Comment by sandiiarov** [comment]
I found a solution but it looks ugly.

```js
const WrappedComponent = React.forwardRef(
  function MyComponent(props, ref) {
    return <StyledComponent innerRef={ref} {...props} />;
  }
);

<PropsTable of={WrappedComponent.render} />
```

**Comment by Jared-Dev** [comment]
@sandiiarov [`innerRef` has been deprecated](https://www.styled-components.com/docs/api#deprecated-innerref-prop) in `styled-components`. `forwardRef` is what will need to be used in the future.

**Comment by sandiiarov** [comment]
@Jared-Dev Yeah I know. It doesn't matter in that example.

**Comment by JeroenReumkens** [comment]
It looks like as soon as your component is wrapped inside a HOC, it won't render the prop types. Quickest solution for now is to also export your component as a named export without the HOCs. That way your prop types will work again.

**Comment by zicodeng** [comment]
@jnaudin Thanks for posting such detailed solutions. The first one works great, but the second one I got `MyComponent.render is not a function` error. Any ideas?

**Comment by pedronauck** [comment]
I think that this will be resolved in the [v1](https://github.com/pedronauck/docz/pull/656) :v:

**Comment by jnaudin** [comment]
> @jnaudin Thanks for posting such detailed solutions. The first one works great, but the second one I got `MyComponent.render is not a function` error. Any ideas?

I think you imported the wrapped component and not the HOC:
import {MyComponent} from './MyComponent'
instead of 
import MyComponent from './MyComponent'

Can you show me what your code ?

**Comment by pedronauck** [comment]
Closed in favor of the newest release.
