### ISSUE TITLE
Netlify CMS

### ISSUE THREAD

**Issue by richTheCreator** [pedronauck/docz#335]
## Question
How can I include the necessary admin folder alongside the served up static files?

**Description**
In order for netlify cms to work, it needs to be included along with the static files in the build.  I've tried placing in `public` and `src` but no luck. Any help welcomed

**Comment by nicholasess** [comment]
@richTheCreator I don`t understand your question, do you use docz for what?

**Comment by richTheCreator** [comment]
@nicholasess I'd like to know how to add my own files/folder into the build process. I am using it as the view layer to a documentation site. While Netlify cms will act as the management layer.

**Comment by denisborovikov** [comment]
@richTheCreator  Use regular cp (copy) command in your build script (depends on your OS)

Here's an example for MacOS. Add to your package.json into scripts section something like:
```
"scripts": {
    "build:doc`": "docz build; cp -r admin ./.docz/dist'",
}
```
