### ISSUE TITLE
Possibility for tslint inside mdx files?

### ISSUE THREAD

**Issue by simonzsolt89** [pedronauck/docz#340]
Hello! First I would like to thank you for this amazing project! I am loving it! 
My question is for Docz configured to use Typescript: 

I was wondering if there is a way to have type checking, or tslint active inside the mdx files for the parts that use ts components? 

As it is right now, if I misstype a component prop, my editor doesn't highlight it as an error. 

Thank you for taking the time to read this!

**Comment by pedronauck** [comment]
You can simply using `modifyBundlerConfig` to add your tslint or eslint loader ✌️

**Comment by jochienabuurs** [comment]
@pedronauck could you add an example of how to do this?
