### ISSUE TITLE
Have the ability to override ignoring files

### ISSUE THREAD

**Issue by iam-merlin** [pedronauck/docz#343]
Hi,
It should be interesting to push ignoring files in configuration with default values...

For example, in my project, we want to use the `README.md` as a "landing page".

For reference : https://github.com/pedronauck/docz/blob/e0a95b342822ab65e48cb327049800aba54b1455/packages/docz-core/src/Entries.tsx#L83

(btw, I'm not sure if it's a bug, but html in markdown create a rendering error in mdx)

**Comment by pedronauck** [comment]
Thanks, this feature will be added in the next release 🚀

**Comment by pedronauck** [comment]
Yeah, for sure, we can do that. I'll try to release in the next version 🙏

**Comment by pedronauck** [comment]
This is already launched using `ignore` property on `doczrc.js`

**Comment by zww-v5** [comment]
can I ignore the whole folder?
