### ISSUE TITLE
Feature request: Syntax highlight typescript blocks inside markdown

### ISSUE THREAD

**Issue by capaj** [pedronauck/docz#345]
Coming from github I expect the syntax higlighting to work for `ts`
Also you have this:
![image](https://user-images.githubusercontent.com/1305378/45933845-f61d9900-bf94-11e8-8cc9-2444cf2986e1.png)

in features. So I'd say it should be supported.

**Comment by pedronauck** [comment]
Fixed, will be released in the next version!
