### ISSUE TITLE
Bugs around styled-components 4.0 beta

### ISSUE THREAD

**Issue by eramdam** [pedronauck/docz#347]
## Bug Report

Some features of [styled-components](https://github.com/styled-components/styled-components) 4.0.0 beta are broken when used inside a Docz document.
I would open a bug to SC directly but the same code works fine in [react-styleguidist](https://github.com/styleguidist/react-styleguidist) so I'm not quite sure where I should open the issue.

The bugs seems to be mainly around the `styled()` syntax of styled-components. Which I assume got changed a bit internally with 4.x.

Considering this file

https://github.com/eramdam/docz-repro-error/blob/master/test/hello.tsx

Here is how it's supposed to look (and how it looks under styled-components 3.x):

<img width="1072" alt="screen shot 2018-09-20 at 3 22 11 pm" src="https://user-images.githubusercontent.com/1409924/45849966-00b40600-bce9-11e8-84fd-6e67383621f1.png">

Here is how it looks with styled-components 4.x installed:

<img width="1072" alt="screen shot 2018-09-20 at 3 20 45 pm" src="https://user-images.githubusercontent.com/1409924/45849972-0ad60480-bce9-11e8-8aef-455e06b9aeea.png">

Feel free to clone https://github.com/eramdam/docz-repro-error and alternate between the `master` branch (4.x) and `sc-v3` (3.x) to try.

I'd be happy to provide more details if needed.

**Comment by jamsch** [comment]
styled-components v4 somehow broke my app's navigation as well as extending on base styles didn't seem to work. No console errors or logs. I don't think it's related to docz though.

**Comment by guilhermedecampo** [comment]
For me docz is not reading propTypes from styled components. 

`Link.js`

```
import { Link as L } from '@reach/router'
import styled from 'styled-components'
import PropTypes from 'prop-types'

const Link = styled(L)`
  font-weight: bold;
  line-height: 1.5;
`

Link.propTypes = {
  to: PropTypes.string.isRequired,
}

export default Link
```

Link.mdx

```
---
name: Link
---

import { Playground, PropsTable } from 'docz'
import Link from './Link'

# Link

<PropsTable of={Link} />

## Basic usage

<Playground>
  <Link to="/">This is a link</Link>
</Playground>
```
![screen shot 2018-09-26 at 18 28 42](https://user-images.githubusercontent.com/4806269/46110449-095d7e00-c1ba-11e8-8293-0af6637d01a7.png)


dev mode

**Comment by pedronauck** [comment]
This problem is related to docgen parser, duplicated from #240 and all that depends of resolve this docgen bug 😕

**Comment by eramdam** [comment]
@pedronauck even the rendering issue with styled-components?

**Comment by pedronauck** [comment]
Sorry @eramdam, the rendering issue isn't a bug from react-docgen, I'll keep this openning 🙏

**Comment by itshizhan** [comment]
this is a real gotcha issue. i resolve it as follows：
```jsx
// Link is a styled components
const LinkWrapper = (props)=>(
   <Link {...props}/>
)
// docz reading propTypes from LinkWrapper
LinkWrapper. propTypes = {
   //props
}
export default LinkWrapper
```

**Comment by antoniojps** [comment]
Any follow up on this issue?

**Comment by pedronauck** [comment]
I'm closing this issue now in favor of the new one, most of the problems have been solved and are working now, but some others appeared.
