### ISSUE TITLE
[feature]Add a console tab to react-live

### ISSUE THREAD

**Issue by sag1v** [pedronauck/docz#349]
I searched it in the [Roadmap site](http://feedback.docz.site/roadmap) and issues but didn't find anyone suggesting it. 

I would love to see a new `console` tab next to the `JSX` and `HTML` tabs in the react-live window.  
In some examples of the component's API we print data to the console so it would be nice if the consumers wont need to open devtools for it.

Something like this:

![image](https://user-images.githubusercontent.com/9153149/45885728-dd0fbf00-bdbf-11e8-9ac3-70524d3a2390.png)

**Comment by nicholasess** [comment]
@sag1v nice, can you add in roadmap it?

**Comment by sag1v** [comment]
Done http://feedback.docz.site/roadmap/p/add-a-console-tab-to-react-live-window-playground
