### ISSUE TITLE
Hide mdx page from menu

### ISSUE THREAD

**Issue by imeldaloei** [pedronauck/docz#359]
## How can I hide an mdx page that is in progress from the menu so that it is not discoverable by users?

**Description**
We have multiple developers working on documentation so we often have mdx that is in progress that we don't want to expose to end users yet. Currently we use a workaround of renaming the .mdx file to .md which works but not ideal because developers usually deploy pull requests to a dev environment for review and in this case, the reviewer will have to pull the branch down locally in order to change the file extension back to .mdx to review the page. Just want to check in and see if we're missing an obvious workflow here 😄

Thank you! We ❤️docz!

![screenshot-localhost-3001-2018 09 24-10-12-46](https://user-images.githubusercontent.com/1466645/45967395-bb425200-bfe2-11e8-891c-256cc33cc614.png)

**Comment by nicholasess** [comment]
@imeldaloei There isn't the option on docz today, Can you add in roadmap the new feature?

http://feedback.docz.site/

Thanks

**Comment by imeldaloei** [comment]
thanks @nicholasess for the quick response! i've added it to the roadmap: http://feedback.docz.site/roadmap/p/hide-mdx-page-from-menu

**Comment by adrianoresende** [comment]
Suggestion:
```
---
name: Design System
route: /
menu: false
---
```

**Comment by Kivylius** [comment]
A work around thats a bit of hack that i'm currently using is, setting the menu to an empty array and it will hide it (partly), e.g
```mdx
---
name: [] <--
route: '/components/Sleek'
menu: Components
---
```

**Comment by poldridge** [comment]
`hidden: true` seems to work, although I can't find any documentation for it:

```
---
name: Home
route: /
hidden: true
---
```
