### ISSUE TITLE
Unable to get propTypes or props from component instance

### ISSUE THREAD

**Issue by louis-pvs** [pedronauck/docz#36]
When I `console.log(MyComponent.proptypes)` in my normal development environment I able to see all the `propTypes` console out correctly. However, it console `undefined` when it import into `.mdx` same goes to `console.log(MyComponent.props)`). The only thing console out correctly is `console.log(MyComponent.defaultProps)`, the console is in the `MyComponent/index.js` it self.

**To Reproduce**
1. Create a new `class MyComponent extends Component` with propTypes
2. put in a `console.log(MyComponent.props)` in `render()` function
3. Run dev server and see the console
4. Create `.mdx` file import `MyComponent`
5. Run `docz dev` and see `undefined` in the console

[Related question from stackoverflow](https://stackoverflow.com/a/32115267/5819443)

I not sure this is a docz bug or react bug, but it preventing me to use docz since I need to [pass down the rest of the props to the button DOM](https://github.com/louis-pvs/mrcw/blob/a7d558c0a75f6cf74a6d1559f5118300115de5a7/lib/Icon/index.js#L30) by `{...omit(this.props, Object.keys(Button.defaultProps))}` and it throw Error 
```shell
Uncaught TypeError: Cannot convert undefined or null to object
```

**Enviroment**
```json
{
  "engines": {
    "node": "8.11.1",
    "npm": "5.7.1",
    "yarn": "1.6.0"
  }
}
```

**Comment by pedronauck** [comment]
hi @louis-pvs... I forked your project and sent you a pr fixing the integration with docz!

basically something happen when you using `Component.defaultProps` in ts files, I don't know even whats happening. And when you use ts files, you need to export by default your component!

**Comment by louis-pvs** [comment]
@pedronauck thanks for checking out, but I still couldn't able to achieve it, I read the introduction knowing there is limitation of React Docgen, all my component are `export default` out. And my [linting rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/prefer-default-export.md) will remind me too.

and... did you send me a PR?

**Comment by pedronauck** [comment]
Yeah @louis-pvs, I sent you a pull request fixing the integration with docz ✌️

**Comment by louis-pvs** [comment]
hi @pedronauck sorry to coming back on this, but I [didn't receive any pull request](https://github.com/louis-pvs/mrcw/pulls).  And still not able to solve the prob, 😭 the only way I can get ride of the error is [publish them to npm and import them into Button.mdx](https://github.com/louis-pvs/mrcw/blob/0ff8506d3f7b32aa103919eae0166459f7242654/lib/button/Button.mdx#L6), but by doing so the PropsTable seems to be not showing at all
![screen shot 2018-06-22 at 11 56 05 am](https://user-images.githubusercontent.com/7659194/41757240-6a9a76e8-7613-11e8-9595-44adf55d15c7.png)
