### ISSUE TITLE
Add link on sidebar logo

### ISSUE THREAD

**Issue by wldcordeiro** [pedronauck/docz#365]
This is something that I try doing habitually but I try to click the heading (the "CNC Citadel" in my screenshot) in the top of the sidebar to go back to `/` of my docs but it's not a link. It'd be really nice to have.

<img width="628" alt="screen shot 2018-09-25 at 7 02 50 pm" src="https://user-images.githubusercontent.com/580982/46051303-e10c4b80-c0f5-11e8-8abf-d40bf63c061b.png">

**Comment by pedronauck** [comment]
Closed, will be added in the next release :v:
