### ISSUE TITLE
ReferenceError: FOO is not defined

### ISSUE THREAD

**Issue by yoohahn** [pedronauck/docz#366]
## Description

When trying to add a `const` in my `mdx` and use that in my component I get `ReferenceError: FOO is not defined`. But the const is being used in my component.

### Button.jsx
```
import React from 'react';
import PropTypes from 'prop-types';

const Button = ({ text }) => (<button type="submit">{text}</button>);
Button.propTypes = {
  text: PropTypes.string.isRequired,
};
export default Button;
```

### Button.mdx
```
---
name: Button
route: /Components/Button
menu: Components
---

import { Playground, PropsTable } from 'docz'
import Button from './Button'
const FOO = 'HELLO'

# Button

<PropsTable of={Button} />

## Basic usage

<Playground>
  <Button text={FOO}></Button>
</Playground>

```

**Result**
<img width="863" alt="screenshot 2018-09-26 at 21 14 13" src="https://user-images.githubusercontent.com/994522/46103441-25b8e500-c1d1-11e8-964c-b059c39e3629.png">

**Comment by pedronauck** [comment]
There's no possible to use declarations like `const, functions` inside `mdx`, just import from another files. What you can do to declare variables is pass a function as a children for your Playground or use `getInitialData` to attribute something on document scope:

```md
---
name: Button
route: /Components/Button
menu: Components
---

import { Playground, PropsTable } from 'docz'
import Button from './Button'

# Button

<PropsTable of={Button} />

## Basic usage

<Playground>
  {() => {
    const foo = 'foo'
    return <Button text={foo}></Button>
  }}
</Playground>
```

or

```md
---
name: Button
route: /Components/Button
menu: Components
---

import { Playground, PropsTable } from 'docz'
import Button from './Button'

export const getInitialData = () => ({
  foo: 'FOO'
})

# Button

<PropsTable of={Button} />

## Basic usage

<Playground>
  <Button text={props.data.foo}></Button>
</Playground>
```

**Comment by kachkaev** [comment]
I ran into the same issue and was confused by the fact that `export const FOO = 'HELLO'` gets highlighted in VSCode:

![screenshot 2019-01-22 at 13 06 15](https://user-images.githubusercontent.com/608862/51537481-a10c6980-1e46-11e9-90e2-d05923afe3e9.png)

**Comment by pedronauck** [comment]
Because there's no difference between a line that starts with const on another word. You will get syntax highlight/javascript code just when your line starts with `import`, `export` or some jsx. Outside these words, mdx will parse everything as a markdown node.

**Comment by kachkaev** [comment]
That makes sense. The problem appears to be on the code highlighting side, which confused me. Just shared own experience to help others that may search for the same thing.
