### ISSUE TITLE
Configurable module resolvers

### ISSUE THREAD

**Issue by benswinburne** [pedronauck/docz#373]
When there's custom resolver logic being used by Webpack in the project Docz is unable to find them. For example, when using something like [`directory-named-webpack-plugin`][plugin] Docz seems unable to resolve modules.

For example, given the following resolve setup in webpack.config.js

```
resolve: {
  modules: [path.resolve('./src'), path.resolve('./node_modules')],
  plugins: [
    // Then when require("component/foo") and the path "component/foo" is
    // resolved to a directory, Webpack will try to look for
    // component/foo/foo.js as the entry (given default options).
    new DirectoryNamedWebpackPlugin({
      include: [path.resolve('./src')],
    }),
  ],
},
```

components/TextInput/TextInput.js
```
import Button from 'components/Button';

export default class TextInput extends Component {}
```

components/TextInput/TextInput.mdx
```
---
name: TextInput
---

import { Playground, PropsTable } from 'docz'
import TextInput from './TextInput.js'

# TextInput

<PropsTable of={TextInput} />

## Basic usage

<Playground>
  <TextInput></TextInput>
</Playground>
```

Results in

> This dependency was not found:
> * components/Button in ./src/components/TextInput/TextInput.js

Similarly if i were to change the import of TextInput.js in the mdx file to 

```
import { Playground, PropsTable } from 'docz'
import TextInput from 'components/TextInput.js'
```

> This dependency was not found:
> * components/TextInput.js in ./src/components/TextInput/TextInput.mdx

It'd be great if we could configure the webpack resolver options (and therefore be able to import the ones from the project's webpack.config.js file). 

Jest has a similar feature whereby you can set the module resolver to a module/function. This module [`jest-webpack-resolver`][resolver] grabs the config from webpack and plugs it into jest. Perhaps this could be used for ideas?

Apologies if I'm missing something and there's already a facility by which do do something like this?

Cheers

[plugin]: https://github.com/shaketbaby/directory-named-webpack-plugin
[resolver]: https://github.com/mkg0/jest-webpack-resolver

**Comment by jedrichards** [comment]
Check out the "Creating plugins" documentation. Does the `modifyBundlerConfig` method do what you need? It lets you tweak the Webpack config used by Docz, so you can add your own rules etc.

https://www.docz.site/documentation/creating-plugins

**Comment by chrstntdd** [comment]
I'm running into these same issues. I tried the suggestion given here: https://github.com/pedronauck/docz/issues/243#issuecomment-415184195, but I am still encountering the same issue.

This is what my doczrc.js looks like:

```js
import webpackConfig from './config/webpack.config.dev';

export default {
  modifyBundlerConfig: config => {
    const newConfig = {
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve.alias,
          ...webpackConfig.resolve.alias
        }
      }
    };

    return newConfig;
  },
};

```

Within the my webpack config, there's an alias defined for `@: path.resolve(__dirname, 'src')`, but it doesn't seem to be applied correctly when using docz. I keep getting errors that an import used within a component I'm trying to document (that relies on the path alias) can't be resolved. Sometimes it even bundles without showing any errors, but when I go to view the documentation, the app crashes with this stacktrace:

```
🚨 Whoops, we crashed 🚨
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `o`.
Stack trace
in o (created by AsyncComponent)
in AsyncComponent (created by t)
in t (created by Context.Consumer)
in b (created by s)
in s (created by Context.Consumer)
in Component (created by AsyncRoute)
in div (created by Styled(div))
in Styled(div) (created by ConsumerMemoization)
in div (created by Styled(div))
in Styled(div) (created by ConsumerMemoization)
in div (created by Styled(div))
in Styled(div) (created by Mt)
in Mt (created by ConsumerMemoization)
in ConsumerMemoization (created by Context.Consumer)
in CopyOnWriteConsumer (created by Context.Consumer)
in ThemeConfig (created by Wt)
in Wt (created by AsyncRoute)
in AsyncRoute (created by t)
in t (created by ConsumerMemoization)
in t (created by ConsumerMemoization)
in ConsumerMemoization (created by Context.Consumer)
in CopyOnWriteConsumer (created by Context.Consumer)
in MDXProvider (created by DocPreview)
in DocPreview (created by ConsumerMemoization)
in ThemeProvider (created by ConsumerMemoization)
in ConsumerMemoization (created by Context.Consumer)
in CopyOnWriteConsumer (created by Context.Consumer)
in ThemeConfig (created by Component)
in Component (created by DoczTheme)
in DefaultWrapper (created by DoczTheme)
in ScrollToTopBase (created by t)
in t (created by withRouter(ScrollToTopBase))
in withRouter(ScrollToTopBase) (created by DoczTheme)
in t (created by t)
in t (created by DoczTheme)
in DataServer (created by DoczTheme)
in CopyOnWriteStoreProvider (created by DoczTheme)
in ErrorBoundary (created by DoczTheme)
in DoczTheme (at root.jsx:9)
in Root (created by HotExportedRoot)
in AppContainer (created by HotExportedRoot)
in HotExportedRoot (at app/index.jsx:15)
```

**Comment by pedronauck** [comment]
Use `onCreateWebpackChain` to create your alias, it's more safety:

```
export default {
  onCreateWebpackChain: config => config.resolve.alias.set('foo', 'bar')
}
```

**Comment by adeelibr** [comment]
> Use `onCreateWebpackChain` to create your alias, it's more safety:
> 
> ```js
> export default {
>   onCreateWebpackChain: config => {
>     config.resolve.alias.set('foo', 'bar')
>   }
> }
> ```

@pedronauck This should be documented somewhere in the documentation, I had some trouble finding this. If it's okay can I make a PR for this? I don't know which section would be appropriate for this information though 😅

**Comment by adeelibr** [comment]
Also I am using rollup, for my library `melting-pot`  https://github.com/withvoid/melting-pot! So the below change was the option for me for using alias in docz site https://melting-pot.netlify.com/

```js
// .babelrc
(...)
"plugins": [
    ["module-resolver", {
        "root": ["./src"],
        "alias": {
            "app": "./src/app"
        }
    }]
],
(...)
```
Reference https://github.com/pedronauck/docz-plugin-css/issues/1#issuecomment-425502093

P.S: Thank you for such an amazing tool.
