### ISSUE TITLE
Use docz without the react dependency

### ISSUE THREAD

**Issue by tinchoz49** [pedronauck/docz#374]
## Can I use docz without having to add react as a dependency?

**Description**
I really like the project and I know that docz support `.md` file besides the default `.mdx`. 

So I want to create a documentation for a library that I have with some markdown files but this library doesn't use React.

But if I don't install React I get this error with docz:
```
🚨 Whoops, we crashed 🚨
Cannot convert undefined or null to object
Stack trace
in ConsumerMemoization (created by Context.Consumer)
in CopyOnWriteConsumer (created by Context.Consumer)
in ThemeConfig (created by Component)
in Component (created by DoczTheme)
in DefaultWrapper (created by DoczTheme)
in t (created by t)
in t (created by DoczTheme)
in DataServer (created by DoczTheme)
in CopyOnWriteStoreProvider (created by DoczTheme)
in ErrorBoundary (created by DoczTheme)
in DoczTheme (at root.jsx:30)
in Root (created by HotExportedRoot)
in AppContainer (created by HotExportedRoot)
in HotExportedRoot (at app/index.jsx:16)
```

Thanks for this awesome work.

**Comment by nicholasess** [comment]
@tinchoz49 you can use React as devDependecie and won’t do harm your project

**Comment by tinchoz49** [comment]
Hi @nicholasess thanks for helping me. Yes, I can do that, but also I think that maybe docz is not the best option for what I want to do.
