### ISSUE TITLE
Use Docz on Existing Create-React-App on Netlify

### ISSUE THREAD

**Issue by alexlee-dev** [pedronauck/docz#376]
## Question
How can I use Docz along an already existing project build with create-react-app and hosted on Netlify?

**Description**
I have a project hosted on Netlify. I'd like to use Docz as documentation for the project. Ideally the URL's would look like this:

**Main Site** -> `https://www.projectname.com/`
**Docs Page** -> `https://www.projectname.com/docs/`

I'm aware of the `base` within a `doczrc.js` file at the root of an application, as seen on [the documentation](https://www.docz.site/documentation/project-configuration#basic-config). I've also read through some other issues that mention a similar thing. However, I'm still unable to get this to work.

I also know that Netlify has a way to use a `_redirects` file to redirect what is served. https://www.netlify.com/docs/redirects/ .

## Current Configurations

`doczrc.js`
```js
export default {
  ordering: 'ascending',
  dest: '/src/docs/',
  base: '/docs/',
  htmlContext: {
    favicon: 'https://raw.githubusercontent.com/alexlee-dev/portfolio/master/public/favicon/favicon.ico'
  }
}
```

**Comment by jedrichards** [comment]
@alexlee-dev The easiest way is to just publish the Docz site as a new Netlify site, and customise the build on that Netlify site with the Docz build command and output directory. So two Netlify sites feeding off the same repo - both are deployed whenever there's a change.

In terms of custom urls you could have:

```
https://www.projectname.com
https://docs.projectname.com
```

Which is fine I think?

**Comment by nicholasess** [comment]
@alexlee-dev i created a plugin to resolve the problem https://github.com/nicholasess/docz-plugin-netlify

**Comment by alexlee-dev** [comment]
@jedrichards Yeah, that's what I ended up doing, and it works alright.

@nicholasess I'll check it out. Thanks!

**Comment by adamduncan** [comment]
Related to this issue...

As a default files in `public` are currently copied to`.docz/dist/public` directory on `docz build`. Is there not a way of specifying that they're sent to `.docz/dist` instead?

Use case being, we might have these Netlify `_redirects`/`_headers` files or other compiled assets  that need to end up in the built `dest` root. Seems like a fairly common requirement? 

`docz-plugin-netlify` only really works under the assumption that all a Netlify project would need is SPA redirects to index.html.
