### ISSUE TITLE
Code Sandbox feature doesn't work with component that using babel-plugin

### ISSUE THREAD

**Issue by hamcompe** [pedronauck/docz#378]
## Bug Report

I've tried to use code sandbox feature with component that has been built by [emotion](https://github.com/emotion-js/emotion) with [babel-plugin-emotion](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion) to enable the way for styling by something like...

```js
const StyledButton = styled.button`...`
```

and code sandbox doesn't include the babel-plugin into it, so it raising the error
![download](https://user-images.githubusercontent.com/8385944/46254385-e16f6280-c4b8-11e8-9732-0725885c438c.png)

**To Reproduce**

1. install `emotion`, `react-emotion`, `babel-plugin-emotion`
2. put `{ "plugins": ["emotion"] }` in `.babelrc`
3. styling component by
```js
import styled from 'react-emotion'

export default styled.button`background: blue`
```
4. Create `mdx` file for that component
5. From docz UI click code sandbox button
6. see the error

**Expected behavior**
Any component that has been built with babel-plugin be able to show in code sandbox

**Environment**

* OS: OSX 10.14.0
* Node version 8.11.4
* yarn version 1.9.4

**Comment by corysimmons** [comment]
I'm having same issue with the react sandbox. Is `.babelrc` supposed to work? CRA just recently upgraded to support custom Babel configs right?

**Comment by nicholasess** [comment]
@ CompuIves Can you help they? 

Thanks

**Comment by hamcompe** [comment]
@corysimmons I haven't checked it yet, but I think CRA 2.0 still **doesn't support** custom `.babelrc`. Instead of that I think it support the `babel-plugin-macros`, which seems like this can be fix our issue.

I haven't played with `babel-plugin-macros` yet, so I don't know exactly how to use it either.

**Comment by corysimmons** [comment]
lmao sorry @nicholasess I thought this was codesandbox-client repo. xD

**Comment by CompuIves** [comment]
Hey! I can help with this 😄.

CodeSandbox supports `.babelrc`, but it's disabled for the CRA projects since they don't enable it. We could maybe export it as a `vanilla` template, which does support `.babelrc`.

**Comment by hamcompe** [comment]
That sounds nice!!

**Comment by nicholasess** [comment]
@hamcompe Can I close the issue?

**Comment by hamcompe** [comment]
@nicholasess Sure! Seems like it's something to deal with the codesandbox first.
