### ISSUE TITLE
Could not create Open in CodeSandbox

### ISSUE THREAD

**Issue by conradoramalho** [pedronauck/docz#383]
## CodeSandbox

I am creating a lib using nwb but when I am running the docz server I have the following error in terminal:

  
```shell
Could not create Open in CodeSandbox { Error: Cannot find module 

'C:\Users\conrado.ramalho\Desktop\nwb-thinking-in-react\App' from

'C:\Users\conrado.ramalho\Desktop\nwb-thinking-in-react\node_modules\codesandboxer-fs\src'
```
I have this component in my .mdx file:

```mdx
import { Playground } from 'docz'
import  MyComponent from './App'

# Hello world

Hello, I'm a mdx file!
<Playground>
  <MyComponent />
</Playground>
```

**Environment**

* OS: [Windows 10]
* Node/npm version: [e.g. Node 10.4.1/npm 6.1.0]

**Comment by cvisco** [comment]
I'm running into a similar similar error due to the fact that my components import `.less` stylesheets:
```
Could not create Open in CodeSandbox Error: unparseable filetype: .less for file ...
```

**Comment by kikorb** [comment]
Same here

**Comment by conradoramalho** [comment]
The bug can be codesandboxer-fs lib
https://github.com/Noviny/codesandboxer/issues/33

**Comment by sag1v** [comment]
Same here:
>Could not create Open in CodeSandbox Error: invalid relative path from  to ../components/Box

**Comment by pedronauck** [comment]
Hi guys, sorry the too late response, last weeks was very hard to me and I couldn't see anything about docz, but now I available again, I'll check what's happening here :pray:

**Comment by pedronauck** [comment]
Fixed on the new release [v0.12.10](https://github.com/pedronauck/docz/releases/tag/v0.12.10) ✅

**Comment by evangoer** [comment]
It's working great Pedro, thank you! Hope you're having a better week.

**Comment by theTechie** [comment]
Figured there was some problem with the way i was importing some modules; specifically trying to access a flow type which was not exported by module

wonder how can we make the error more informative. @pedronauck
