### ISSUE TITLE
TypeScript populating PropsTable description from interface

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [pedronauck/docz#384]
## Question
Is there a way to populate the description field of a `PropsTable` based on a TypeScript `interface`?
**Description**
I use separate interface files for defining the properties a component should take. Is there any way to populate the description column of the `PropsTable` when using TypeScript in this manner?

**Comment by dotlouis** [comment]
Yes you can. I tried using the description format `/** Description */` specified in the [docs](https://www.docz.site/documentation/components-api#propstable) and it worked.

```typescript
interface MyProps {
  /** This is a color description */
  color: string;
}
```

**Comment by InquisitiveDevelopment** [comment]
And you set this interface up in a separate file?

**Comment by InquisitiveDevelopment** [comment]
I did just move the interface into the same file as the component and it worked as the docs suggest. 

If there is any point where there is just NO way that I'd be comfortable leaving the description out of the documentation I may implement the interface this way, but I'd definitely prefer the interface to exist outside of the component if possible.

**Comment by InquisitiveDevelopment** [comment]
So this ended up being an issue with Webpack. A change to the external interfaces **does** trigger a rebuild, but it doesn't actually factor in `interface` changes to a rebuild. It does actually do a build on its initial build.

I'm not sure where that issue is, but I'm closing this issue since the library itself is working as it should.
