### ISSUE TITLE
Have the ability to set SVGR built-in configuration

### ISSUE THREAD

**Issue by danielbayerlein** [pedronauck/docz#389]
## Question

How can I configure the [SVGR](https://github.com/smooth-code/svgr) built-in?

My current loader looks like this:

```
test: /\.svg$/,
use: {
  loader: '@svgr/webpack',
  options: {
    icon: true,
    replaceAttrValues: {
      '#1a171b': 'currentColor'
    }
  }
}
```

**Comment by lasimonne** [comment]
You can use the modifyBundlerConfig

```js
// doczrc.js
export default {
  modifyBundlerConfig: (config) => {
    /* custom loaders */
    config.module.rules.push({
        test: /\.svg$/,
        use: '@svgr/webpack',
    });
    return config
  }
}
```

**Comment by danielbayerlein** [comment]
@lasimonne In your example you add the `@svgr/webpack` loader, but it is already integrated in the new version of `docz`. Let me know if I misunderstood something.

**Comment by lasimonne** [comment]
@danielbayerlein I might have misunderstood you, are you talking about `.svgrrc` configuration?

**Comment by danielbayerlein** [comment]
@lasimonne Thanks, I did not know the configuration file! But it looks like the configuration file is ignored. 😕

**Comment by danielbayerlein** [comment]
https://github.com/smooth-code/svgr#configurations

**Comment by pedronauck** [comment]
Hi @danielbayerlein, that's is something that we need to put on doczrc. I'll do that and put for the last release 🙏

**Comment by pedronauck** [comment]
oh, really? and this work actually with docz too @danielbayerlein ?

**Comment by danielbayerlein** [comment]
@pedronauck Yes, the configuration file `.svgrrc` works fine.

**Comment by pedronauck** [comment]
Cool! So, I'll let just this config instead of put a new property on doczrc, thanks to the tip dude 🙏
