### ISSUE TITLE
Feature Request: Toggle side-by-side view for `jsx` and `html`

### ISSUE THREAD

**Issue by Jared-Dev** [pedronauck/docz#390]
## Awesome, do you have an idea? 😍

I originally thought an icon sitting between the `JSX` and `HTML` buttons would be ideal, but I'm not sure there. 

Anyway, it would be handy to have the ability to have the original `JSX` sit beside the `HTML` that is generated!

**Comment by nicholasess** [comment]
@Jared-Dev Could you add the feature in roadmap? 
http://feedback.docz.site/
Thanks
