### ISSUE TITLE
What is the best way for designers to participate in DOCZ flow? 

### ISSUE THREAD

**Issue by dusskapark** [pedronauck/docz#394]
## Question

> What is the best way for designers to participate in DOCZ flow? 

**Description**

Hi, I am a designer and I recently have thought about how to work more efficiently with our FE engineers. I have some node js and React experience, but not a professional one. I often make designs with Sketch + Zeplin and pass it to FE developer, Johnny. He is an excellent React engineer. He recently made a design that I passed through Zeplin as React components and then created/delivered it using DOCZ. I think his efforts have improved the collaboration a lot. It's comfortable and cool! 

So, on the other hand, I started to think about how I could help FE engineers by participating in their DOCZ work. Well, to be honest, I thought it was not cool to send design results through Zeplin and the UX guide(PDF, wiki). 

I've read some blog posts like `Storybook Driven Development` but I do not exactly know how to get started. Let me know if anyone has any experience!

**Comment by thebergamo** [comment]
Hey @dusskapark not sure if this can clarify your question, but this talk from Monica Lent may help you to connect the dots with you FE team.

https://www.youtube.com/watch?v=CzTnQg5Mg2E

**Comment by Glazy** [comment]
Hey @dusskapark :wave:

I will close this issue because it is inactive and I assume you have found a good way to integrate Docz into your flow. If that isn't the case then please open up a new issue and we can discuss it some more :+1:
