### ISSUE TITLE
cannot load docs on clean project when using npm instead of yarn

### ISSUE THREAD

**Issue by natergj** [pedronauck/docz#397]
## Bug Report

**Describe the bug**
On a clean project, the documentation does not load and an error appears in the debugger console when docz is installed via npm instead of yarn.

**To Reproduce**

1. clone repo
2. run `npm install`
3. run `npm run docz:dev`
4. open browser to http://localhost:3000 and open developer tools

If, however, `yarn` is used in step 2, issue does not appear.

This issue only appears in version 0.12.x, 0.11.x works fine with npm.

```shell
buble-browser.es.js?a7b4:633 Uncaught TypeError: Cannot set property 'jsx' of undefined
    at inject (buble-browser.es.js?a7b4:633)
    at eval (buble-browser.es.js?a7b4:9830)
    at Array.reduce (<anonymous>)
    at Module.eval (buble-browser.es.js?a7b4:9829)
    at eval (buble-browser.es.js:9918)
    at Module../node_modules/buble/dist/buble-browser.es.js (vendors.js:1286)
    at __webpack_require__ (runtime~app.js:788)
    at fn (runtime~app.js:151)
    at eval (react-live.es.js?849f:1)
    at Module../node_modules/react-live/dist/react-live.es.js (vendors.js:5579)
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*
I created a clean project here: https://github.com/natergj/docz_clean

**Expected behavior**

either yarn or npm can be used in project

**Environment**

* OS: 10.14
* Node/npm version: npm: 6.4.1, node: 10.11.0, yarn 1.10.1

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

![image](https://user-images.githubusercontent.com/8051185/46753348-395e5400-cc85-11e8-941c-15aaeda95011.png)

**Comment by torch2424** [comment]
Was just about to report this myself, this would also close #339

This would need to add a `package-lock.json` matching the `yarn.lock` 😄

**Comment by nicholasess** [comment]
The issue will close, because doesn't have the reply from the owner
