### ISSUE TITLE
Netlify deploy guide doesn't mention SPA rewrite rules, so by default linking into docz is not working

### ISSUE THREAD

**Issue by capaj** [pedronauck/docz#409]
## Bug Report

*Deploy guide doesn't mention SPA rewrite rules, so by default linking into docz is not working*

would be nice to mention you need to add a rewrite rule like this one:

```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

**Comment by dlbnco** [comment]
Related to #257
