### ISSUE TITLE
Imported plugin not being resolved

### ISSUE THREAD

**Issue by marceloavf** [pedronauck/docz#41]
## Question

**Description**
I'm trying to import a plugin but it's not being compiled with docz and don't return any error even in debug mode. Should be something with the implementation or how i'm exporting it?

Importing: 
https://github.com/marceloavf/docz-plugin-vue/blob/master/examples/vue/doczrc.js

Plugin config that should return some error:
https://github.com/marceloavf/docz-plugin-vue/blob/master/packages/docz-plugin-vue/src/index.ts

Thanks!

**Comment by pedronauck** [comment]
I sent you a dm on twitter about that @marceloavf ✌️
