### ISSUE TITLE
`order` field is ignored when `menu` is specified

### ISSUE THREAD

**Issue by sw-yx** [pedronauck/docz#414]
## Bug Report

**Describe the bug**

`order` field is ignored when `menu` is specified

**To Reproduce**

see https://github.com/sw-yx/fresh-concurrent-react/tree/docz
deployed at https://concurrent-react.netlify.com/

![image](https://user-images.githubusercontent.com/6764957/47033999-2dbad380-d144-11e8-9dac-22d7c2ce3e82.png)

when i add an `order` key to my docs in the api section, nothing moves around

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

`order` should be respected inside menu, and should go in ascending order

**Comment by kylealwyn** [comment]
@pedronauck Would you mind expanding a little more on that? What is the recommended way to order the menu now? I see this: http://feedback.docz.site/roadmap/p/managing-menu-order-on-doczrc but that new configuration option isn't in the documentation

**Comment by sw-yx** [comment]
yeah its ok to deprecate `order` but then how do i set the menu order haha

**Comment by kylealwyn** [comment]
I've tried using the new `menu` config option like so, but moving the options around in any order does not affect menu layout as desired.

```
// doczrc.js

export default {
...
menu: [['Introduction'], ['Guides', ['Theming']], ['Components', ['Grid']]],
...
}

**Comment by sag1v** [comment]
@kylealwyn Same here with this syntax:
```
menu: [
    "Getting started",
    "Examples",
    [
      'event',
      'ref',
      'on & off',
      'multiple events',
      'preventDefault'
    ]
  ]
```

I think the documentation for this feature is quite confusing.

**Comment by sag1v** [comment]
@kylealwyn I was able to finally get it working as expected.  
I'm not sure how exactly you want to order your menu but in your case i think it needs to be something like that: 

```
export default {
  menu: [
    'Introduction', // auto ordered menu "Introduction"
    {
      name: 'Guides', // manually oredered menu "Guides"
      menu: ['Theming'] // oredered items for "Guides"
    },
    {
      name: 'Components',  // manually oredered menu "Components"
      menu: ['Grid'] // // oredered items for "Components"
    }
  ]
}
```

**Comment by Primir** [comment]
Sorry for inconvinience,
AlpineSunGreetz, Primir
