### ISSUE TITLE
vendor.js is very big

### ISSUE THREAD

**Issue by danielberndt** [pedronauck/docz#415]
I've just managed to deploy my docs under https://react-sticky-box.codecks.io/ and I am very happy with the result!

However I was really surprised when I found that loading the page required to fetch 1.6MB worth of javascript. Yes, it's less if it's gzipped but I feel we could do better here. Without having really looked at the source, I assume that the largest chunk stems from the Playground which probably includes a whole babel pipeline. Is it maybe worth to code-split this part out and only import it, once the user starts interacting with the editor?

**Comment by danielberndt** [comment]
I just ran the resulting bundles through the `webpack-visualizer-plugin` to look at what's inside. And it seems like codemirror is the biggest contributor to file size. Followed by `buble`, `js-beautify`, `core-js` and `acorn`.
![screen shot 2018-10-17 at 13 40 56](https://user-images.githubusercontent.com/856386/47083895-514c4f80-d212-11e8-80d0-c8ec0ab02188.png)

This is the underlying [html file](https://github.com/pedronauck/docz/files/2487179/stats.html.zip) with the full stats. 

Unfortunately I don't know the architecture of docz that well to know how to easily improve this. But I assume that the biggest win would be to precompile all the pages (as seems to be [planned](https://docz.canny.io/roadmap/p/static-build-based-on-generated-routes)) and only load codemirror and it's dependencies if the user starts interacting with the editor. But I guess this also largely depends on how well codemirror supports a use case like this.

**Comment by danielberndt** [comment]
Maybe it's worth looking into [react-live](https://github.com/FormidableLabs/react-live). Their sample page requires only ~430KB of (unzipped) javascript and they seem to offer SSR.

**Comment by nicholasess** [comment]
@danielberndt we know that the build is very big, but now it isn't focus for us. 

Could you please create a item in roadmap? We receive PR too

Thanks!

http://feedback.docz.site/

**Comment by danielberndt** [comment]
Alright. Created an item here: http://feedback.docz.site/roadmap/p/decrease-size-of-javascript-assets
