### ISSUE TITLE
Option to hide sidebar/leftnav/TOC?

### ISSUE THREAD

**Issue by ncknuna** [pedronauck/docz#417]
First of all, awesome work on docz!

I'd like to use docz as a way to demo larger content/components to external stakeholders, who may find the left nav to be distracting. It would be great if there was some way to hide it. Of course, I can always implement something myself using some CSS, but a built-in would be nice :)

If this is something you're open to a PR for, I'd be happy to give it a shot if you point me to how/where you'd like it to be implemented!

**Comment by pedronauck** [comment]
Hi dude, can you add this suggestion on [our roadmap](http://feedback.docz.dev/roadmap)?

**Comment by ncknuna** [comment]
Totally! Done: http://feedback.docz.site/roadmap/p/option-to-hide-sidebarleftnavtoc
