### ISSUE TITLE
issue when installing through NPM

### ISSUE THREAD

**Issue by grantglidewell** [pedronauck/docz#42]
## Bug Report

When installed through NPM the  script refuses to run, reporting that its unable to find a webpack module. When installing through Yarn it works as described in the docs

**To Reproduce**

1. run 'npm i -D docx' in project directory
2. add 'docz dev' script to package.json
3. run dev script
4. see glorious broken output

```shell
module.js:549
    throw err;
    ^

Error: Cannot find module 'webpack/schemas/WebpackOptions.json'
```

**Expected behavior**

NPM and Yarn should behave the same

**Enviroment**

* OS: OSX 10.13.4
* Node/npm version: npm 6.1.0

**Comment by Swapnull** [comment]
I have just tried creating a project and followed your steps and it seems to work fine. See Below.

Are you doing this on an existing or empty project? Do you have any further setup in terms of `doczrc.js` files or anything? 

<img width="1440" alt="screen shot 2018-06-14 at 20 17 28" src="https://user-images.githubusercontent.com/4456346/41433206-1a003028-7010-11e8-96e7-11ac72c43b6c.png">

**Comment by grantglidewell** [comment]
I used existing projects and created a fresh project to test this before making the issue. it's possible that it comes down to something strange in my local environment. I can check on another machine entirely, and will create another issue with more detail if it's something I can reproduce without that possibility.

**Comment by edwilliams** [comment]
having same issue installing with npm (following @grantglidewell's steps above with existing project)

```shell
module.js:540
    throw err;
    ^

Error: Cannot find module 'webpack/schemas/WebpackOptions.json'
```
