### ISSUE TITLE
Use vanilla HTML without JS components

### ISSUE THREAD

**Issue by Dobby89** [pedronauck/docz#43]
Is it possible to use docz without importing JS components and instead just use basic HTML?

I currently have a `hello.mdx` file which looks like the following:

```
---
name: Hello World
---

import { Playground } from 'docz'

# Hello
<Playground components={{}}>
    <h1>Hello</h1>
</Playground>
```
I run `yarn docz dev` and get the following error:
```
ERROR  Failed to compile with 1 errors

This dependency was not found:
* srcdocuttons.mdx in ./.docz/app/imports.js
To install it, you can run: npm install --save srcdocuttons.mdx
```
System specs:
- Windows 7
- Node v8.9.3
- Yarn v1.7.0
- docz v0.2.4

**Comment by marceloavf** [comment]
Probably related to #12

**Comment by lwxyfer** [comment]
I want to just use basic HTML like below. 

```
---
name: Hello World
---

import { Playground } from 'docz'

# Hello

<h1>test here</h1>
```

But the full page render badly. (no error, no waring)
