### ISSUE TITLE
Add netlify _redirects file

### ISSUE THREAD

**Issue by hilquias-kil** [pedronauck/docz#430]
### What’s the problem?

The client-side router control. When you refresh a page whose path is not /. Then, you hit the 404 wall. Which is just a blank page.

### The solution:

Add `_redirects` file to the `dist` folder, in order to redirect to the index.html file, so the routers can work properly in the Netlify.

`/*    /index.html   200`

https://www.netlify.com/docs/redirects/#rewrites-and-proxying

There are other solutions, if you guys do not like this one.

**Comment by nicholasess** [comment]
@hilquias-kil I created a plugin to resolve the problem

https://github.com/nicholasess/docz-plugin-netlify

thanks

**Comment by hilquias-kil** [comment]
Thanks @nicholasess.

**Comment by klappy** [comment]
The main documentation guides everyone to deploying with Netlify, can that be updated to point to a fix? There doesn't appear to be a section in the documentation to help users find this plugin. 

Thanks @nicholasess for creating a fix for this issue. Does this still work with rc.8 and 1.0.0 release? When using it, the dev server doesn't appear to render anymore with react-hot-loader errors.

I'll try writing my own post build script for the package.json. That way it doesn't have to be updated with releases of Docz as often.
