### ISSUE TITLE
Customizable tabs in playground 

### ISSUE THREAD

**Issue by joeljeske** [pedronauck/docz#435]
(I didn't see it in your roadmap, so I am proposing it here.)

I think it would be very useful and flexible to allow the default theme to support customizable tabs in the playground. You recently added the "<> show editor" button which shows the drop down and then you can navigate between the JSX or HTML. I think it would also be useful to allow projects or instances of a Playground to create additional right-hand side buttons like "show editor" and that would then show a drop down panel like the code panel and/or expose left hand buttons to toggle the content panel. 

If this flexibility existed, the eco-system could provide a "knobs" plugin tab without needing to add this to the default theme by default.

If you are interested, I am wanting to create a tab that would show a set of "checks" or verifications for the current code snippet and running example. I want to run snap-shot tests on the JSX tree, and I want to run an A11y check. By being able to implement these checks here, I am not forced to duplicate all my examples in docs and in unit tests. FWIW, I think the ability to run customizable "checks" on the playground example would be useful to have in Docz default theme as well, but it seemed more likely that you guys might be more open to welcoming customizable tabs such that the ecosystem could provide plugins like this. 

If my ideas pleases you, I am very open to contributing some PRs working toward this goal. 

Thanks!

**Comment by TrilipuT** [comment]
Also interested in this functionality.
I have only found that you can add `codeSandbox: false` in `doczrc.js` and it will disable Sandbox tab in the playground.

**Comment by pedronauck** [comment]
Hey @joeljeske, please, can you add your suggestion on [our roadmap](http://feedback.docz.site/roadmap)?
