### ISSUE TITLE
How to configure menu on doczrc.js

### ISSUE THREAD

**Issue by mariusespejo** [pedronauck/docz#436]
## Question

**Description**
It seems that #322 was released but there is barely any documentation on usage. If you were trying to look for how to order the docs like I was, you might end up in a couple issues that ultimately leads you to this page: http://feedback.docz.site/roadmap/p/managing-menu-order-on-default-theme

There is an image on that page for how to configure it but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/5385443/47929608-c19bd780-de86-11e8-91bb-0d9b90ad4657.png)

Looking at #322 there is an example on there given by @mpivaa
Like 
```
export default {
  menu: [
    'Getting Started',
    {
      name: 'Components',
      docs: [
        'Alerts',
        'Button',
        ...
      ],
    }
  ]
}
```
I have not been able to get that to work either. 
It's also not clear, the strings provided in the `docs` array of the object, is that the name of the mdx file? Is that the name property added to the top of the file??
Like
```
---
name: Button
---
```

Could someone clarify with examples? Or even better add it to the official docs? 

At the moment for me configuration like this:
```
menu: [
    'Introduction',
    {
      name: 'Getting Started',
      docs: [
        'Button'
      ],
    }
  ]
```

just comes out as a flat structure:
![image](https://user-images.githubusercontent.com/5385443/47929935-ada4a580-de87-11e8-8415-7c2521d2ea4e.png)

Thanks for your time.

**Comment by pedronauck** [comment]
You can see how configure menu in the [release link](https://github.com/pedronauck/docz/releases/tag/v0.12.4). I didn't have time to update docs yet 😕

**Comment by adekunleoduye** [comment]
I'm still having trouble with menu order feature. @pedronauck is there an example of this being implemented successfully?

I've tried every method out hear and still no luck.

**Comment by mariusespejo** [comment]
@pedronauck can we keep this issue open until it is officially documented? The intent of the issue to begin with is that a user trying to figure out how to do this is left with nothing but to dig through these various wrong examples... having it officially documented would open it up for more folks to know it is supported and to test it with the given docs

**Comment by bitworking** [comment]
The menu config seems to be broken in the newest version.

An external link show up with a arrow down icon and is not clickable.
Submenu reordering gives this error: TypeError: array-sort expects an array.

My config:

menu: [
    'Introduction',
    'Components',
    'Plugins',
    { name: 'Plugins', menu: ['Plugins1', 'Plugins2', 'Plugins3'] },
    'Instructions',
    { name: 'Github', href: 'https://github.com/' },
  ],
