### ISSUE TITLE
htmlContext applies head.raw to the body

### ISSUE THREAD

**Issue by walkerrandolphsmith** [pedronauck/docz#439]
## Bug Report

**Describe the bug**

Given the following `htmlContext`:

```
export default {
  htmlContext: {
    head: {
      raw: [`<svg><symbol id="myDot" width="10" height="10" viewBox="0 0 2 2"><circle cx="1" cy="1" r="1" /></symbol></svg>`]
    }
  }
};
```

The value supplied to `htmlContext.head.raw` is aded to the document's `body`. Similar to #248, however the change to https://github.com/pedronauck/docz/pull/255/files#diff-2a1affb35d37591201b01ee14eb6572dL32 does not seem to be relevant. Both an array and a string used for `htmlContext.head.raw` produce the same result.

*A clear and concise description of what the bug is.*

I tried adding a SVG to the `head` of the document using `htmlContext` and found it is applied to the body.

**To Reproduce**

1. Clone the repo, install dependencies, and start the dev server
    ```
    clone git@github.com:walkerrandolphsmith/docz-example-issue.git \
        && cd docz-example-issue \
        && npm i --no-progress --silent \
        && npx docz dev
    ```
2. Navigate to localhost:3000 in your browswer
3. Your page source or open dev tools
4. Observe `<svg><symbol id="myDot" width="10" height="10" viewBox="0 0 2 2"><circle cx="1" cy="1" r="1" /></symbol></svg>` in the body (it is expected in the head)

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

https://github.com/walkerrandolphsmith/docz-example-issue

**Expected behavior**

*A clear and concise description of what you expected to happen..*

I expected the SVG tag mentioned to exist in the `head` and not in the `body`.

**Environment**

* Windows and Mac OSX
* Node 8.11.1
* npm 5.6.0

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/1386741/48142011-f9858f00-e279-11e8-81f7-5484ac24496c.png)

**Comment by pedronauck** [comment]
Hi dude, try to update the version of Docz, this will be fixed 🙏
