### ISSUE TITLE
CLI webpack happypack doesn't respect SIGINT

### ISSUE THREAD

**Issue by transitive-bullshit** [pedronauck/docz#442]
## Bug Report

If you run `docz:dev` on a repo with a large number of source files, allow it to fully compile, then make a small edit to a source file which kicks off docz's hot reloading, them control+C the docz cli process to kill it, the underlying [happypack](https://github.com/amireh/happypack) webpack compilation processes should all get killed as well, but they don't and continue to take up heavy CPU+RAM while printing to the original stdout+stderr.

The codebase I'm reproducing this on is private, but it contains ~6k source files and recompilation taking upwards of a minute.

**To Reproduce**

1. Run docz:dev on a larger codebase
2. Allow it to compile
3. Trigger hot reload by editing a file
4. control+C the docz cli (sends SIGINT to the docz cli process)
5. docz cli process is killed due to the Node.js default SIGINT handler
6. observe that the subprocesses are still compiling and logging to stdout/err

**Expected behavior**

When you kill the docz CLI parent process, it should also properly kill and cleanup any children processes it has spawned.

**Environment**

* OS: macOS 10.13.6
* Node/npm version: node `v10.3.0`, yarn `v1.12.3`

**Comment by pedronauck** [comment]
Fixed on release [v0.12.10](https://github.com/pedronauck/docz/releases/tag/v0.12.10) ✅
