### ISSUE TITLE
unparseable filetype: .less for file 

### ISSUE THREAD

**Issue by liuzhiyang0113** [pedronauck/docz#444]
`Could not find dependency version for prop-types
Could not create Open in CodeSandbox Error: unparseable filetype: .less for file /Users/mac/Desktop/projects/framework/react-framework/src/common/components/calendar/calendar.module.less
    at loadRelativeFile (/Users/mac/Desktop/projects/framework/react-framework/node_modules/codesandboxer-fs/src/loadRelativeFile.js:78:13)`

**Comment by pedronauck** [comment]
Fixed on release [v0.12.10](https://github.com/pedronauck/docz/releases/tag/v0.12.10) ✅

**Comment by szymkab** [comment]
@pedronauck I have the same error but for `.scss`, is it known issue or it should work fine?

**Comment by pedronauck** [comment]
Oh, for sure, I forgot about the `.scss` extension on uploading files to codesandbox. I'll add this extensions and release some path 🙏

**Comment by szymkab** [comment]
Thanks!

**Comment by pedronauck** [comment]
I'm releasing the patch now @szymkab

**Comment by krvajal** [comment]
In which version was this issue solved. I still get the error
`could not find dependency version for ` when using sass files. The error seems to be originated from `codesandbox-fs/src/loadFiles`

**Comment by kivervinicius** [comment]
me too @krvajal
