### ISSUE TITLE
can not run 

### ISSUE THREAD

**Issue by liuzhiyang0113** [pedronauck/docz#449]
This dependency was not found:

* /Users/mac/Desktop/study/mdx/mdx/react-framework/.docz/app/index.jsx in multi ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx, mult
i webpack-hot-client/client?6731d2ca-ad60-4d8d-9f75-d5d276c34a2f ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx

To install it, you can run: npm install --save /Users/mac/Desktop/study/mdx/mdx/react-framework/.docz/app/index.jsx

**Comment by liuzhiyang0113** [comment]
it throw an error when i delete .docz

**Comment by transitive-bullshit** [comment]
I would recommend:

```bash
rm -rf .docz node_modules
```

Then `npm install` or `yarn install` and retry.

For these types of issues, please always include node version, npm/yarn version, and the verbose output of running docz.

**Comment by liuzhiyang0113** [comment]
I forgot it，sorry.

node@8.11.3
npm@5.6.0
yarn@1.9.4

It works before I use `indexHtml: './src/docz.html'` ,but after ，the page is blank , so i delete `.docz` and use `yarn docz dev` ,  `npm` throw an error 

```
 ERROR  Failed to compile with 2 errors                                                                                                        
This dependency was not found:

* /Users/mac/Desktop/study/mdx/mdx/react-framework/.docz/app/index.jsx in multi ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx, mult
i webpack-hot-client/client?ef3d54ff-4c71-46b5-be0d-7e0806c2b5cc ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx

To install it, you can run: npm install --save /Users/mac/Desktop/study/mdx/mdx/react-framework/.docz/app/index.jsx

```

**Comment by pedronauck** [comment]
Hey guys, try to delete your node_modules and install it again. Then, re run the docz, can be happening because the last release 🙏

**Comment by krzysztofzuraw** [comment]
@pedronauck I've tried (I also removed `.docz`) folder - the problem still occurs

**Comment by pedronauck** [comment]
@krzysztofzuraw which version do you're using?

**Comment by krzysztofzuraw** [comment]
I've just updated to the newest - `0.12.12` and it fixed the issue - thank you 👏
