### ISSUE TITLE
Uncaught TypeError: cannot read property 'pre' of undefined

### ISSUE THREAD

**Issue by mengera88** [pedronauck/docz#45]
Is it related to the use of typescript?
error message:
Uncaught TypeError: Cannot read property 'pre' of undefined
    at __webpack_exports__.default (button.mdx?a2b0:9)
    at ProxyFacade (react-hot-loader.development.js?c2cb:670)
    at mountIndeterminateComponent (react-dom.development.js?61bb:13272)
    at beginWork (react-dom.development.js?61bb:13711)
    at performUnitOfWork (react-dom.development.js?61bb:15741)
    at workLoop (react-dom.development.js?61bb:15780)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:138)
    at invokeGuardedCallback (react-dom.development.js?61bb:187)
    at replayUnitOfWork (react-dom.development.js?61bb:15194)
__webpack_exports__.default @ button.mdx?a2b0:9
Component @ react-hot-loader.development.js?c2cb:670
mountIndeterminateComponent @ react-dom.development.js?61bb:13272
beginWork @ react-dom.development.js?61bb:13711
performUnitOfWork @ react-dom.development.js?61bb:15741
workLoop @ react-dom.development.js?61bb:15780
callCallback @ react-dom.development.js?61bb:100
invokeGuardedCallbackDev @ react-dom.development.js?61bb:138
invokeGuardedCallback @ react-dom.development.js?61bb:187
replayUnitOfWork @ react-dom.development.js?61bb:15194
renderRoot @ react-dom.development.js?61bb:15840
performWorkOnRoot @ react-dom.development.js?61bb:16437
performWork @ react-dom.development.js?61bb:16358
performSyncWork @ react-dom.development.js?61bb:16330
requestWork @ react-dom.development.js?61bb:16230
scheduleWork$1 @ react-dom.development.js?61bb:16096
enqueueSetState @ react-dom.development.js?61bb:11185
Component.setState @ react.development.js?72d0:273
n.safeSetState @ index.m.js?4320:1
(anonymous) @ react-hot-loader.development.js?c2cb:582
(anonymous) @ index.m.js?4320:1
Promise.then (async)
n @ index.m.js?4320:1
n @ VM6155:5
constructClassInstance @ react-dom.development.js?61bb:11333
updateClassComponent @ react-dom.development.js?61bb:13036
beginWork @ react-dom.development.js?61bb:13715
performUnitOfWork @ react-dom.development.js?61bb:15741
workLoop @ react-dom.development.js?61bb:15780
renderRoot @ react-dom.development.js?61bb:15820
performWorkOnRoot @ react-dom.development.js?61bb:16437
performWork @ react-dom.development.js?61bb:16358
performSyncWork @ react-dom.development.js?61bb:16330
interactiveUpdates$1 @ react-dom.development.js?61bb:16597
interactiveUpdates @ react-dom.development.js?61bb:2150
dispatchInteractiveEvent @ react-dom.development.js?61bb:4528
react-dom.development.js?61bb:14113 The above error occurred in the <Component> component:
    in Component (created by Component)
    in div (created by Styled(div))
    in Styled(div) (created by Render)
    in Render (created by Playground)
    in Playground (created by Component)
    in div (created by Component)
    in Component (created by Component)
    in Component (created by Component)
    in Component (created by n)
    in n (created by t)
    in div (created by Styled(div))
    in Styled(div) (created by Page)
    in div (created by Styled(div))
    in Styled(div) (created by Page)
    in Page (created by t)
    in t
    in t
    in DocPreview
    in div (created by Styled(div))
    in Styled(div) (created by Main)
    in Main
    in t
    in ThemeConfig (created by Theme)
    in Theme (created by DoczTheme)
    in DefaultWrapper (created by DoczTheme)
    in t (created by t)
    in t (created by DoczTheme)
    in DoczTheme (created by Root)
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.

**Comment by lorem--ipsum** [comment]
I just faced the same issue and it turns out I needed to run docz with the `--typescript` flag as follows (I'm using npm) :

`docz dev --typescript`

**Comment by good-idea** [comment]
I was getting this error when I had a typo in my import statement at the top of my `.mdx`. It took a while to figure out.

Docz has been pretty great considering how little config I need to take care of. But, when things break, it's difficult to find out what I've done wrong.

**Comment by pedronauck** [comment]
You're right @good-idea, unfortunately, has a lot of tricks to treat on docz, and we need asap improve error handlers 😢

**Comment by pedronauck** [comment]
Fixed on [v0.2.8](https://github.com/pedronauck/docz/releases/tag/v0.2.8)
