### ISSUE TITLE
Fonts in docs not like on example

### ISSUE THREAD

**Issue by popugang** [pedronauck/docz#451]
## Bug Report

Fonts in docs not like on example

example
![image](https://user-images.githubusercontent.com/19804652/48560938-f46eb280-e8ff-11e8-8731-d78ad2c2c913.png)

im my project 

![image](https://user-images.githubusercontent.com/19804652/48560965-02bcce80-e900-11e8-99e6-10b0b282ff9d.png)

**Comment by pedronauck** [comment]
Yes, we change the title font. If you don't like it, you can change it on your `doczrc.js`:

```js
export default {
  themeConfig: {
    styles: {
      h1: {
        fontFamily: 'Your font here',
      }
    }
  }
}
```
