### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by ChuksFestus** [pedronauck/docz#454]
after running docz build i get a dist folder in .docz is that what i'm supposed to host? cos when i ran it, I got a blank page

**Comment by jedrichards** [comment]
Yes, the `.docz/dist` folder contains the build output. It's a static site with an `index.html` in it. It won't work just opening `index.html` in a browser, you need to serve it with a web server.

**Comment by ChuksFestus** [comment]
yeah i hosted it with now and got the same result: https://docz-wwrmllyirk.now.sh/dist/

**Comment by jedrichards** [comment]
If I open your site and look at the network activity in Chrome Dev Tools I'm getting a bunch of 404 for all the JS file Docz generates. Did you make sure to deploy the entire contents of the `dist` folder?

**Comment by ChuksFestus** [comment]
yeah even when i run it locally with a local server i get the same thing

**Comment by ChuksFestus** [comment]
oh fixed now... i actually deployed the .docz folder and the navigated to dist/... so right now i just deployed dist/ dicrectly

**Comment by jaikiratsingh** [comment]
Is there any way to make it into a static build, instead of making dynamic calls to each component that I load. I want it to be static, i.e. no network calls.

**Comment by jedrichards** [comment]
It is already a static build. A static build doesn't mean no network calls, it means it can be served with a basic static file server. Sounds like what you're after is a version that doesn't do any code splitting, and you get the whole app with the first request? I don't think that's supported.

What's your use case? You need network connectivity to make the first request, so what's the problem with the subsequent ones?
