### ISSUE TITLE
`indexHtml` is not working

### ISSUE THREAD

**Issue by liuzhiyang0113** [pedronauck/docz#457]
`indexHtml` is not working....

i use `indexHrml: './index.html'`

`index.html` is in the root directory,and it includes:
```
<!DOCTYPE html>
<html lang="{{ lang }}">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    {{ head }}
    <link rel="stylesheet" href="./index.css">
  </head>
  <body>
    <div id="root" />
    {{ footer }}
  </body>
</html>
```

`indexHtml` is not working for me.

**Comment by liuzhiyang0113** [comment]
sorry , i misspelled it.  But i link `.css` in `./index.html`, i get 404.

`index.html`:

```
<!DOCTYPE html>
<html lang="{{ lang }}">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    {{ head }}
    <link rel="stylesheet" href="{{ publicUrl }}/index.css">
  </head>
  <body>
    <div id="root" />
    {{ footer }}
  </body>
</html>
```

`Elements`:
```<link rel="stylesheet" href="/index.css">```

```<link rel="stylesheet" href="{{ publicUrl }}/index.css">```  ==>  ```<link rel="stylesheet" href="/index.css">```



 i get 404.

 directory:
![1542678830939](https://user-images.githubusercontent.com/22534145/48746411-3b66fa00-ecaa-11e8-8a5f-be81c847f36c.jpg)

**Comment by pedronauck** [comment]
Since [v0.12.10](https://github.com/pedronauck/docz/releases/tag/v0.12.10) if you want to add static assets in a public folder, you need to put it inside the `/public`, or you can set a custom public directory on your doczrc. Please, see the release to know more about that.

**Comment by liuzhiyang0113** [comment]
yes，I saw it, but it work in `yarn docz build` , not work in `yarn docz dev`
