### ISSUE TITLE
Applying styles for root tag

### ISSUE THREAD

**Issue by w0wka91** [pedronauck/docz#464]
## Question

I like to use rem in my css to increase the accessibility, so I always set the html font-size to 62.5% in order that 1rem equals 10px. Is there any way to set the font-size for the root tag in the themeConfig?

**Comment by danielbayerlein** [comment]
You can change it on your `doczrc.js`. For example:

```javascript
export default {
  themeConfig: {
    styles: {
      playground: {
        fontSize: 'Your font size here'
      }
    }
  }
}
```

**Comment by w0wka91** [comment]
That's not working because rem values are always relative to the root html element.

**Comment by danielbayerlein** [comment]
Ah I understand - sorry! Maybe you can inject the global styling like https://github.com/pedronauck/docz/blob/master/packages/docz-theme-default/src/styles/global.ts

**Comment by w0wka91** [comment]
No worries. I'm not sure where to inject the global style(Component/Class/File)

**Comment by w0wka91** [comment]
Got it now. Created a wrapper component
`import React from 'react'
import { injectGlobal } from 'emotion'
import globalStyle from './utils/globalStyle'

injectGlobal(globalStyle)

interface Props {
  children: React.ReactNode
}

function DoczWrapper({ children }: Props) {
  return <div>{children}</div>
}

export default DoczWrapper;`

and specified it in the `doczrc.js` like this:
`module.exports = {
  title: 'React Atoms',
  typescript: true,
  wrapper: 'src/DoczWrapper.tsx',
}
`

**Comment by danielbayerlein** [comment]
Thank you for sharing your solution.

**Comment by drewlustro** [comment]
Yes, thank you for sharing this solution. It should definitely be in the docs for docz!
