### ISSUE TITLE
I can't get the theme config logo config to work

### ISSUE THREAD

**Issue by enzoferey** [pedronauck/docz#469]
## Question

**Description**
In the [default theme README](https://github.com/pedronauck/docz/tree/master/packages/docz-theme-default) it states:

```js
// doczrc.js
export default {
  themeConfig: {
    logo: {
      src: '/path/of/my/logo',
      width: 150
    }
  }
}
```

I have tried with all kind of absolute and relative paths and I can't manage to display my logo. I guess it's because it doesn't get bundled ?

My logo is located at `./src/logo.svg` and my `doczrc.js` looks like this:

```js
export default {
    src: "./src",
    ...
    themeConfig: {
       ...
        logo: {
            src: "./logo.svg",
            width: 150
        }
    },
};
```

Thank you for your help ! 😄

**Comment by nicholasess** [comment]
@enzoferey Could you try with png? If the error happens, we investigate the problem

**Comment by enzoferey** [comment]
Same for PNG...

What I don't really understand is where and how the image gets bundled. Because in the theme side it's a webpack configuration that doesn't have any image rule. It just takes the image src provided in the config and sets a `<img>` with it as its src attribute. That basically means later when the docs are built if the path is "./logo.png" it will try to fetch it at `localhost/logo.png`, and as far as I know the routes are reserved for pages, not assets (how is it suposed to find it if I create a logo.mdx for example ?).

**Comment by enzoferey** [comment]
Got a solution 🎉 

Thanks to [this comment](https://github.com/pedronauck/docz/issues/39#issuecomment-440577061) I learnt that Docz supports a `public` folder, so my config now looks like this:

```js
export default {
  src: "./src",
  public: "./src/public",
  ...
  themeConfig: {
     ...
      logo: {
          src: "/public/logo.svg",
          width: 150
      }
   },
};
```

It works great ! I feel like the documentation of the default theme should be updated to either a working solution without using `public` folder (I don't know of any) and this `public` folder thing should be documented in the main package.

I can't really find any page on the website where configs like `public` or `htmlContent` are documented. I would like to do it, but where should it be placed ?

**Comment by pedronauck** [comment]
Hi @enzoferey, you can send us a pull request on https://github.com/pedronauck/docz-website

**Comment by enzoferey** [comment]
Hi @pedronauck ! 

Sure, I can do that, however I feel like there have been many recent changes on configurations that are not reflected anywhere in the docs... Is there any other way than just looking at the source code and go throughout every roadmap page to know all the configurations settings currently supported ?

**Comment by pedronauck** [comment]
For sure @enzoferey, has a description on [each release](https://github.com/pedronauck/docz/releases) with that information. You can get see on that maybe which is in the documentation and which isn't.

**Comment by JulienDemarque** [comment]
Seems the public folder thing is still not properly documented... I had to came here to find the solution. Any update to the documentation soon?

**Comment by prestonneal** [comment]
> For sure @enzoferey, has a description on [each release](https://github.com/pedronauck/docz/releases) with that information. You can get see on that maybe which is in the documentation and which isn't.

I would think you would want to keep your own documentation up-to-date.

**Comment by prestonneal** [comment]
> Seems the public folder thing is still not properly documented... I had to came here to find the solution. Any update to the documentation soon?

Yea.  I would think they would want to keep their own documentation up-to-date.

**Comment by prestonneal** [comment]
> Seems the public folder thing is still not properly documented... I had to came here to find the solution. Any update to the documentation soon?

Yea.  I'd like to think they would want to keep their own documentation up-to-date.

**Comment by prestonneal** [comment]
> Seems the public folder thing is still not properly documented... I had to came here to find the solution. Any update to the documentation soon?

Yea.  I'd like to think they would keep their documentation up-to-date. Especially if they were aware of information that is missing.
