### ISSUE TITLE
Allow components / mdx files in node_modules folder to be imported

### ISSUE THREAD

**Issue by AshConnolly** [pedronauck/docz#470]
I have components in my project that are pulled in via node_modules. Docz allows you to specify a folder where MDX files are located, such as:
```
// doczrc.js
export default {
  src: "./test"
}
```
However when targeting the node_modules folder it doesn't appear to work. I'm not sure if this is a bug or by design. The docs don't state that node_modules is off limits so I presume its a bug.

Cheers! 😀

**Comment by pedronauck** [comment]
For sure, get some files from `node_modules` is possible just as common modules to import, isn't possible to transpile then since they should be transpiled yet. This is not a good practice I think, import files not transpiled from `node_modules`.

**Comment by AshConnolly** [comment]
Hi @pedronauck! Thanks for the quick response!
So the issue is that the modules are not transpiled yet? Would it be possible to transpile them? How difficult would that be? If I could use node_modules docz would be a brilliant for my purposes. 

I've worked at a couple of places have react components as individual node modules as it makes the UI easier to keep track of. I think it would be a very worthwhile feature, particularly for larger organisations.

**Comment by AshConnolly** [comment]
I could potentially make a script that copies the node_modules I need into the src folder, but I'd ideally rather be able to target them directly from doczrc.js.

**Comment by pedronauck** [comment]
As I told you, it's a bad practice transpile files for `node_modules`, mainly for webpack. This can imply in a bunch of unnecessary files transpiled. Imagine the performance impact. I think that this is not a good thing to support inside docz and not even in any project. When you publish some package to npm, the published version of your package needs to be built and minified.

**Comment by AshConnolly** [comment]
oh sorry mate, I dont want to transpile all node_modules, that would be awful for performance! I want to transpile specific modules in my node_modules folder, for example 
```
export default {
  src: ["./src", "./node_modules/my-component"]
}
```
That would import all MDX in src and all MDX in my-component, which is in node_modules.

Would that be possible? Apologies for the confusion! 😀

**Comment by pedronauck** [comment]
I got, you can use `modifyBundlerConfig` to modify and include this folder at include option for webpack module rules.

**Comment by AshConnolly** [comment]
Very late reply @pedronauck! 
Thanks for that mate! I had a read of https://www.docz.site/documentation/creating-plugins, but cant see how I would include a node module folder for webpack?
Can you point me in the right direction?
Appreciate the help, cheers! 😀

**Comment by pedronauck** [comment]
You need to access the specific loader that you want to include the folder, then add it. I think that use `onCreateWebpackChain` can be easier for that:

```js
export default {
  onCreateWebpackChain: config => {
    config.module.rule('js').include.add('/path/to/your/folder')
  }
}
```
