### ISSUE TITLE
why 'html' tag add a className 'with-overlay' ?

### ISSUE THREAD

**Issue by zWingz** [pedronauck/docz#476]
## Question

**Description**
![image](https://user-images.githubusercontent.com/13031838/49128190-325ad600-f305-11e8-96fe-cdbad88fc34c.png)

it will set `with-overlay` when `window.innerWidth < 1118`, but it will not remove when `window.innerWidth > 1118`

*Give more information about your doubt*

i don't know why set `hidden` in `html`

[basic demo](https://github.com/pedronauck/docz/tree/master/examples/basic) have same issus

**Comment by nathunsmitty** [comment]
I'm also experiencing this issue with docz 0.12.13

**Comment by pedronauck** [comment]
Fixed on [v0.12.14](https://github.com/pedronauck/docz/releases/tag/v0.12.14) ✅
