### ISSUE TITLE
Dependency was not found on 0.12.13

### ISSUE THREAD

**Issue by hiepndd** [pedronauck/docz#477]
## Bug Report
Can't import component in component 
**Describe the bug**

-  the docz dev is failed, docz build also failed too.

**To Reproduce**
1. run docz dev
2. See error
This dependency was not found:
 @/components/Link in ./src/components/AddButton/index.js
To install it, you can run: npm install --save @/components/Link
**Environment**

- OS: Mojave
- Node: 10.11
- Yarn: 1.9.4

**Additional context/Screenshots**

- docz dev with --debug

ERROR in ./src/components/AddButton/index.js
Module not found: Error: Can't resolve '@/components/Link' in '/Users/hiepnguyen/Dev/front-end/fortress/src/components/AddButton'
 @ ./src/components/AddButton/index.js 23:0-37 32:29-33
 @ ./src/components/AddButton/index.mdx
 @ ./.docz/app/imports.js
 @ ./node_modules/docz/dist/index.m.js
 @ ./node_modules/docz-theme-default/dist/index.js
 @ ./.docz/app/root.jsx
 @ ./.docz/app/index.jsx
 @ multi ./node_modules/@babel/polyfill/lib/index.js ./.docz/app/index.jsx

**Comment by nicholasess** [comment]
@hiepndd Are there someone alias called ```@/components/Link``` in webpack?

**Comment by hiepndd** [comment]
Hi @nicholasess 
Of course, added before.

**Comment by hiepndd** [comment]
Hi @nicholasess 
please help me :thinking_cry:

**Comment by pedronauck** [comment]
Hey @hiepndd, can you create a repo with the minimal setup for you bug?

**Comment by nicholasess** [comment]
@hiepndd I was understand your scenary, because i mean that error is why you don't use resolve.alias in .doczrc with modifyBundlerConfig.



Like a
```
export default {
  modifyBundlerConfig: (config) {
     config.resolve.alias = {...config.resolve.alias, ...{
       "@/components": path.join(...., "src/components")
     }}
  }
}
```

The webpack config from docz doens't see the webpack config from your project, you need to link in  modifyBundlerConfig

**Comment by pedronauck** [comment]
I'll close this since the too delayed answer :)
