### ISSUE TITLE
React / HTML Toggle in Playground

### ISSUE THREAD

**Issue by phildebrandt** [pedronauck/docz#478]
## What happened to the React / HTML toggle in Playground?

![image](https://user-images.githubusercontent.com/2347265/49165712-d477bf80-f2ff-11e8-8dca-70364728872d.png)

There used to be a toggle here to switch between React/JSX and HTML in the Playground component on version `0.12.11`. Did this get removed, or is there some setting that I'm missing to have it show up?

**Comment by nicholasess** [comment]
@phildebrandt Before everything, could you please update version to `0.12.3`? If the error continues, let me know.

thanks

**Comment by phildebrandt** [comment]
@nicholasess Do you mean `0.12.13`? If so, I should have clarified that's the version I'm currently on. The last time it worked for me was on `0.12.11`.

**Comment by pedronauck** [comment]
We were having a lot of trouble with the HTML and it was bloating the bundle, so, for now, I decided to remove this feature until finding a better way to develop it again.
