### ISSUE TITLE
Make docs generated responsive

### ISSUE THREAD

**Issue by merelinguist** [pedronauck/docz#49]
It would be nice if the docs were mobile-friendly, and it would give Docz a big win over Storybook, which is still not responsive either.

**Comment by marceloavf** [comment]
First we need to discuss which is the best approach to make the default theme responsive, there is some options: https://github.com/emotion-js/emotion/blob/master/docs/media-queries.md

**Comment by marceloavf** [comment]
🎉 This enhancement is now included in version 0.3.2 🎉

The release is available on:
- [npm package (@latest)](https://www.npmjs.com/package/docz)
- [GitHub release](https://github.com/pedronauck/docz/releases/tag/v0.3.2)

Thank you!
