### ISSUE TITLE
Edit page button is overlayed by the link to github

### ISSUE THREAD

**Issue by capaj** [pedronauck/docz#494]
## Bug Report

I have docz 0.12.15. I understand the github button is meant to be an overlay, but couldn't we shift the underlying button just a little bit?

**Describe the bug**

![image](https://user-images.githubusercontent.com/1305378/49670885-61401d00-fa66-11e8-9f02-ee701d07e53c.png)

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

The button is not overlayed

**Comment by Jared-Dev** [comment]
I'm seeing this as well. Any chance you could submit a PR?

**Comment by capaj** [comment]
I could this evening. Leave it up to me then.

**Comment by pedronauck** [comment]
Landed on [0.12.16](https://github.com/pedronauck/docz/releases/tag/v0.12.16) ✅
