### ISSUE TITLE
Resolving Path in JSON File

### ISSUE THREAD

**Issue by zicodeng** [pedronauck/docz#497]
In my `mdx` file, I can import a JSON file successfully. But in the JSON file, it defines path to other image assets but they cannot be resolved correctly. Any thoughts?

**Comment by zicodeng** [comment]
I tried to set `public: "./static"` in docz config, but still not working

**Comment by pedronauck** [comment]
Can you give us some repo with the minimum setup?

**Comment by zicodeng** [comment]
@pedronauck Hi I created a minimum example here: https://github.com/zicodeng/docz-load-anim-json

Thanks a lot!

**Comment by chooblarin** [comment]
Hi, I think I have a similar problem. 

I want to load some fonts in `/static` from CSS file like this. 
```
url('/static/fonts/NotoSans.woff') format('woff');
```

but it seems static file's root is `public` directory. (I saw [here](https://github.com/pedronauck/docz/blob/abb3626bce4f61b6ae132c0f39c501fbde646fd4/packages/docz-core/src/webpack/devserver.ts#L38).) How can I do this?

**Comment by chooblarin** [comment]
@zicodeng 

Your code work when I tried

1. Set image paths in `static/anim.json` to `/public/images/` instead of `./images/`
2. Rename public folder to `whatever` (other than `static`) from `static`.

**Comment by pedronauck** [comment]
In your case that you want to import the image instead of reference it, it's a better approach you create some kinda an alias on your `doczrc.js`, them import as you're doing

```js
export default {
  onCreateWebpackChain(config) {
    config.resolve.alias.set('static', path.join(__dirname, 'static))
  }
}
```

So, if you want just reference it without use webpack to parse, you need to put `/public` always before your request to reference files inside public folder.
