### ISSUE TITLE
How to include static assets?

### ISSUE THREAD

**Issue by regrettably** [pedronauck/docz#502]
## Question
I have certain assets that need to be included in order for my components to render correctly -- namely, fonts and images. 
Is there a way I can tell docz to mount a specific folder to a path in order to serve these alongside my component library?

Thanks!

**Comment by pedronauck** [comment]
you set set `public` option on your `doczrc.js`:

```
export default {
  public: '/path/to/your/public'
}
```

Then you can use from `/public` on your code.

**Comment by Jimeno0** [comment]
Is that possible to change the path to use?
I mean IE to serve from `/static` instead from `/public` in your code 
Thanks!

**Comment by xiufuwang** [comment]
you can see 'docz-core/index.js'   at row that like: "const devServerConfig=()....."
