### ISSUE TITLE
Using docz for CSS Style Guides

### ISSUE THREAD

**Issue by leonardofaria** [pedronauck/docz#503]
## Question

**Description**
At my work we have a component library (something similar to Bootstrap), with several Sass components. We use a Ruby gem called [hologram](https://github.com/trulia/hologram) - the result is something similar to [this](http://wearecube.github.io/hologram-github-theme-example/styleguide/base_css.html). For the React components built on top of this Sass components we use storybook.

I am thinking in using docs to replace both tools and have only one concise tool to show both components - the ones created with HTML + CSS and the ones created in React. I guess that for the HTML + CSS I would inject the compiled CSS in the theme, like when you inject bootstrap.min.css from a CDN in a page but I am not sure if this is the best approach.

I decided to post here to see if is anyone using docz in a similar way or if someone can bring additional information here. Thanks in advance and congratulations - this is an awesome project.

**Comment by leonardofaria** [comment]
I looked the docs-plugin-css and this is the way to go here. 
My doubt was if someone was using docz in a similar way (CSS style guide). I looked at the issues and examples and I didn't find one, I guess I can be the first

**Comment by trexguo** [comment]
@leonardofaria You can document HTML + CSS, here is a simple example:

**Note the html tags are actually JSX elements**

```
<Playground>
  {
    ()=>
      <>
        <button class="btn btn-default">Click</button>
        <a class="btn btn-default" href="#">Me!</a>
      </>
  }
</Playground>
```
**Ignore the styles. You should use your own css by adding them in doczrc.js (the configuration file)**

![image](https://user-images.githubusercontent.com/5989880/50327019-3bb41880-0528-11e9-9b94-a306213d479c.png)

**Comment by jpeet86** [comment]
Hi @leonardofaria ,

I was thinking of doing something like this too, building a HTML/CSS style guide with Docz. Was wondering how you got on with this? Did you manage to achieve it?

**Comment by leonardofaria** [comment]
@jpeet86 I kept using hologram and didn't have the time to invest in Docz.
