### ISSUE TITLE
Order doesn't work as expected with menu

### ISSUE THREAD

**Issue by alexandru-cazacu** [pedronauck/docz#51]
I have a list of pages with the following headers:

name: Introduction
route: /
order: 100
menu: Getting Started

name: Check Server Status
route: /check-server-status
order: 99
menu: Getting Started

name: Login
route: /login
order: 86
menu: Authentication

name: Update User
route: /user-update
order: 5
menu: User

(it's just a part of the list)

The groups are shown as follows: Authentication > Getting Started > User. How do i order them with Getting Started as the first element (without using subfolders as in [docz-website](https://github.com/pedronauck/docz-website))?

**Comment by pedronauck** [comment]
By now you can just set the order of documents, not for menus. But I think that I can create some `menuOrder` to fix that. I'll put release some new version with this!

**Comment by Rainower** [comment]
I also have a request related to the menus, it would be nice that when one arrives on a page of a menu directly from the url the menu is unfolded.

Thank you anyway, good job !

**Comment by Swapnull** [comment]
I had this issue so just prepended a number on the start to force ordering
![image](https://user-images.githubusercontent.com/4456346/41532254-3bc3fab0-72ee-11e8-811b-ee6d5b792bee.png)

**Comment by rafaelmotta** [comment]
+ 1. Would be good to insert in the documentation this limitation

**Comment by Kosai106** [comment]
@Swapnull This works, until you have more than 10 menu items. In my case this is what happens:

Not only is the menu items not ordered correctly, but sub items as well.

![screen shot 2018-06-22 at 16 34 32](https://user-images.githubusercontent.com/6379824/41782334-39ca1f06-763a-11e8-9aaa-b20c4ae88a1b.png)

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/managing-menu-order-on-default-theme)
