### ISSUE TITLE
Missing / broken .docz cache folder for docz dev

### ISSUE THREAD

**Issue by clight-fastly** [pedronauck/docz#520]
## Bug Report

Upgrading from docz `0.12.13` to `0.13.0` - cache folder missing.

ENOENT: no such file or directory, mkdir `$PROJECT/.docz/cache/.progress-estimator`

Manually removing folder and attempting start does not seem to work.

**To Reproduce**

1. Upgrade docz
2. Run `docz dev`

**Expected behavior**

Docz creates folder if needed.

**Environment**

- https://whatsmybrowser.org/b/WUK3M5H
- Node v8.12.0

**Comment by selrond** [comment]
@clight-fastly Same here, with an additional info:
When I ran `docz dev` directly after updating to `0.13.0`, everything compiled with no problem (having `.docz` folder from `v0.12.13`), except it threw a "could not resolve..." `docz-theme-default` message

**Comment by pedronauck** [comment]
I'm launching some patch now fixing this bug. So, about this @selrond, in the new version, you need to explicitly add `docz-theme-default` on your package.json.

```bash
$ yarn add docz-theme-default --dev
```

**Comment by selrond** [comment]
@pedronauck definitely needs to get added into setup guide / docs somewhere

**Comment by pedronauck** [comment]
Launched on [v0.13.2](https://github.com/pedronauck/docz/releases/tag/v0.13.2) ✅

**Comment by pedronauck** [comment]
It's on the readme @selrond and in the previous releases if you check it's there too ✌️

**Comment by selrond** [comment]
@pedronauck I've checked the changelog, and it wasn't there. I don't read `README.md` every time I update a dep

**Comment by pedronauck** [comment]
@selrond I think you did not see that https://github.com/pedronauck/docz/releases/tag/v0.12.17

**Comment by selrond** [comment]
@pedronauck hmm I've looked only at https://github.com/pedronauck/docz/blob/master/CHANGELOG.md
