### ISSUE TITLE
Docz default theme is no dependency.

### ISSUE THREAD

**Issue by SheepFromHeaven** [pedronauck/docz#525]
## Bug Report

**Describe the bug**
Currently installing the docz package does not bring the default theme with it, which will lead to the following error:
Module not found: Can't resolve 'docz-theme-default'

*A clear and concise description of what the bug is.*
docz-theme-default is no dependency of docz.

**To Reproduce**
Install docz and try to start dev.

```shell
docz dev
```

**Expected behavior**
docz-theme-default is installed with the docz package or it is stated in the documentation otherwise

**Environment**

* OS: OSX 10.14
* Node/npm version: Node 11/npm 6.1.4

**Comment by pedronauck** [comment]
Since [v0.12.17](https://github.com/pedronauck/docz/releases/tag/v0.12.17) now you need to explicit install `docz-theme-default` as dependency on your project.

**Comment by SheepFromHeaven** [comment]
@pedronauck then I think it should be mentioned in the get started docs, so it is not causing errors there 🙂

**Comment by jb-san** [comment]
after updating and installing docz-theme-default, im getting 
```
Compiled with warnings.

./node_modules/docz-theme-default/dist/index.m.js
Attempted import error: 'ClassNames' is not exported from '@emotion/core'.

./node_modules/emotion-theming/dist/emotion-theming.browser.esm.js
Attempted import error: 'ThemeContext' is not exported from '@emotion/core'.

./node_modules/emotion-theming/dist/emotion-theming.browser.esm.js
Attempted import error: 'ThemeContext' is not exported from '@emotion/core'.

./node_modules/emotion-theming/dist/emotion-theming.browser.esm.js
Attempted import error: 'ThemeContext' is not exported from '@emotion/core'.
```

**Comment by amirphp7** [comment]
./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'ComponentsProvider' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useComponents' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useComponents' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useComponents' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/chunk.esm.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm2.js
Attempted import error: 'useConfig' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useDocs' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useDocs' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useMenus' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'usePrevious' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'usePrevious' is not exported from 'docz'.

./node_modules/docz-theme-default/dist/index.esm.js
Attempted import error: 'useWindowSize' is not exported from 'docz'.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
