### ISSUE TITLE
[SOLVED] Active link in sidebar no longer working since 0.12.16

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#526]
## Solved
*Solution:* Use yarn and install peer dependencies
```
yarn add docz docz-theme-default react react-dom
```

## Bug Report

**Active link** in sidebar in docz-theme-default **no longer working since 0.12.16** (working with 0.12.15).

**Not working**
![image](https://user-images.githubusercontent.com/9749061/50169081-27380c00-02ed-11e9-90c6-aecbf3abde7c.png)
- Use **docz 0.12.16 or docz 0.12.17+** with docz-theme-default 0.12.17+
- Go to one page
- Link is not active in sidebar

**Working**
![image](https://user-images.githubusercontent.com/9749061/50169180-58184100-02ed-11e9-8a8a-799b13edbd4a.png)
- Use **docz 0.12.15 or older**
- Go to one page
- Link is active

By the way, amazing job ;)

**Comment by pedronauck** [comment]
Really? I'm using 0.12.7 here and the active link is working normal, I tried in some clean install and everything works fine too. Even using an emoji in the name 🤔 

![](https://cdn-std.dprcdn.net/files/acc_649651/makx88)

So, this can be some conflict with emotion or react-router maybe. Do you have any extra information about that?

**Comment by ivan-dalmet** [comment]
Sorry I miss a 1 so since 0.12.16... I update the title and description right now   :/

**Comment by pedronauck** [comment]
Did you try to update to the newst version @ivan-dalmet ?

**Comment by ivan-dalmet** [comment]
Yes I tried first with 0.13.4

**Comment by pedronauck** [comment]
Can you give me more information about your repo? Maybe some example with the minimal setup.

**Comment by ivan-dalmet** [comment]
Yes I will give you an example tomorrow (it's 9 p.m. here in France ☺)
 Thanks for your time !

**Comment by ivan-dalmet** [comment]
@pedronauck I've made a litte repo with 3 examples ❌  0.13.4 (ko), ❌ 0.12.16(ko) and ✅ 0.12.15 (ok)
Follow the README of this repo to reproduce:
https://github.com/ivan-dalmet/docz-issue-sandbox

**Comment by pedronauck** [comment]
That's pretty weird, because is something that's just happen with npm, I tried using yarn and everything works fine 😕

**Comment by ivan-dalmet** [comment]
🤨Yes, that's weird! I tried with Yarn on the examples and it works... But on my project, with Yarn (I removed node_modules and .docz folders) I get the following error 😭 
![image](https://user-images.githubusercontent.com/9749061/50236955-04285d80-03bc-11e9-8684-283757ac2d64.png)
(Yarn version 1.12.3)

**Comment by ivan-dalmet** [comment]
@pedronauck I found the problem
Docz needs `react` and `react-dom` as peer dependencies! 
(may be the doc can be udpate with the `yarn add docz docz-theme-default react react-dom`)

But that's still weird that npm vs yarn change the display 🤨

**Comment by pedronauck** [comment]
Pretty good @ivan-dalmet I'll put react and react dom as dependency on docs 🙏 thanks to the help...

**Comment by nmessager** [comment]
I have the same problem but in my case i have also these dependencies installed
```
"dependencies": {
    "docz": "^0.13.7",
    "docz-theme-default": "^0.13.7",
    "webpack": "^4.28.4",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14"
  }
```
When i remove all webpack dependencies from my package.json it works when i use yarn. Any idea ?

**Comment by nmessager** [comment]
Follow the README of this repo to reproduce:
https://github.com/nmessager/docz-issue-sandbox

**Comment by roscioli** [comment]
Hey guys, is the active menu item supposed to update on scroll? Or is that a feature that is not yet implemented?
