### ISSUE TITLE
Putting `dist` as `./` removes all files

### ISSUE THREAD

**Issue by albinekb** [pedronauck/docz#53]
## Bug Report

1. Set `"dist": "./"`
2. Run `docz build`
3. Everything except `node_modules` is removed.

**Expected behavior**

Docs are compiled to "./", or a warning is thrown. No files should be deleted.

Luckily this happened when i was playing around but it could be devastating if you aren't using git correctly 😄

**Comment by chrisdemars** [comment]
Do we know what the fix is for this @albinekb ?

**Comment by pedronauck** [comment]
Fixed on [v0.6.0](https://github.com/pedronauck/docz/releases/tag/v0.6.0) 🚀
