### ISSUE TITLE
Searching in docz-theme-default menu duplicates menu items in the UI

### ISSUE THREAD

**Issue by chrisrzhou** [pedronauck/docz#532]
## Bug Report
When adding `menu` field to md/mdx frontmatter, it creates bugs in the search interface of `docz-theme-default`.  The bug causes more menu items to be created when users backspace and retype the values again.  A `console` warning is fired as well which warns about duplicate keys.

I think the bug is because the search typeahead is looking at both the menu text and nested menu text to decide whether it should display on the search bar.  When `backspace` is pressed, it doesn't clear the state (probably due to non-unique React keys), which causes the old elements to still persist, leading to duplication of UI submenu items in the menu.

This makes the nested menu somewhat unusable.

I also tested that if the menu name doesn't clash with any of the existing component names, then things work fine.  For example, searching for `m`, `a`, `menu`, `aaa` are all fine below without errors.

```
// md1.mdx
---
menu: aaa
---

// md2.mdx
---
menu: aaa
---
```

The issues happens when the markdown file names have matching characters as the menu frontmatter value e.g.

```
// md1.mdx
---
menu: mymenu
---

// md2.mdx
---
menu: mymenu
---
```

Typing `m` and backspacing will create the bug because `m` exists in both the menu frontmatter value, as well as the markdown file names.

**To Reproduce**

1. Clone and install test repo

```
git clone git@github.com:chrisrzhou/docz-test-menu.git
cd docz-test-menu
yarn
yarn docz dev
```

Or create two markdown files like this:
```
// md1.mdx
---
menu: mymenu
---

// md2.mdx
---
menu: mymenu
---
```

2. Search in menu by typing `m`, then `m1`
3. Backspace and repeat 2 over and over again.

**Expected behavior**
Expect that it should show `m1` and `m2` and then `m1`, but what we get is `m1`, `m2` being duplicated in the menu.  The following error trace is also shown in the console:

```
Warning: Encountered two children with the same key, `01CZ5B2RC11CXABZ3AC94BWSNY`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in nav (created by Context.Consumer)
    in Styled(nav) (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Styled(div) (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Styled(div) (created by Context.Consumer)
    in Menu (created by SidebarBase)
    in SidebarBase (created by withSizes(SidebarBase))
    in withSizes(SidebarBase) (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Context.Consumer)
    in ThemeConfig (created by Page)
    in Page (created by AsyncRoute)
    in AsyncRoute (created by Route)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in MDXProvider (created by DocPreview)
    in DocPreview (created by Context.Consumer)
    in ThemeProvider (created by Context.Consumer)
    in ThemeConfig (created by Theme)
    in Theme (created by Theme)
    in ScrollToTopBase (created by Route)
    in Route (created by withRouter(ScrollToTopBase))
    in withRouter(ScrollToTopBase) (created by Theme)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Router)
    in Router (created by Theme)
    in DataServer (created by Theme)
    in StateProvider (created by Theme)
    in ErrorBoundary (created by Theme)
    in Theme (at root.jsx:5)
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot (at app/index.jsx:14)
```

**Environment**

* OS: macOS 10.14.1
* Node/npm version: 0.13.5 (but I've ran into issues in 0.12.* as well)

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/4425362/50273203-ddcfe580-03ee-11e9-972f-28c3f38515c1.png)

**Comment by ivan-dalmet** [comment]
Same problem here 😢

**Comment by Glazy** [comment]
Looks like this issue can be closed now @pedronauck :muscle:

**Comment by jakelacey2012** [comment]
This isn't fixed.
