### ISSUE TITLE
Export all default components

### ISSUE THREAD

**Issue by JeroenReumkens** [pedronauck/docz#533]
I know there is already something on the roadmap to release a UI Kit, but I was wondering if it is possible to at least export all the default Docz components. That would already be a great start I think! Right now some components in the components folder can be imported, but others can't. 

Right now I needed to create my own custom `Table`, which I wanted to look just like the Docz table. However, to achieve that, I had to copy that component. This of course can break with each update of Docz. So I'd rather see an option to import it.

Curious how others think about it.

**Comment by JeroenReumkens** [comment]
Hey @pedronauck 

I was wondering if you've considered this option as part of the new V1 release? I think it would be a great (and easy?) addition. 

Thanks!

**Comment by pedronauck** [comment]
This is done on v1 @JeroenReumkens  :)

**Comment by JeroenReumkens** [comment]
Hey @pedronauck 
Thanks for yo awesome work on v1!! 
You mean the usecomponents hook? I saw that and already tried that. But that way it isn’t yet possible to use the components themselves inside a mdx file, right?

**Comment by pedronauck** [comment]
Sorry @JeroenReumkens, I didn't understand your question. It's possible to use components inside mdx like always, but what specific you want to?

**Comment by JeroenReumkens** [comment]
Hey @pedronauck 

What I'm trying to achieve is importing the Docz table component in my MDX file, and also importing eg my breakpoint settings, and generate a table in JSX with all of the breakpoints. It would be nice if I could then re-use the Docz table component, so all tables would look the same. And I don't need to manually replicate the Docz table (or override the docz default table with my own table I need to style and maintain).

A simplified example of how I would like to use this in MDX would be: 

```
import {Table} from 'docz';
import breakpoints from '../breakpoints';

<Table>
    {breakpoints.map(breakpoint => (
        <tr><td>{breakpoint.name}</td><td>{breakpoint.size}</td></tr>
    ))}
</Table>
```

**Comment by pedronauck** [comment]
Oh for sure, you can export it from `docz-theme-default` like you can see:
https://github.com/pedronauck/docz/blob/master/core/docz-theme-default/src/index.tsx#L33

**Comment by JeroenReumkens** [comment]
Yes, that's exactly what I was looking for! Thanks a lot for adding this 😄
