### ISSUE TITLE
Distribute components as UI library

### ISSUE THREAD

**Issue by tokenvolt** [pedronauck/docz#534]
## Is there a way to produce a build of components (as UI library) and not a static site? 

I have implemented a style guide using this amazing library. Everything is working fine, but now I want to use the components outside of docz and distribute them a separate package, is there a way to achieve this?

**Comment by pedronauck** [comment]
You can use something like [microbundle](https://github.com/developit/microbundle) to do that, this is not a responsibility of docz.
