### ISSUE TITLE
Crashes when using Playground Component - docz v0.13.5

### ISSUE THREAD

**Issue by JClackett** [pedronauck/docz#540]
## Bug Report

Crashes when using the Playground component

**To Reproduce**

Just wrapping my components in <Playground> 

```jsx
<Playground>
	<Button>Click me</Button>
	<Button variant="primary">Click me</Button>
</Playground>
```
I'm using styled-components and typescript? but if i just use:

```jsx
<Playground>
	<div>hello</div>
</Playground>
```
it still breaks..

**Stack trace**

🚨 Whoops, we crashed 🚨
Passed an incorrect argument to a color function, please pass a string representation of a color.
Stack trace
in right (created by Resizable)
in div (created by Resizer)
in Resizer (created by Resizable)
in span (created by Resizable)
in div (created by Resizable)
in Resizable (created by RenderBase)
in div (created by Context.Consumer)
in div (created by LiveProvider)
in LiveProvider (created by RenderBase)
in RenderBase (created by Context.Consumer)
in ThemeConfig (created by Render)
in Render (created by BasePlayground)
in BasePlayground (created by Context.Consumer)
in Component (at Button.mdx:22)
in div (created by MDXTag)
in MDXTag (created by Context.Consumer)
in Component (at Button.mdx:16)
in MDXContent (created by AsyncComponent)
in AsyncComponent (created by ExportedComponent)
in ExportedComponent (created by Context.Consumer)
in Component (created by UnconnectedReactImportedComponent)
in UnconnectedReactImportedComponent (created by ReactImportedComponent)
in ReactImportedComponent (created by ImportedComponent)
in ImportedComponent (created by ForwardRef)

**Expected behavior**

Render without crashing

**Environment**

* Docz: 0.13.5
* OS: [OSX 10.14.1]
* Node/npm version: [Node latest / yarn latest]

**Comment by JClackett** [comment]
Okay, so after more debugging, just doing a clean install of docz and removing any cache seems to fix it, not sure if this was something i did whilst installing originally?

**Comment by pedronauck** [comment]
In the newest versions you need to explicitly add `docz-theme-default` as dependency on your project. And a fresh install always help with 😂

**Comment by JClackett** [comment]
hmm, yes but i did have it installed originally
