### ISSUE TITLE
font size isn't changing

### ISSUE THREAD

**Issue by socker210** [pedronauck/docz#555]
## Bug Report

**Describe the bug**
 Font-size of h1 isn't changing when fontSize's data type is Array.

my doczrc.js:
```javascript
const path = require('path')

module.exports = {
  title: 'the title',
  description: 'description of component',
  src: path.resolve(__dirname, 'examples'),
  dest: './dist',
  codeSandbox: false,
  themeConfig: {
    styles: {
      h1: {
        fontFamily: '\'Source Sans Pro\', Helvetica, sans-serif',
        fontWeight: 100,
        fontSize: [36, 38, 42]
      }
    }
  }
}
```

But, the font-size is ...

1120px: 36px
920px: 70px
420px: 50px

I expected ...

1120px: 42px
920px: 38px
420px: 36px

**Environment**

* OS: OS X (Mojave)
* Node/npm version: v11.4.0 / v6.5.0
* docz: 0.13.7
* docz-theme-default: 0.13.7

**Comment by kachkaev** [comment]
Same thing. I'm unable to change font sizes for body, headers, menu etc. – it's always default and it looks too big. Can the issue be related to https://github.com/pedronauck/docz/commit/825612edc6ad599be3f0727e35352b825f80117f#diff-1a78deda6004651f093ed4d38f859d88R16?

This part of the theme docs seems to be misleading ATM: https://github.com/pedronauck/docz/tree/master/packages/docz-theme-default#default-themeconfig

**Comment by kachkaev** [comment]
I finally manage to reduce font size in the menu on the left and in the main area by using the following workaround:

```js
{
  themeConfig: {
    styles: {
      blockquote: {
        fontSize: 14,
      },
      body: {
        "nav a": {
          fontSize: "14px !important", // <-- [1]
        },
      },
      container: {
        fontSize: 14,
      },
      h1: {
        fontWeight: "normal",
        fontSize: 48,
      }
    }
  }
}
```

[1]: [ docz/packages/docz-theme-default/src/styles/global.ts#L15](https://github.com/pedronauck/docz/blob/89e1d03a8ea489fb6dd244588221c8d62aaf1122/packages/docz-theme-default/src/styles/global.ts#L15)

**Comment by pedronauck** [comment]
Is this already solved? Can I close here?

**Comment by socker210** [comment]
@kachkaev Thank you! I will try your solution 👍 @pedronauck Sorry for late reply. I closed this issue thanks.

**Comment by kachkaev** [comment]
Mo solution is a workaround. It'd be nice if the font in the menu could be tweaked in a slightly less crazy way 🙂

**Comment by yyynnn** [comment]
Yeah like in the readme

**Comment by yyynnn** [comment]
I also kinda stupid to do this to avoid min-width css rule on the container:

```javascript
styles: {
      container: {
        width: '100%!important'
      }
    }
```
