### ISSUE TITLE
Component not render correctly using only emotion CSS props

### ISSUE THREAD

**Issue by rakasiwi23** [pedronauck/docz#560]
## Bug Report

**Given the following basic component code**
```
// @flow
import React from 'react'
import { css } from '@emotion/core'

const base = css`
  color: red;
`

export const Button = ({ children }) => <button css={base}>{children}</button>
```

**.babelrc**
```
{
  "presets": ["@babel/preset-flow", "@emotion/babel-preset-css-prop"]
}
```

**Expected behavior**

It should render a button with red color on it. But instead the css is not loaded correctly

**Additional context/Screenshots**
<img width="876" alt="docz example flow 2018-12-29 20-12-20" src="https://user-images.githubusercontent.com/7766807/50538723-38630180-0ba6-11e9-8b9a-a3190261b6d4.png">
<img width="469" alt="docz example flow 2018-12-29 20-12-53" src="https://user-images.githubusercontent.com/7766807/50538725-3f8a0f80-0ba6-11e9-805c-bdb126ee4a04.png">

**Comment by nathunsmitty** [comment]
I'm also experiencing this

**Comment by pedronauck** [comment]
So, do you need to set the pragma, no?!

**Comment by nathunsmitty** [comment]
I'm getting issue with both the pragma and the babel preset – my issue seems to be that I'm using TypeScript, since it works fine for me just using .js files. If it helps, I can set up a demo repo.

**Comment by rkusa** [comment]
Same here, with a pure TS setup. From browsing emotion-js/emotion#1046 the only solution I found was to set `"jsx": "preserve"` in the `tsconfig.json` and then using `/** @jsx jsx */` in any TS file.

**Comment by simonflk** [comment]
Same here. I worked around it by removing the docz babel preset.
My docz setup is running in the same project as my webapp, so everything I need for ESNext & React etc is already configured.

my docz.js looks like this:
```js
module.exports = {
    modifyBabelRc: babelRc => {
        // Remove conflicting docz preset
        babelRc.presets.pop();

        // Optional: Add plugin to make docz's `parseProps` feature work
        babelRc.plugins.unshift([
            'babel-plugin-react-docgen',
            { resolver: 'findAllExportedComponentDefinitions' }
        ]);
        return babelRc;
    }
}
```

It would be nice if there was an option to make _babel-preset-docz_ skip some of its plugin loading if you already have babel & react configured.

**Comment by ticidesign** [comment]
I had the same problem and  [@mitchellhamilton](https://github.com/mitchellhamilton) one of the maintainer of Emotion helped me.

Docz appends its babel preset to the user provided config so since its babel preset includes @babel/preset-react which includes the react jsx transform which @emotion/babel-preset-css-prop also uses. So Docz's usage of the react JSX transform is used by default.

To fix this, we're including the JSX transform plugin in the plugins in our doczrc.js file. 
This works because plugins in the config take precedence over plugins in presets.

```js
plugins: [
    createPlugin({
      modifyBabelRc(babelrc) {
        return {
          ...babelrc,
          plugins: [
            ...babelrc.plugins,
            [
              '@babel/plugin-transform-react-jsx',
              { pragma: '___EmotionJSX', pragmaFrag: 'React.Fragment' },
            ],
          ],
        };
      },
    }),
  ],
```

Credits to @mitchellhamilton

**Comment by rakasiwi23** [comment]
Thanks, @ticidesign for the solution. I close this issue

**Comment by bcbrian** [comment]
I have tried both @ticidesign and @simonflk and they do not work... I am sure I am missing something something small...

**Comment by gsong** [comment]
@ticidesign @mitchellhamilton Do you have a solution for Gatsby v2? I've tried various combinations of `gatsby-node` and `doczrc` to no avail.

**Comment by rakannimer** [comment]
Hey @gsong,

I tried a basic setup of docz with the example code provided above and it works as expected : 

```jsx
import React from 'react'
import { css } from '@emotion/core'

const base = css`
  color: red;
`

export const Button = ({ children }) => <button css={base}>{children}</button>
```

Any chance you can provide a repro repo ?

**Comment by gsong** [comment]
@rakannimer I think the issue was using the `css` prop while in a `<Playground>` component. I don't have a good repro repo right now.
