### ISSUE TITLE
Submenu not working correctly

### ISSUE THREAD

**Issue by eliezer-souza** [pedronauck/docz#564]
## Bug Report

When adding submenus using ##, it is not displayed in the menu list and after clicking on any component, the menu simply closes

**Expected behavior**

That all submenus appear in the side menu and that after selecting a component the menu does not close

**Environment**

* OS: Windows 10
* Node version: v10.5
* npm version: v6.1
* Docz version: v0.13.7

**Additional context/Screenshots**

<img src="https://i.imgur.com/UBDdgkb.gif" />

**Correct behavior**

<img src="https://i.imgur.com/uKBaz4X.png" />

**Comment by ivan-dalmet** [comment]
Same problem as #526 
TL;DR --> Use Yarn instead of Npm

**Comment by eliezer-souza** [comment]
@ivan-dalmet Yeah, solved for me too, thanks
