### ISSUE TITLE
My library generates a CSS file, I'd like to watch it and include it

### ISSUE THREAD

**Issue by lorem--ipsum** [pedronauck/docz#57]
## Question

**Description**
I have a library of components (TS, React, SCSS) that follows a very simple structure. I've developed a tool similar to Docz but I'd like to give Docz a try. Having Docz use the TSX components is easy, but I have no idea how to include in the generated HTML my project's generated CSS.

*Give more information about your doubt*

Should this be a plugin ? Or should I somehow use webpack for that ? I have no idea. ¯\_(ツ)_/¯

Also, thanks a lot for this project, it looks great !

**Comment by pedronauck** [comment]
In the issue #6 you can some related case, but if you want to use the generated css on the HTML file, you can use webpack extract plugin or create your own `index.html` as we [explain here](https://www.docz.site/documentation/project-configuration#theming)

**Comment by pedronauck** [comment]
After released [v0.2.11](https://github.com/pedronauck/docz/releases/tag/v0.2.11) you can use [docz-plugin-css](https://github.com/pedronauck/docz/tree/master/packages/docz-plugin-css) to configure your CSS just by adding a plugin. ✌️ 

@lorem--ipsum
