### ISSUE TITLE
Support both TS and React

### ISSUE THREAD

**Issue by OlafCheng** [pedronauck/docz#583]
Hi, we recently use DOCZ to render our compony's React components document and I know that if I add `typescript: true` to `doczrc.js`, DOCZ would be enabled to render tsx componets' MDX correctly, but it will not be able to compile React component written with `.js` postfix.
(Our React components have both components with `.js` and `.tsx`.)

Can you support this kind of request? Thank you!

**Comment by mbrochh** [comment]
Are you sure this does not work? I just tried this and it seems to work.

Here is my `doczrc.js`:

```
export default {
  indexHtml: './src/components/misc/DoczIndex.html',
  typescript: true,
}
```

In my project, I have both, "*.js" components and "*.tsx" components and both are documented in "*.mdx" files. When I run `yarn docz:dev` everything seems to work fine.

**Comment by OlafCheng** [comment]
@mbrochh Maybe there is something wrong with my project's bundle config, I'll check it. Thank you. 😊

**Comment by wokakou** [comment]
> Are you sure this does not work? I just tried this and it seems to work.
> 
> Here is my `doczrc.js`:
> 
> ```
> export default {
>   indexHtml: './src/components/misc/DoczIndex.html',
>   typescript: true,
> }
> ```
> 
> In my project, I have both, "_.js" components and "_.tsx" components and both are documented in "*.mdx" files. When I run `yarn docz:dev` everything seems to work fine.

when set `typescript : true` ,the `Props` dosen't render , with .js and .tsx
