### ISSUE TITLE
Submenu config in doczrc not working

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#585]
## Bug Report

Menu config in doczrc is not working (v0.13.7) 😢 

_Node version: v10.13.0_
_Yarn version: v1.13.0_

#### Menu config in `doczrc.js` file:
```
menu: [
  'Home',
  {
    name: 'Components',
    menu: ['Alerts', 'Buttons']
  },
],
```

#### `index.mdx` file:
```
---
name: Home
route: /
---

... page content ...

```

#### `button.mdx` file:
```
---
name: Buttons
---

... page content ...

```

#### `alert.mdx` file:
```
---
name: Alerts
---

... page content ...

```

### Expected menu result:
```
> - Home  // Link to index.mdx
> - Components // Toggle subnav
> -- Alerts // Link to alert.mdx
> -- Buttons // Link to button.mdx
```

### Buggy menu result:
```
> - Home // Link to index.mdx 👍 
> - Components // Toggle subnav 👍 
> -- Alerts // Link to nowhere 😢 
> -- Buttons // Link to nowhere 😢 
> - Alerts // Link to alert.mdx 😢
> - Buttons // Link to button.mdx 😢
```

Any idea why ?

**Comment by nmessager** [comment]
You can set the parent menu of your component like that
`---
menu: Components
name: Buttons
---

... page content ...`

It works for me.

**Comment by ivan-dalmet** [comment]
Yes this option works but I want to manage the navigation only in the doczrc.js file.
This feature is available since the 0.12.4 https://github.com/pedronauck/docz/releases/tag/v0.12.4
And I made it works a few time ago, but not with the last version.
I'm trying to make it works on an older version to see the regression.

**Comment by ivan-dalmet** [comment]
To reproduce this issue --> https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-585

**Comment by pedronauck** [comment]
@ivan-dalmet yeah, for sure this won't get work because of you need to explicit add the `menu` property on each mdx. Since the `menu` property on doczrc is just kinda a *sorter*, it doesn't create and organize menus for you, it just sort based on what you setup on each mdx.
