### ISSUE TITLE
Modify front matter during build?

### ISSUE THREAD

**Issue by dshimkoski** [pedronauck/docz#586]
Is it possible to add front matter to mdx files programmatically as part of the build step?

I'm building the `menu` in doczrc and I'd basically like to specify the corresponding `menu` front matter as part of the build step.

Thanks!

**Comment by dshimkoski** [comment]
Awesome 👏 Thanks!

**Comment by treshugart** [comment]
I'm still having a hard time with this one. I've copied the OP's code and put it into a `gatsbyRemarkPlugins` entry. I can confirm that it's transforming the file. Here's the code:

```js
const jsYaml = require('js-yaml')

module.exports = ({ markdownAST }, pluginOptions) => {
  const node = markdownAST.children.find(c => c.type === 'yaml')
  const fm = node || { type: 'yaml' }
  fm.value = jsYaml.safeDump({ name: 'override', menu: 'Section' }).trim()
  if (!node) {
    markdownAST.children.unshift(fm)
  }
  return markdownAST
}
```

And the config:

```
export default {
  files: 'docs/README.md',
  gatsbyRemarkPlugins: ['@looker/gatsby-remark-rewrite-menu']
}
```

The name and the section do show up as front matter, but are not reflected in the UI. I've tried clearing cache, etc.

Any ideas?

**Comment by treshugart** [comment]
It looks like the front matter is already removed from the AST and is in `markdownNode.frontmatter`. I've tried modifying that to no avail.
