### ISSUE TITLE
Support JavaScript in Playground

### ISSUE THREAD

**Issue by stefanbuck** [pedronauck/docz#587]
Wouldn't it be awesome if we could use vanilla JavaScript functions in the playground component as well? Basically JSFiddle lite for Docz. 

```jsx
import foo from './src/foo.js'

<Playground>
  foo('bar')
</Playground>
```

**Comment by dshimkoski** [comment]
You can do something similar with third party modules.

For instance, you could use [react-simple-code-editor](https://www.npmjs.com/package/react-simple-code-editor) and export a custom component from your library:

```jsx
export class Code extends React.Component {
  state = { code: '' }

  run(code) {
    try {
      return eval(code)
    } catch(e) {}
  }

  render() {
    const code = this.state.code || this.props.children
    return (
      <>
        <code>{this.run(code)}</code>
        <Editor
          value={code}
          onValueChange={code => this.setState({ code })}
          ...
        />
      </>
    );
  }
}
```
Then just use that instead of `<Playground />`:
```jsx
import { Code } from 'my-lib'

<Code>1 + 2</Code>
```

**Comment by stefanbuck** [comment]
Thanks for your suggestion @dshimkoski. It works if all your JavaScript is inline, but I need to import other functions. It looks like that `eval` is not able to access variables which are declared outside

**Comment by dshimkoski** [comment]
@stefanbuck 

Example here: https://github.com/dshimkoski/docz-code-editor

You can work around this limitation by [manually importing stuff into the global scope from a lib file](https://github.com/dshimkoski/docz-code-editor/blob/master/lib/index.js).

Kinda clunky but it's better than nothing!
