### ISSUE TITLE
Could not find dependency version for xxx

### ISSUE THREAD

**Issue by zicodeng** [pedronauck/docz#598]
## Bug Report

**Describe the bug**

After running `docz dev`, I am seeing a lot of `could not find dependency version for ...` in my console. However, after the build process, the app still runs fine.

**To Reproduce**

I am assuming this bug comes from how I import my modules. I used resolved path to import my module, but Docz thinks it is a node module missing dependency version?

**Expected behavior**

Console should have no warnings.

**Environment**

* OS: 10.14.2
* Node/npm version: 10.12.0

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/24593509/51578965-25c1ac80-1e74-11e9-85c0-4a59a790d6d1.png)

**Comment by CesarDenis** [comment]
@zicodeng, have you solved this bug?

**Comment by pedronauck** [comment]
Try to update to new version, we are no longer using emotion on docz and no longer suporting `0.13.7`.

**Comment by yyynnn** [comment]
it happens on 1.0.4

**Comment by LucidityDesign** [comment]
Same problem with 1.2.0

**Comment by zicodeng** [comment]
I solved the problem by using relative path in all of my `mdx` files (you can use alias in your component source files, that's fine, but if you use alias in `mdx` files, you will get this error, but it doesn't cause any functional bugs)
