### ISSUE TITLE
How to compile React Component with less or css?

### ISSUE THREAD

**Issue by YardWill** [pedronauck/docz#6]
How to compile React Component with less or css? Our UI Library in private npm registry just compiled to es5 and we didn't  compile less(We compiled less in our business project with webpack).

**Comment by pedronauck** [comment]
You can modify your bundler config and put less, sass or css modules at rules... I didn't have much time, but my idea is create something like `docz-plugin-less`, `docz-plugin-sass`, `docz-plugin-cssmodules` in the near future...

But if you want to modify your bundler config, just use the `modifyBundlerConfig` on `doczrc.js`:

```js
// doczrc.js
export default {
  modifyBundlerConfig: (config) => {
    /* put your custom loaders logic here */
    return config
  }
}
```

**Comment by YardWill** [comment]
@pedronauck Can you show me a loader example? I can't find it in doc. Thanks!

**Comment by renatorib** [comment]
@YardWill 

You need to put the loader of sass or less. 
Here is an example using sass:

```js
// doczrc.js

export default {
  modifyBundlerConfig: (config) => {
    config.module.rules.push({
      test: /\.scss$/,
      use: ["style-loader", "css-loader", "sass-loader"]
    })
    
    return config
  }
}
``` 

Read more here: https://github.com/webpack-contrib/sass-loader

**Comment by kunokdev** [comment]
@pedronauck as mentioned on #140 I am still getting error, I tried both adding loaders and the plugin. I use create-react-app v2 with sass and css modules. I fail to include both local css files and from npm. 
Pasted details from previous comment:

Hello, while I am using @tsnolan23 's config I get zero errors, but none of CSS was loaded.

```
export default {

  modifyBundlerConfig: config => {
    config.resolve.extensions.push(".scss")
    config.module.rules.push({
      test: /\.scss$/,
      use: ["style-loader", "css-loader", "sass-loader"],
    })

    return config
  },
}
```

and 

```
import { css } from "docz-plugin-css"

export default {
  plugins: [
    css({
      preprocessor: "sass",
      cssmodules: true,
    }),
  ],

}
```
throws error that it needs appropriate loader. 

```
Failed to compile.

./src/components/Avatar/styles.module.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import "../../_vars";
|
| .avatar {
```

Basicallty, I am using CRA2 with Sass and CSS modules, this way:
```
// @flow
import React from "react"

import styles from "./styles.module.scss"

type PropTypes = { value: string }

const Avatar = ({ value }: PropTypes) => (
  <div className={styles.avatar}>{value && value.substring(0, 1)}</div>
)

export default Avatar
``` 
Any suggestions?
