### ISSUE TITLE
Sharing: good Docz Example

### ISSUE THREAD

**Issue by dfee** [pedronauck/docz#606]
Hey @pedronauck, just wanted to share the docz that I have for my project so that you could add those to a list of sites using docz. https://dfee.github.io/rbx

Cheers

**Comment by adeelibr** [comment]
Can I make a PR to add my OSS library built on `docz` as well, I am more then happy to make a PR for it https://melting-pot.netlify.com/ This is fairly new.

**Comment by sw-yx** [comment]
hey! i saw you launch rbx on r/reactjs. nice usage of docz! how was your experience?

**Comment by dfee** [comment]
@sw-yx pretty good. I actually migrated away from storybook.

That said, I had to build a custom props-table, and a custom `Frame` component (so that certain pieces of my code would be isolated (in an iframe).

The only point of real improvement, I think, is on theming.

**Comment by pedronauck** [comment]
Thanks to the feedback @dfee, btw your site is awesome 👏 I'm very busy at the end of the last year and at the beginning of this, but this is changing, so close I'll get more involved with docz again and also get people involved in order to help maintain. We really need this. So, this points that you talked, I saw as very important points too and they're already in my mind.

**Comment by HadeAs** [comment]
@dfee  good usage of docz!  btw, how can i write a demo code that contain state components

**Comment by dfee** [comment]
@sw-yx my implementation is slightly peculiar, but you can here is a link to [`<Frame>` (my iframe component0](https://github.com/dfee/rbx/blob/master/src/__docs__/components/frame.tsx) -- note that i'm truly copying styles and stylesheets from the root window... and also note that i'm using a polyfill for ie11 (which doesn't support the `srcdoc` attribute.

Also, I have my [`<SimplePropsTable>` implementation here](https://github.com/dfee/rbx/blob/master/src/__docs__/components/simple-props-table.tsx). Note that I've largely thrown out the `withMDX` components, and probably will throw the rest of it out at some point. This is because it was difficult to understand how it worked (and there's no TS types!).

**Comment by dfee** [comment]
@HadeAs I wrote stateful components (in my case, they're typically examples), in separate files... for example: [`<SimpleModalManager>`](https://github.com/dfee/rbx/blob/master/src/components/modal/__docs__/simple-modal-manager.tsx). Note that I just import that component and use it in a playground, but I explicitly call out that I don't ship those examples in my docs.

**Comment by HadeAs** [comment]
@dfee thanks for reply!

**Comment by gaui** [comment]
Awesome example. Thank you for this. Any way to add things like typography and color pallets? Like it's possible in [Catalog](https://www.catalog.style/try)

**Comment by Dobby89** [comment]
In case anyone hasn't seen this in a related issue thread (https://github.com/zicodeng/docz-iframe-playground)

An iframe playground component :D https://github.com/zicodeng/docz-iframe-playground

**Comment by sw-yx** [comment]
cool. closing this for now. iframe looks cool https://github.com/pedronauck/docz/issues/789
