### ISSUE TITLE
Does the menu option support the notion of sub menus?

### ISSUE THREAD

**Issue by mcdonnelldean** [pedronauck/docz#611]
## Does the menu option support the notion of sub menus

Right now I can give an `.mdx` file a value for menu like so `menu: Foo`. Are menus single level or is there a syntax to support sub menus?

**Comment by sw-yx** [comment]
i believe so - you have to use doczrc.js i think. see the docz site 
![image](https://user-images.githubusercontent.com/6764957/52022165-c24f0480-249b-11e9-9ef4-73fadb035717.png)

https://github.com/pedronauck/docz-website
