### ISSUE TITLE
It does not run - Module build failed - Cannot read property 'plugins' of undefined

### ISSUE THREAD

**Issue by bichotll** [pedronauck/docz#62]
## Bug Report

I installed docz and tried to run it `docz dev`. It started to compile until it showed me the following error:

```shell
 ERROR  Failed to compile with 1 errors                                                        5:26:38 PM

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/happypack/loader.js):
TypeError: Cannot read property 'plugins' of undefined
    at Object.HappyLoader (/[DELETED]/node_modules/happypack/lib/HappyLoader.js:15:34)

 @ multi ./node_modules/docz-core/node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Enviroment**

* OS: macOS 10.13.2
* Node/npm version: Tried with `8.9.1` and `10.4.1`

**.babelrc**

I tried deleting it and it didn't work either anyway.

```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

--- 

I hope this helps.

**Comment by pedronauck** [comment]
thanks @bichotll, I'll look this ✌️

**Comment by daveobriencouk** [comment]
Hey, I'm experiencing an identical issue. It throws ups on happypack, and specifically:

`TypeError: Cannot read property 'plugins' of undefined`

We're using **Babel 6** and **Webpack 3**, have tried using `docz-plugin-babel6` - I've also tried updating Babel and Webpack with no luck.

I'm on:

- OS: macOS 10.13
- Node/npm version: 8.11.3

Will take another look over the course of the week

**Comment by marceloavf** [comment]
Sorry @daveobriencouk but docz only works with `webpack 4+`, mainly to resolve performance issues.
