### ISSUE TITLE
Question: implement theme selector for component styling

### ISSUE THREAD

**Issue by jochienabuurs** [pedronauck/docz#627]
## Implement theme selector for component styling

When building a component library, it is often necessary for components to be easily themable.

F.e. when using styled components with Storybook, Storybook has a [package]( https://www.npmjs.com/package/storybook-theme-switcher) that adds a theme switcher to the interface.

It would be nice if we could build such functionality inside docz. I suppose this would be possible with a plugin. Are there people here that want to discuss this option, and how to approach it?

Thanks

**Comment by weslleyaraujo** [comment]
I am working on a library with the same requirements actually 😅

Not sure how easy is to approach a theme switcher that will be flexible enough to work with different theme provider api's...

Was thinking of building my own [custom docz component](https://www.docz.site/documentation/components-api) (like a `<Menu />` for example) and implement it there

**Comment by pedronauck** [comment]
Something that you can @jochienabuurs is create some wrapper using `wrapper` property on your `doczrc` and render floating in the screen your theme switcher. Together with the floating switcher pass your provider that select between one theme or another.

Btw, you can create your own theme too 🤷‍♂️
