### ISSUE TITLE
Cant load Component with *.css import

### ISSUE THREAD

**Issue by meetromb** [pedronauck/docz#629]
## Bug Report

`docz dev` throwing error, when css styles imported directly into component js file:

```shell
Failed to compile.

./src/components/Button/index.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .button-v1 {
|     border-radius: 20px;
|     font-family: 'roboto_medium';
```
![code](https://user-images.githubusercontent.com/34175623/52704720-47551600-2f92-11e9-8b3e-7ba1a18d28f3.png)
![code2](https://user-images.githubusercontent.com/34175623/52704723-4b813380-2f92-11e9-98bf-084907bf9d05.png)

**Comment by hastebrot** [comment]
I guess you need to modify the webpack configuration.

In `doczrc.js`:
~~~js
  modifyBundlerConfig: bundlerConfig => {
    const rules = [
      {
        test: /\.css$/,
        loader: "style-loader!css-loader"
      }
    ];
    bundlerConfig.module.rules.push(...rules);
    return bundlerConfig;
  }
~~~

In `package.json`:
~~~json
  "devDependencies": {
    "css-loader": "^2.1.0",
    "style-loader": "^0.23.1"
  }
~~~

Documentation: https://www.docz.site/documentation/project-configuration#build-pipeline

**Comment by meetromb** [comment]
> I guess you need to modify the webpack configuration.
> 
> In `doczrc.js`:
> 
> ```js
>   modifyBundlerConfig: bundlerConfig => {
>     const rules = [
>       {
>         test: /\.css$/,
>         loader: "style-loader!css-loader"
>       }
>     ];
>     bundlerConfig.module.rules.push(...rules);
>     return bundlerConfig;
>   }
> ```
> 
> In `package.json`:
> 
> ```json
>   "devDependencies": {
>     "css-loader": "^2.1.0",
>     "style-loader": "^0.23.1"
>   }
> ```
> 
> Documentation: https://www.docz.site/documentation/project-configuration#build-pipeline

Yep, its working. Thank you)

**Comment by raikusy** [comment]
I tried the above sollution, it didn't work. I am using docz with a rollup config. Check this branch [docz-css](https://github.com/raikusy/react-components-library/tree/docz-css).
I am also getting the same error with docz-plugin-css
![image](https://user-images.githubusercontent.com/4938039/58401928-e5bc4180-8080-11e9-97b5-4b47cb242156.png)
![image](https://user-images.githubusercontent.com/4938039/58401944-f1a80380-8080-11e9-866c-e4a17d64eba7.png)
