### ISSUE TITLE
Only getting a blank screen on installation

### ISSUE THREAD

**Issue by axhamre** [pedronauck/docz#632]
## Bug Report

**Describe the bug**

Nothing is rendered.

I created a brand new create-react-app, and installed Docz according to the docs. But I'm just getting a blank screen on `localhost:3000`.

**To Reproduce**

1. npx create-react-app my-docz-app
2. cd my-docz-app
3. yarn add docz docz-theme-default --dev
4. yarn install
5. yarn docz dev

**Comment by sw-yx** [comment]
always check your console, so you have more useful bug reports than "blank screen".

in your case i suspect you're falling to the same issue as this: https://github.com/pedronauck/docz/issues/536#issuecomment-462794127

so use the recommended patch in that issue for now.

**Comment by sw-yx** [comment]
cc @pedronauck - still need to address the webpack version issue

**Comment by axhamre** [comment]
@sw-yx Wow, thank you! Yes, this solved it:

1. Add to package.json:
`"resolutions": {
  "ansi-styles": "^3.2.0"
}`
2. Run `yarn install`

**Comment by sw-yx** [comment]
yeah :( not great i know. cant even fix the docs because they currently fail to build.
