### ISSUE TITLE
when version 14.0 publish?

### ISSUE THREAD

**Issue by HadeAs** [pedronauck/docz#633]
## Question

**Description**
*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by wldcordeiro** [comment]
Yeah, considering that `0.13.x` just blows up for me I've been stuck on the `0.12.x` releases and would love to know!

**Comment by sw-yx** [comment]
you can follow the branch here - https://github.com/pedronauck/docz/tree/v0.14

**Comment by pedronauck** [comment]
Soon guys, soon I'll have a release with great features :pray:
