### ISSUE TITLE
What are the required versions of react, webpack and babel to run?

### ISSUE THREAD

**Issue by vashi38** [pedronauck/docz#641]
## What are the required versions of react, webpack and babel to run?

**I am trying to bulid documentation of my components, but its giving error after I run docz dev**

![image](https://user-images.githubusercontent.com/24382280/52909239-94dfc480-32ab-11e9-8d18-3682913b2c9f.png)

My package.json
{
  "engines": {
    "npm": ">=3"
  },
  "scripts": {
    "analyze": "node ./internals/scripts/analyze.js",
    "npmcheckversion": "node ./internals/scripts/npmcheckversion.js",
    "preinstall": "npm run npmcheckversion",
    "predist": "npm run dist:clean",
    "dist": "cp -R ./build/ ./dist/",
    "dist:clean": "rimraf ./dist/*",
    "prebuild": "npm run build:clean",
    "build": "cross-env NODE_ENV=production DEBUG=webpack-build:* webpack --config internals/webpack/webpack.prod.babel.js --color -p --display-error-details --progress",
    "build:testing": "npm run prebuild && cross-env NODE_ENV=testing webpack --config internals/webpack/webpack.testing.babel.js --color --progress",
    "build:development": "npm run prebuild && cross-env NODE_ENV=development webpack --config internals/webpack/webpack.testing.babel.js --color --progress",
    "build:qa": "npm run prebuild && cross-env NODE_ENV=qa webpack --config internals/webpack/webpack.qa.babel.js --color --progress",
    "build:clean": "rimraf ./build/*",
    "build:dll": "node ./internals/scripts/dependencies.js",
    "start": "cross-env NODE_ENV=development node server",
    "start:tunnel": "cross-env NODE_ENV=development ENABLE_TUNNEL=true node server",
    "start:production": "npm run build && npm run start:prod",
    "start:prod": "cross-env NODE_ENV=production node server",
    "start:testing": "cross-env NODE_ENV=testing node server",
    "start:qa": "cross-env NODE_ENV=qa node server",
    "pagespeed": "node ./internals/scripts/pagespeed.js",
    "presetup": "npm i chalk",
    "setup": "node ./internals/scripts/setup.js",
    "postsetup": "npm run build:dll",
    "clean": "shjs ./internals/scripts/clean.js",
    "generate": "plop --plopfile internals/generators/index.js",
    "lint": "npm run lint:js && npm run lint:css",
    "lint:eslint": "eslint --ignore-path .gitignore --ignore-pattern internals/scripts --ignore-pattern app/vendor",
    "lint:js": "npm run lint:eslint -- . ",
    "lint:css": "stylelint ./app/**/*.css",
    "lint:staged": "lint-staged",
    "pretest": "npm run lint",
    "test": "cross-env NODE_ENV=test karma start internals/testing/karma.conf.js --single-run",
    "test:watch": "npm run test -- --auto-watch --no-single-run",
    "test:firefox": "npm run test -- --browsers Firefox",
    "test:safari": "npm run test -- --browsers Safari",
    "test:ie": "npm run test -- --browsers IE",
    "coveralls": "cat ./coverage/lcov/lcov.info | coveralls",
    "docz:dev": "docz dev",
    "docz:build": "docz build"
  },
  "lint-staged": {
    "lint:eslint": "*.js",
    "stylelint": "*.css"
  },
  "pre-commit": "lint:staged",
  "babel": {
    "presets": [
      "es2015",
      "react",
      "stage-0"
    ],
    "plugins": [
      "jsx-control-statements"
    ],
    "env": {
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements"
        ]
      }
    }
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "plugins": [
      "jsx-control-statements"
    ],
    "extends": [
      "airbnb",
      "plugin:jsx-control-statements/recommended"
    ],
    "env": {
      "browser": true,
      "node": true,
      "mocha": true
    },
    "rules": {
      "max-len": 0,
      "indent": [
        "warn",
        4
      ],
      "react/jsx-indent": [
        "warn",
        4
      ]
    },
    "settings": {
      "import/resolver": {
        "webpack": {
          "config": "./internals/webpack/webpack.test.babel.js"
        }
      }
    }
  },
  "stylelint": {
    "extends": "stylelint-config-standard",
    "rules": {
      "color-hex-case": "upper",
      "string-quotes": "single",
      "font-family-name-quotes": "always-where-recommended",
      "selector-pseudo-class-no-unknown": [
        true,
        {
          "ignorePseudoClasses": [
            "global"
          ]
        }
      ],
      "indentation": 4
    }
  },
  "dllPlugin": {
    "path": "node_modules/react-boilerplate-dlls",
    "exclude": [
      "chalk",
      "compression",
      "cross-env",
      "express",
      "ip",
      "minimist",
      "sanitize.css"
    ],
    "include": [
      "core-js",
      "lodash",
      "eventsource-polyfill"
    ]
  },
  "dependencies": {
    "async": "^2.0.1",
    "axios": "^0.12.0",
    "babel-cli": "^6.26.0",
    "babel-polyfill": "^6.7.4",
    "babel-runtime": "^6.26.0",
    "browser-cookies": "^1.0.8",
    "chalk": "^1.1.3",
    "classnames": "^2.2.5",
    "codemirror": "^5.37.0",
    "compression": "^1.7.2",
    "copy-to-clipboard": "^3.0.5",
    "debounce": "^1.0.0",
    "deepmerge": "^1.4.4",
    "eslint-plugin-jsx-control-statements": "^2.1.1",
    "express": "^4.16.3",
    "express-http-proxy": "^0.7.3",
    "fontfaceobserver": "^1.7.1",
    "google-maps-api": "^2.0.1",
    "highcharts": "^5.0.2",
    "history": "^2.1.0",
    "html-entities": "^1.2.0",
    "immutable": "^3.8.1",
    "ion-rangeslider": "^2.1.6",
    "ip": "^1.1.2",
    "is-base64": "0.0.5",
    "jquery": "^3.0.0",
    "jsonp": "^0.2.0",
    "jsx-control-statements": "^3.1.5",
    "lodash-es": "^4.14.2",
    "minimist": "^1.2.0",
    "moment": "^2.22.2",
    "nouislider": "^10.1.0",
    "numeral": "^1.5.3",
    "rc-slider": "8.6.1",
    "rc-tree": "^1.5.0",
    "react": "^15.3.2",
    "react-addons-pure-render-mixin": "^15.3.0",
    "react-addons-shallow-compare": "^15.2.1",
    "react-block-ui": "^1.0.3",
    "react-bootstrap": "^0.32.3",
    "react-bootstrap-switch": "^15.5.1",
    "react-codemirror": "^1.0.0",
    "react-codemirror2": "^5.0.1",
    "react-contenteditable": "^2.0.7",
    "react-copy-to-clipboard": "^4.2.3",
    "react-countup": "^1.1.8",
    "react-custom-properties": "^1.2.0",
    "react-datetime": "^2.8.10",
    "react-dom": "^15.0.1",
    "react-dropzone": "^3.6.0",
    "react-ellipsis-with-tooltip": "^1.0.8",
    "react-helmet": "^5.2.0",
    "react-highcharts": "^11.0.0",
    "react-image-crop": "^4.0.1",
    "react-input-range": "^1.2.1",
    "react-loaders": "^2.5.0",
    "react-maskedinput": "^3.3.4",
    "react-notification": "^6.5.0",
    "react-nouislider": "^2.0.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.0",
    "react-router-redux": "^4.0.4",
    "react-router-scroll": "^0.2.0",
    "react-select": "^1.0.0-beta14",
    "react-slidez": "0.0.28",
    "react-star-rating-component": "^1.2.4",
    "react-switch": "^2.3.0",
    "react-tagcloud": "^1.0.0",
    "react-tooltip": "^3.2.2",
    "react-truncate": "^2.3.0",
    "react-ultimate-pagination": "^1.2.0",
    "react-ultimate-pagination-bootstrap-3": "^1.1.0",
    "react-virtualized": "^8.4.0",
    "redux": "^3.5.2",
    "redux-form": "^5.3.1",
    "redux-immutable": "^3.0.6",
    "redux-saga": "^0.16.2",
    "reselect": "^2.5.1",
    "sanitize.css": "^3.3.0",
    "spinkit": "^1.2.5",
    "styled-components": "^2.1.1",
    "url": "^0.11.0",
    "url-join": "^1.1.0",
    "validator": "^10.4.0",
    "webpack-remove-serviceworker-plugin": "^1.0.0",
    "whatwg-fetch": "^1.0.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^6.0.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-transform-react-constant-elements": "^6.8.0",
    "babel-plugin-transform-react-inline-elements": "^6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.2.7",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-0": "^6.5.0",
    "chai": "^3.5.0",
    "chai-enzyme": "^0.8.0",
    "cheerio": "^0.22.0",
    "coveralls": "^3.0.1",
    "cross-env": "^1.0.7",
    "css-loader": "^0.23.1",
    "docz": "^0.13.7",
    "docz-theme-default": "^0.13.7",
    "enzyme": "^2.2.0",
    "eslint": "^2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-import-resolver-webpack": "^0.2.4",
    "eslint-plugin-import": "^1.8.0",
    "eslint-plugin-jsx-a11y": "^1.2.0",
    "eslint-plugin-react": "^5.1.1",
    "eventsource-polyfill": "^0.9.6",
    "expect": "^1.18.0",
    "expect-jsx": "^2.5.1",
    "exports-loader": "^0.6.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.16.0",
    "image-webpack-loader": "^1.8.0",
    "imports-loader": "^0.6.5",
    "ip": "^1.1.2",
    "isparta": "^4.0.0",
    "isparta-loader": "^2.0.0",
    "json-loader": "^0.5.4",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "^1.0.1",
    "karma-coverage": "^1.1.2",
    "karma-firefox-launcher": "^1.0.0",
    "karma-ie-launcher": "^1.0.0",
    "karma-mocha": "^1.0.1",
    "karma-mocha-reporter": "^2.0.3",
    "karma-safari-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.0",
    "lint-staged": "^1.0.2",
    "lodash": "^4.17.10",
    "minimist": "^1.2.0",
    "mocha": "^5.2.0",
    "ngrok": "2.1.8",
    "null-loader": "^0.1.1",
    "plop": "^1.5.0",
    "postcss-cssnext": "^2.5.2",
    "postcss-focus": "^1.0.0",
    "postcss-loader": "^0.9.1",
    "postcss-reporter": "^1.3.3",
    "pre-commit": "^1.1.3",
    "psi": "^3.1.0",
    "rimraf": "^2.5.2",
    "shelljs": "^0.7.0",
    "sinon": "^2.0.0-pre",
    "style-loader": "^0.13.1",
    "stylelint": "^6.3.3",
    "stylelint-config-standard": "^8.0.0",
    "url-loader": "^1.0.1",
    "webpack": "2.1.0-beta.13",
    "webpack-dashboard": "^2.0.0",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-hot-middleware": "^2.10.0"
  }
}

**Comment by giulianok** [comment]
Same here, I just ran a fresh install and started getting the error

**Comment by sw-yx** [comment]
webpack 2 is very old. your code base is probably not supported.

@giulianok pls file a diff issue if your exact error cant be foudn in other issues, pls search first
