### ISSUE TITLE
Please stop removing terminal text during build

### ISSUE THREAD

**Issue by aryzing** [pedronauck/docz#642]
## Bug Report

When running docz dev, all my terminal text gets deleted. Even warnings and intermediate errors thrown by docz get removed. 

**To Reproduce**

Run `docz dev`

**Expected behavior**

Running docz should not delete terminal text and should not hide errors or intermediate warnings during build.

**Environment**

* OS: OSX Mojave 10.14.2
* Node/npm version: [e.g. Node 11/npm 6.5.0]

**Comment by aryzing** [comment]
Also, while building the production bundle, terminal environments that don't support removing of text (like a build pipeline) end up logging hundreds (a couple thousand?) lines of output

**Comment by rdmclin2** [comment]
Can docz support an environment variable to open or close console text? I just cannot locate errors because docz hides all errors.

**Comment by pedronauck** [comment]
Fixed, will have a new option called `clearConsole` that you can use to disable the default console clear on Docz :)
