### ISSUE TITLE
docz dev fails

### ISSUE THREAD

**Issue by pkrawc** [pedronauck/docz#651]
## Bug Report

Docz won't build in development mode

**To Reproduce**

1. `npm init -y && npm i -D docz docz-theme-default`
2. `docz dev`

```shell
Failed to compile.

./node_modules/docz/dist/index.m.js 473:30
Module parse failed: Unexpected token (473:30)
You may need an appropriate loader to handle this file type.
| async function loadFromImports(path) {
|     // tslint:disable-next-line
>     const { imports } = await import('~imports');
|     const { default: Component$$1, getInitialData } = await imports[path]();
|     const ExportedComponent = props => (createElement(AsyncComponent, Object.assign({}, props, { as: Component$$1 || 'div', getInitialData: getInitialData })));
```

I would expect the tool to not fail a build with the basic, out-of-the-box setup.

**Environment**

MacOS 10.14.3 Mojave
Node 11.7.0 | NPM 6.7.0

**Comment by KingScooty** [comment]
Having exactly the same issue :/

**Comment by sw-yx** [comment]
this is a known issue: https://github.com/pedronauck/docz/issues/596#issuecomment-456288810 (and if you're using create react app, https://github.com/pedronauck/docz/issues/536#issuecomment-449601804)

unfortunately i cant fix it but its been known and a pinned issue for a while

**Comment by pkrawc** [comment]
Thanks. I'll close this in favor of keeping conversation on that thread.

**Comment by sw-yx** [comment]
cheers. sorry i dont have a better answer
