### ISSUE TITLE
Using modularized lodash packages causes security warnings in CI

### ISSUE THREAD

**Issue by kachkaev** [pedronauck/docz#668]
## Bug Report

**Describe the bug**

Modularized lodash packages like `lodash.flatten`, `lodash.get`, etc. have not been updated for a while and seem to be deprecated now. Depending on them raises security warnings by scanners in CI. Would it be possible to replace `lodash.x` with `lodash/x` in docz to avoid this?

See https://github.com/lodash/lodash/issues/4030 for background. Might be worth clicking on linked issues too for more context.

In fact, there is even no need to use `import x from "lodash/x"`. With the lodash plugins for webpack and babel, it's fine to always use `import {x} from "lodash"` and get things tree-shaken.

**Comment by pedronauck** [comment]
Thanks @kachkaev, it's done will be released today :)
