### ISSUE TITLE
The next version is V1 or V14.0, and How long will it take to post

### ISSUE THREAD

**Issue by HadeAs** [pedronauck/docz#671]
## Question

**Description**
*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by HadeAs** [comment]
@pedronauck

**Comment by HadeAs** [comment]
our project is urgent for the new version

**Comment by pedronauck** [comment]
Hi @HadeAs, the next version will be v1, but it's a pretty big release I need to be careful, so I'm making tests and write documentation, in couple weeks we'll release it :)

**Comment by HadeAs** [comment]
@pedronauck  ok thks
