### ISSUE TITLE
Typescript decorators fail to compile

### ISSUE THREAD

**Issue by yinonov** [pedronauck/docz#672]
## Bug Report

**Describe the bug**

> Support for the experimental syntax 'decorators-legacy' isn't currently enabled

on a stencil components project:
trying to run `docz dev --typescript` keep throwing that error above while .tsconfig in root folder clearly has _experimentalDecorators_ set to true in its compiler options.

also tried solving the issue unsuccessfully with creating & setting typescript options in _doczrc.js_ but it's not clear where to place that file or address it, root directory I assume. 
should we maybe extend the .tsconfig file in folders containing .mdx files?

p.s
when serving the docz as mentioned above, the command line shows
```shell
Creating app... 1 ms
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
```

not clear why it refers babel when the typescript flag is on

**Comment by pedronauck** [comment]
Closed in the newest version.
