### ISSUE TITLE
Redux Connected Component

### ISSUE THREAD

**Issue by Swapnull** [pedronauck/docz#68]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When trying to document a redux connected component, a store must be provided via the `<Provider>` eg. 
```javascript
<Provider store={createStore()}>    
    <ConnectedComponent/>
</Provider>
```
This means that when wrapping in the playground, the <Provider> is output in the code example.

**Describe the solution you'd like**
A new container that allows the component output and code output to be defined separately. 
```js
<Provider store={createStore()}>    
    <ConnectedComponent/>
</Provider>

<Code>
    <ConnectedComponent />
</Code>
```
**Describe alternatives you've considered**
- A configuration option that allows you to strip certain tags
` export default { ignoreTags: ['Playground', 'Provider'] } `
- An inline option to remove tags 
```js
<Provider store={createStore()} doczDisplay={false}>    
    <ConnectedComponent/>
</Provider>
```

**Comment by pedronauck** [comment]
hey @Swapnull you can use the [wrapper property](https://www.docz.site/documentation/project-configuration#theming) to set up a component that will wrap your entire application:

```js
// doczrc.js
export default {
  wrapper: 'src/MyWrappedComponent'
}
```

Does this solve your problem?

**Comment by Swapnull** [comment]
@pedronauck That seems to sort it for me. Will close in favour of #75
