### ISSUE TITLE
Hamburger button doesn't work when browser dev tools reduce size of viewport

### ISSUE THREAD

**Issue by mplis** [pedronauck/docz#693]
## Bug Report

**Describe the bug**

I'm using `v1.0.0-rc.3`.

If I'm viewing my docs and I open the Chrome dev tools pinned to the right side of the screen, it reduces the viewport size to less than 1120px, so the hamburger menu shows up, but clicking it doesn't do anything.

**To Reproduce**

1. Open a docz-generated site
2. Open browser dev tools pinned to the right and increase size of dev tools window until viewport width is less than 1120px
3. Attempt to click on hamburger menu to view sidebar

Here's a test repo: https://github.com/mplis/docz-test

Check out the repo, run `yarn docs`, and open generated site to reproduce the bug.

**Expected behavior**

I expect the hamburger menu to open the sidebar

**Environment**

* OS: OSX 10.13.6
* Node/npm version: Node 10.15.1, Yarn 1.13.0

**Comment by Glazy** [comment]
@pedronauck 

We can now close this issue because my PR ☝️ (#698) has resolved it!

**Comment by pedronauck** [comment]
Yeah, for sure, but it's not release yet, will be in the next rc :)
