### ISSUE TITLE
 React does not recognize the `activeClassName` prop on a DOM element. 

### ISSUE THREAD

**Issue by hannadrehman** [pedronauck/docz#703]
## Bug Report

**Describe the bug**

I am not able to run docz, it keeps on giving react warnings. and components don't load.

```React does not recognize the `activeClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activeclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

```React does not recognize the `partiallyActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `partiallyactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

because of these issues I get broken UI in the preview app

**Environment**

* OS: OSX 10.14.3
* Node/npm version: Node v11.11.0 / npm 6.7.0
* docz: 1.0.0-rc.3,
* docz-theme-default :  1.0.0-rc.3,
* react :  16.8.4,
* react-dom : 16.8.4
* antd: 3.15.1

**Comment by cupofjoakim** [comment]
In the same boat, i'd love if this got some attention.

**Comment by pedronauck** [comment]
This is fixed, I'll release some new version today :)
