### ISSUE TITLE
update to the new version 1.0.0-rc.3, and the page content can not show

### ISSUE THREAD

**Issue by HadeAs** [pedronauck/docz#710]
## Question
![图片](https://user-images.githubusercontent.com/12652964/54880504-21b80800-4e80-11e9-843c-897bef385e66.png)

**Description**
*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by rfoel** [comment]
Can you share the repository?

**Comment by alanrsoares** [comment]
I'm experiencing the same issue with https://re-reduced.netlify.com, https://github.com/alanrsoares/re-reduced

**Comment by HadeAs** [comment]
@pedronauck do you know what problem cause this situation

**Comment by ivan-dalmet** [comment]
Same problem here 😢

**Comment by ivan-dalmet** [comment]
@pedronauck I made a example to reproduce the bug.
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-710

**Comment by ivan-dalmet** [comment]
@pedronauck I made an example with the problem.
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-710

**Comment by ivan-dalmet** [comment]
I just update the repo with more examples
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-710

**For now what I found:**
❌Mdx files are at the root of the project.
❌Folder with mdx files is **not** named `src` and is **not** the first folder after `.docz`.
✅Folder with mdx files is named `src`.
✅Folder with mdx files is **not** named `src` but is **the first folder** after `.docz`.

**Comment by ivan-dalmet** [comment]
I just test on our project, we rename the `docs` folder into `src`. It's a workaround that works!

**Comment by HadeAs** [comment]
> I just test on our project, we renamed our `docs` folder into `src`. It's a workaround that works!

this is my project folder, is it right?

<img width="346" alt="20190326192341" src="https://user-images.githubusercontent.com/12652964/54993379-a2037800-4ffc-11e9-8984-886ae6169174.png">

**Comment by pedronauck** [comment]
This is awkward @ivan-dalmet, since the default `source` folder is the root of the project. Did you have any setting related to that on your `doczrc`?

**Comment by ronghang** [comment]
When I use `base` prop in doczrc.js , have occurred the same problem.

**Comment by goldins** [comment]
@ivan-dalmet I just cloned your repo and found that `ko-2` was the only one that worked properly for me.

**Comment by goldins** [comment]
@ivan-dalmet I cloned your repo and found that `yarn && yarn serve` works intermittently... After cloning, removing and re-cloning a few times, it seems to work the first time, but then running `yarn && yarn serve` again exhibits the problem, even when running `rm -rf .docz` beforehand. `ko-1` and `ko-2` seemed to have the same behavior (i.e. they worked fine the first time around). Can you see if you can reproduce this with your repo?

Steps I took:
```sh
git clone git@github.com:ivan-dalmet/docz-issue-sandbox.git
cd docz-issue-sandbox/issue-710
```

```sh
cd ok-1 # as an example. Try it with all four if you can.
yarn && yarn serve
# [ctrl - c] after verifying that the application serves properly
rm -rf ./docz
yarn && yarn serve
# Seeing the same "Page Not Found" here
```

```sh
cd ../../../
rm -rf docz-issue-sandbox
git clone git@github.com:ivan-dalmet/docz-issue-sandbox.git
...
```

@pedronauck: it seems like this might be another bug.

**Comment by pedronauck** [comment]
fixed, I'll release some new release candidate today :v:
