### ISSUE TITLE
Props components not working with default exports in 1.0.0-rc.3

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#717]
The Props component doesn't display anything :(
It's working in the docz basic example but not with an external fresh new install from npm.

**Repo with the example**
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-717

Docz: 1.0.0-rc.3
Node: 10.13.0
Yarn: 1.15.2

**Comment by ivan-dalmet** [comment]
Just add a working example in the repo... but no idea why it works 😢

If someone has a clue...

**Comment by ivan-dalmet** [comment]
Found why... it doesn't work with default exports 😢

**Comment by ivan-dalmet** [comment]
@pedronauck an idea why?

**Comment by pedronauck** [comment]
Hi @ivan-dalmet, I'm digging into this today to see what's happening. I have an idea I think.

**Comment by pdoongarwal** [comment]
For me it is not working with named exports also. Any update on how to fix this?

**Comment by lesha1201** [comment]
@ivan-dalmet @pedronauck Problem is in `babel-plugin-export-metadata`. It doesn't add `__filemeta` in case of `export default`. I've fixed `babel-plugin-export-metadata` but I need to fix some other things. I think I'll finish tommorow

**Comment by JackCuthbert** [comment]
FWIW I'm having issues in rc7 with `Props` not rendering anything at all while _not_ using default exports with TypeScript enabled.

![image](https://user-images.githubusercontent.com/5564612/55455179-5a996f00-562e-11e9-88bf-7560fee6435e.png)

Component looks something like:

```jsx
export const MyComponent: React.FunctionComponent<Props> = (props) => {
  return (
    // ...
  )
}
```

**Comment by nikitapavets** [comment]
I have the same issue

**Comment by rakasiwi23** [comment]
I have the same issue too

**Comment by pedronauck** [comment]
Fixed, will be released in the next version ✅
