### ISSUE TITLE
www.docz.site does not load in FireFox

### ISSUE THREAD

**Issue by tim-field** [pedronauck/docz#720]
## Bug Report

**Describe the bug**

https://www.docz.site does not load in FireFox

![image](https://user-images.githubusercontent.com/1326910/54958275-11a44380-4fba-11e9-907d-076a97a9f45e.png)

Above errors in the console, using latest FF version 66

**Comment by macklinu** [comment]
Duplicate of https://github.com/pedronauck/docz-website/issues/50

**Comment by tim-field** [comment]
Closing as duplicate
