### ISSUE TITLE
docz build with --base not working in 1.0.0-rc.3

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#722]
## Bug Report

`docz build --base /base/path` not working properly in in 1.0.0-rc.3
The navigation links do not use `/base/path` as supposed.

**Repo with the example**
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-722

Docz: 1.0.0-rc.3
Node: 10.13.0
Yarn: 1.15.2

**Comment by minhcasi** [comment]
I've got the same issues, looking forward to getting new release with this fix

**Comment by ivan-dalmet** [comment]
Solved in 1.0.0-rc.5 :)
