### ISSUE TITLE
Docz build is not working for 1.0.0-rc.3

### ISSUE THREAD

**Issue by mitul45** [pedronauck/docz#731]
## Bug Report
The `yarn docz:build` generates the bundle successfully but it's broken (there are no components on the sidebar).

**Describe the bug**
I was able to write documentation in dev environment using `yarn docz:dev` but when I tried to generate a build to host this on a static file server, the rendered didn't have any components.

*A clear and concise description of what the bug is.*
It looks like this in dev:
![image](https://user-images.githubusercontent.com/6790325/55087710-ce75cd80-50aa-11e9-8bed-3506d229c6b8.png)

Compared to this (after creating the production build):
![image](https://user-images.githubusercontent.com/6790325/55087484-7a6ae900-50aa-11e9-903e-d242bd3d8c0d.png)

**To Reproduce**
1. Write a couple of `.mdx` file(s)
1. Check if it's working – run `yarn docz:dev` and see it in the browser
1. Create production build – `yarn docz:build`
1. Check the generated bundle:
    ```sh
    cd .docz/dist
    python -m SimpleHTTPServer
    ```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*
It's internal repo, can't provide a link

**Expected behavior**
Should generate the bundle similar to dev environment. When I switched the docz version to `0.13.7` the same setup worked fine.

**Environment**

* OS: OSX 10.14.3
* yarn version: 1.13.0

**Comment by ivan-dalmet** [comment]
Almost same as #710

I made a repo with this problem
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-710

**Comment by ivan-dalmet** [comment]
@mitul45 can you show the `doczrc.js` content (if you use one) and your project folder organisation?

**Comment by mitul45** [comment]
Folder structure:
```
src
 |--components
        |-- component.jsx
        |-- otherComponent.jsx
docs
 |-- component.mdx
 |-- otherComponent.mdx
```

Config:
```js
export default {
  codeSandbox: false,
  themeConfig: {
    showPlaygroundEditor: true,
    codemirrorTheme: 'docz-dark'
  },
  modifyBundlerConfig: config => {
    config.module.rules.push({
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    });

    return config;
  }
};
```

**Comment by ivan-dalmet** [comment]
@mitul45 is it working if you put the `docs` folder inside the `src` folder?

**Comment by mitul45** [comment]
Nope, having the same issue.

**Comment by cupofjoakim** [comment]
Experiencing the same issue. Working like a charm in dev, but the built one does not. Looking in the build `/static/js/` folder it does seem like it has built the files for the different pages, so the routing in itself seems to be the issue.

**Comment by elv1n** [comment]
I believe this will be resolved after publishing a new version with fix https://github.com/pedronauck/docz/pull/725

**Comment by cupofjoakim** [comment]
@elv1n Can we confirm this?

**Comment by elv1n** [comment]
@cupofjoakim I had the same problem and while waiting for a new release I published the package with the fix to '@elv1n/docz-core'.
Feel free to install it and check if fix works for you
```
// fakeDocz.js
#!/usr/bin/env node
require('@elv1n/docz-core').cli()
```

and run `node ./fakeDocz build`

**Comment by cupofjoakim** [comment]
@elv1n Partially worked. Still getting "Page Not Found", but some menu items are atleast rendering. Links to the stuff declared "Menu" in doczrc.js are rendered, but not navigatable. Child pages fetched from a different folder still isn't showing up.

**Comment by pedronauck** [comment]
Hi guys, can you check which version of `docz-core` are installed? Btw, I'm getting some fixes and today I'll release a new release candidate version.

**Comment by pedronauck** [comment]
Fixed in the newest release candidate :)

**Comment by cupofjoakim** [comment]
Hey @pedronauck, thanks a bunch for solving this so quickly, super nice!

**Comment by mitul45** [comment]
Thank you for the help, everyone!

**Comment by michaelw85** [comment]
I don't think this issue is resolved.

I just did a fresh rc7 setup and I'm getting a page not found. When using the navigation I end up going to 'http://src-hello-world-hello-world/' moving away from the docz page.

File structure:
```
| -- .docz
| --  src
       | -- hello-world
             | -- hello-world.mdx
```

mdx content
```mdx
---
name: Hello world
---

# Hello world
```

**Comment by cupofjoakim** [comment]
I'm also still getting "Page not found".

**Comment by michaelw85** [comment]
@cupofjoakim I found another issue where someone mentioned adding a route to the meta data for the homepage. I got a basic setup working now after applying this change + #747 

```mdx
---
name: Hello world
route: /
---

# Hello world
```

**Comment by yyynnn** [comment]
yeah routes are broken too in rc7 


route: '/some_route' will result in http://some_route
