### ISSUE TITLE
Error when using react-router-dom@5.0.0

### ISSUE THREAD

**Issue by timbergus** [pedronauck/docz#732]
## Bug Report

**Describe the bug**

I had Docz working perfectly until today using __react-router-dom@4.3.1__, but when I updated this morning to __react-router-dom@5.0.0__, this error appears:

__TypeError: Cannot read property 'Consumer' of undefined__

**To Reproduce**

1. Download the following [example repository](https://github.com/timbergus/lazy-project/tree/error_react_router_dom_5_0_0) that I'm building, where I have found the error.
2. `yarn`
3. `yarn docz:dev`
4. Navigate to `http://127.0.0.1:3500/` to see the error.

```shell
Compiled with warnings.

./node_modules/react-router-dom/esm/react-router-dom.js
Attempted import error: '__RouterContext' is not exported from 'react-router'.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

**Expected behavior**

The same behavior I had with __react-router-dom@4.3.1__. Just work as always without any errors.

**Environment**

* OS: OSX 10.14.4.
* Node/npm version: 10.15.2 / 6.7.0.

**Additional context/Screenshots**

<img width="1039" alt="Screenshot 2019-03-27 17 18 00" src="https://user-images.githubusercontent.com/1750734/55093203-4dbbcf00-50b4-11e9-8cd3-3184f033fb83.png">

Thanks in advance

**Comment by pedronauck** [comment]
Hey dude, we are no longer supporting `0.137`, try to update :)

**Comment by timbergus** [comment]
Hi @pedronauck. Thanks a lot for your help. I'm using a Visual Studio plugin to maintain my packages versions (Version Lens), and I missed the notification about the RC version. Everything works now :)

**Comment by dreadrocksean** [comment]
I have the same problem but don't understand this solution.  Im using CRA.
