### ISSUE TITLE
Embedding Docz inside a Gatsby Application

### ISSUE THREAD

**Issue by patricksimonian** [pedronauck/docz#734]
## Question
Hi there, loving the direction that Docz is going into! I was just trying a quick tech spike in integrating Docz into a preexisting Gatsby application and got hung up. 

My goal was to have a directory for my docz mdx files. The Gatsby build pipeline picks that up (probably with that Docz theme) and produces a Gatsby page for the Docz application.

So I could navigate to here...
https://mysite.com/documentation => and get the docz app
and navigate to here...
https://mysite.com => and get a regular gatsby page

1. Is this currently possibly?
2. If not any thoughts on this implementation (I'd understand that the entire scope is not on Docz, but perhaps a gatsby plugin could be authored)?

Thanks!

**Comment by pedronauck** [comment]
Hi @patricksimonian, you can set your `src` folder on your `doczrc` pointing to this folder that you want to, see the [configuration page](https://www.docz.site/docs/project-configuration#basic-config) for more info.
