### ISSUE TITLE
ThemeProps not an exported interface

### ISSUE THREAD

**Issue by jedmao** [pedronauck/docz#743]
## Bug Report

In following along the documentation, I write the following default export:

```ts
export default theme(themeConfig)(Theme)
```

And get the following TypeScript error:

> Default export of the module has or is using private name 'ThemeProps'.

## Version

```json
    "docz": "^1.0.0-rc.5",
    "docz-theme-default": "^1.0.0-rc.5",
```

## Work-around

Manually edit `theme.d.ts` to export the `ThemeProps` interface:

```ts
export interface ThemeProps {
    db: Database;
    wrapper?: CT;
    linkComponent?: CT;
    children(WrappedComponent: CT): JSX.Element;
}
```

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
