### ISSUE TITLE
Issue with route on Windows

### ISSUE THREAD

**Issue by lesha1201** [pedronauck/docz#747]
## Bug Report

**Describe the bug**

After upgrading to version `^1.0.0-rc.5`, I have an issue with links in documentation on Windows 10 - all links in the format: `/\:slug\`. So when I click on such a link I go to `:slug/` instead of `localhost:3000/:slug/`

**To Reproduce**

1. Start the development server of `docz`
2. Open it in the browser
3. Click on any link

**Expected behavior**

I found that you are using `path.join` in generating route (Entry). I think you should not use it because it converts automatically on Windows symbol `/` to `\\`

I think this (core\docz-core\src\lib\Entry.ts):

```ts
private getRoute(parsed: any, base: string): string {
  const parsedRoute = get('route', parsed)
  const route = parsedRoute || `/${this.slug}`
  return path.join(base, route)
}
```
should be:

```ts
private getRoute(parsed: any, base: string): string {
  const parsedRoute = get('route', parsed)
  const route = parsedRoute || `/${this.slug}`
  return path.posix.join(base, route)
}
```

**Environment**

* OS: Windows 10
* Node/npm/yarn version: node 10.14.0, npm 6.9.0, yarn 1.13.0
* docz: 1.0.0-rc.5 (also in 1.0.0-rc.7)

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/10157660/55313325-2e37f400-5470-11e9-81ea-5304b28f2491.png)

![image](https://user-images.githubusercontent.com/10157660/55314675-4bba8d00-5473-11e9-89e9-e4681bbf12e0.png)

**Comment by michaelw85** [comment]
I am also running into this issue and can confirm this code change fixes the issue for me.

**Comment by pedronauck** [comment]
Merged, will be released soon
