### ISSUE TITLE
Allow `<Playground>` inside elements

### ISSUE THREAD

**Issue by fzaninotto** [pedronauck/docz#75]
## Feature Request

To hide the required context for my element, I'ld like to write the following mdx:

```jsx
<Provider store={createStore(() => ({}))}>
  <Playground>
    <MyButton />
  </Playground>
</Provider>
```

But in that case, the `Playground` component doesn't work. It forces me to put the context inside playground, which leads to large example code with unrelated elements.

```jsx
<Playground>
  <Provider store={createStore(() => ({}))}>
    <MyButton />
  </Provider>
</Playground>
```

I know I can define a `wrapper` inside `doczrc.js`, but I'm documenting a large project with several different contexts, so a single wrapper is not an option.

Somehow related to #68.

**Comment by pedronauck** [comment]
In the [v0.2.8](https://github.com/pedronauck/docz/releases/tag/v0.2.8) we update the mdx version. In the new version of mdx you can [export a default](https://github.com/mdx-js/mdx#export-default) component that will be the wrapped component of your document. Maybe you can use this to setup your provider, what do you think?

```markdown
---
name: Custom Document
---

import { Playground } from 'docz'
import { CustomLayout, Provider, MyButton } from './components'

export default ({ children, ...props }) => (
  <Layout {...props}>
    <Provider>
      {children}
    </Provider>
  </Layout>
)

# Hello world

<Playground>
  <MyButton>ClickMe</MyButton>
</Playground>
```

**Comment by fzaninotto** [comment]
That works if all the code samples in a given page use the same context. But not if they need custom contexts...

**Comment by pedronauck** [comment]
Ok, I'll see that ✌️

**Comment by pedronauck** [comment]
✅Fixed using `wrapper` property on [v0.7.0](https://github.com/pedronauck/docz/releases/tag/v0.7.1)

**Comment by johnnycopperstone** [comment]
I tried adding doing something similar by adding a wrapper around Playground and exporting that globally to be used in each of the .mdx files. 

```
// themed-playground.js
import { MyTheme } from 'somewhere' 
import { Playground } from 'docz'
export default (props) => (
  <Playground
     wrapper={ MyTheme }>
      { props.children }
  </Playground>
)
```

so that in each of my .mdx files I can just import this directly instead of Playground:

```
// random.mdx
import MyPlayground from './themed-playground'
<MyPlayground>
  <div>yeah!</div>
</MyPlayground>
```

But it doesn't seem to like the fact that I'm not using Playground directly in the .mdx file. Would you expect this to work?

**Comment by pedronauck** [comment]
You need to call your component as `Playground` instead of `MyPlayground` @johnnycopperstone, try that way!

**Comment by johnnycopperstone** [comment]
I just tried that, unfortunately didn't work either. I get this error thrown:

![screenshot 2018-11-22 at 12 44 07](https://user-images.githubusercontent.com/1838917/48903810-7c027700-ee54-11e8-97a0-d8ff9f23292c.png)

For reference, these are my files:

```
---
name: BladeList
menu: Blade
---

# BladeList

## Prop Types

import { PropsTable } from 'docz'
import Playground from '../provided';
import BladeListFull, { BladeList } from './'

<PropsTable of={ BladeList } />

## Usage

<Playground>

    <BladeListFull
      listTitle={ 'The List' }
      list={[
        {
          label: 'Home insurance',
          value: 'Very hard'
        },
        {
          label: 'Car insurance',
          value: 'See more',
          moreDetails: 'All of the details.'
        }
      ]} />

</Playground>
```

and the `provided.js` file is:

```
```

**Comment by johnnycopperstone** [comment]
I managed to get around this by using the `wrapper` property in [the project configuration](https://www.docz.site/documentation/project-configuration) file.

 🤜 🤛

**Comment by huchenme** [comment]
@pedronauck could you provide some code example of using `<Playground wrapper />`? I get exactly same error as @johnnycopperstone got: `toString` undefined

**Comment by johnnycopperstone** [comment]
hey @huchenme, this is my setup:

I set up a component file which has the wrapper:

```js
export default ({ children }) => (
  <MyComponentOrPlayground prop={ any }>
    { children }
  </MyComponentOrPlayground>
)
```

and reference this in your `doczrc`

```js
export default {
  ...,
  wrapper: 'path/to/my/playground/wrapper'
}
```

**Comment by victorcabeceira** [comment]
Hi, in case it helps anyone, that's how I got around.

doczrc.js configuration
```
//doczrc.js (on root)

export default {
  src: './src',
  wrapper: 'src/wrapper',
  ...
}
```
```
// wrapper.js (on ./src)

import React from 'react';
import { Provider } from 'react-redux';
import { createStore } from 'redux';


export default ({ children }) => (
  <Provider store={createStore()}>
    { children }
  </Provider>
);

```

Then, just proceed with your docz documentation
```
// component.mdx

import { Playground, Props } from 'docz';
import Component from './path-to-component';

<Playground>
  <Component />
</Playground>
```
