### ISSUE TITLE
Playground display bug when editing code

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#752]
When editing the code in the Playground, the rendering display the code with 1 input late.

![docz-playground-edition-bug](https://user-images.githubusercontent.com/9749061/55345680-d1106280-54b0-11e9-9ea3-05d40d16a65e.gif)

If anyone get any idea why, I'm trying to figure out why but right now I found no clue :/

**Comment by ivan-dalmet** [comment]
I think it's might be a bug from `react-live` and not from `docz`.

**Comment by ivan-dalmet** [comment]
Confirmed. Rolling back from 2.0.0 to the the 1.12.0 of react-live fix the issue.

@pedronauck any new feature that we need in 2.0.0 or we can rollback for now until the bug is fixed in react-live?

**Comment by ivan-dalmet** [comment]
(react-live issue: https://github.com/FormidableLabs/react-live/issues/13)

**Comment by pedronauck** [comment]
I think not @ivan-dalmet, we can rollback until the fix!

**Comment by pedronauck** [comment]
Fixed, will be released soon!
