### ISSUE TITLE
v1.0-RC7 not ignoring README.md files

### ISSUE THREAD

**Issue by jedmao** [pedronauck/docz#753]
## Bug Report

v1.0-RC7 not ignoring README.md files
https://github.com/jedmao/queso

**Comment by jedmao** [comment]
I put up a PR request that manually ignores `CONTRIBUTING.md` and `README.md` (all caps), but it still doesn't work, as you can well see by the "Readme" menu item.

https://github.com/jedmao/queso/pull/15
https://5ca2757b860cff0008c214f7--quesojs.netlify.com/

**Comment by pedronauck** [comment]
Pr merged :v: thanks @jedmao
