### ISSUE TITLE
Using Custom Webpack Config and react-svg-loader

### ISSUE THREAD

**Issue by yakovkhalinsky** [pedronauck/docz#755]
## Question

**Using Custom Webpack with react-svg-loader**
I have setup a `doczrc.js` and added my module aliases, but now I am running into an error where I am using `react-svg-loader` to load SVG files setup with my existing webpack.

I have tried to add my loader rule that I have in my `webpack.config.js` for SVGs but it still causes an error.

`doczrc.js` extract:
```
  [
      {
        loader: 'babel-loader',
      },
      {
        loader: 'react-svg-loader',
        options: {
          jsx: true,
        },
      },
    ]
```

My first attempt was to `config.module.rules.push`, and then I tried replacing the `use` part in the existing `config.module.rules` that was testing for SVGs.

Neither seems to solve the issue. So I am struggling to resolve this. I'm open to suggestions.

![image](https://user-images.githubusercontent.com/646086/55379254-2fe4e300-5568-11e9-8e3e-2d5a93a74fe1.png)

**Comment by pedronauck** [comment]
Try to use `onCreateWebpackChain` method instead of `modifyBundler`, can be easy to do that:

```js
export default {
  onCreateWebpackChain: config => {
    config.module
      .rule('js')
      .use('svg-loader')
        .loader('react-svg-loader')
        .options({ jsx: true })
  }
}
```

**Comment by yakovkhalinsky** [comment]
Thanks, that seems to now use the `react-svg-loader`but the SVG file going through that loaderis now causing an error:
![image](https://user-images.githubusercontent.com/646086/55436376-da501b00-55e7-11e9-9cd1-45466fc7a2b4.png)

Perhaps it's conflicting with the existing loader.

**Comment by yakovkhalinsky** [comment]
I will try a few things and see if I can resolve this.

Will post back here when I find the solution.

**Comment by yakovkhalinsky** [comment]
Just reporting back, seems like I couldn't use `react-svg-loader` but instead I replaced the `file-loader` in the webpack config as in this issue https://github.com/pedronauck/docz/issues/169 and that fixed all my errors 👍
