### ISSUE TITLE
Following "Getting Started" guide yields "Page Not Found" and links are wrong

### ISSUE THREAD

**Issue by snorrekim** [pedronauck/docz#757]
## Bug Report

Trying to setup docz for the first time. localhost:3000 has content, but nothing seems to work, any .mdx file I add links to non-existing pages, and the start page is just "Page Not Found Check if you haven't changed the document route or deleted it!"

**To Reproduce**

1. Start in an empty folder
2. Follow the guide on https://www.docz.site/docs/getting-started
3. Add an .mdx file "HelloWorld.mdx" in root following the guide
4. run "yarn docz dev"
5. go to localhost:3000 (the default page says "Page Not Found Check if you haven't changed the document route or deleted it!" is this normal?)
6. "Hello world" link appears in the menu, but it links to the page "http://hello-world/"
7. Click the "Hello world" link, navigates to non-existing page

**Expected behavior**

Should link to documentation page "Hello world"

**Environment**

* OS: Windows 10
* Node/npm version: [e.g. Node 10.15.3/npm 6.4.1]

**Additional context/Screenshots**

The html code for the "Hello world" link is like this:

    <a class="sc-iELTvK jkxbEX" href="/\hello-world">Hello world</a>

I assume the href is wrong, what is it supposed to be? If someone could give me the correct link I could at least check to see if the corerct url leads to a working page.

**Comment by pedronauck** [comment]
Fixed, will be released in the next version ✅
