### ISSUE TITLE
babel-plugin-export-metadata does not work with exports after expression

### ISSUE THREAD

**Issue by dartess** [pedronauck/docz#758]
## Bug Report

**Describe the bug**

```
export const Button = () => ();
```
works fine

```
const Button = () => ();
export {Button};
```
Property `__filemeta` is not added, consequently, `<Props>` component does not work (shows no properties). 

**To Reproduce**

1. Go to https://github.com/pedronauck/docz/blob/master/examples/basic/src/components/Button.jsx
2. Change from
``` 
export const Button = ({ children, ...props }) => (
  <ButtonStyled {...props}>{children}</ButtonStyled>
)
```
to
```
const Button = ({ children, ...props }) => (
  <ButtonStyled {...props}>{children}</ButtonStyled>
)
export {Button}
```

**Expected behavior**

`<Props>` component should work fine.

**Environment**

* OS: OSX 10.14.3
* Node/npm version: Node 10.15.0/npm 6.4.1
* docz: 1.0.0-rc.7

**Comment by lesha1201** [comment]
I'm working on this problem. Hope to finish soon

**Comment by dartess** [comment]
thanks, v1.0.0-rc.8 show Props fine!
