### ISSUE TITLE
[v rc.7]dependencies warning in yarn install

### ISSUE THREAD

**Issue by GFwer** [pedronauck/docz#761]
## Question

**Description**
*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

I was updated with `yarn add docz@next` and package.json like this:
```
    "docz": "^1.0.0-rc.7",
    "docz-plugin-css": "^0.11.0",
    "docz-theme-default": "^1.0.0-rc.7",
```

but when I try `yarn install`, there will be a warning:
```
warning Lockfile has incorrect entry for "docz@1.0.0-rc.21+2bae93b5". Ignoring it.
Couldn't find any versions for "docz" that matches "1.0.0-rc.21+2bae93b5"
? Please choose a version of "docz" from this list: (Use arrow keys)
```
when I run `yarn install` each time, I have to select the version, is there any way to solve this?

**Comment by luke-john** [comment]
As a temporary workaround you can use the resolutions field in your `package.json` to tell yarn/npm to ignore the requested version and only use a particular version.

see below for an example

```json
{
  "name": "your-package-name",
  "resolutions": {
    "**/docz-core": "1.0.0-rc.7",
    "**/docz": "1.0.0-rc.7"
  },
```

This beahviour files is documented at the following link

https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by GFwer** [comment]
Thanks! this option helps me a lot!

**Comment by pedronauck** [comment]
Can I close this @GFwer ?

**Comment by pedronauck** [comment]
This is happening just with npm, it's a problem related to the way of npm resolve dependencies. Another solution keeps your docz dependencies like that:

```json
"devDependencies": {
  "docz": "1.0.0-rc.7",
  "docz-core": "1.0.0-rc.7",
  "docz-theme-default": "1.0.0-rc.7",
},
```

**Comment by GFwer** [comment]
Yes, thanks a lot!
