### ISSUE TITLE
Why does the loading indicator not show up with 1.0.0-rc.7?

### ISSUE THREAD

**Issue by edgarmueller** [pedronauck/docz#765]
## Question

**Description**
Thanks for the great work on docz! I have question regarding the location indicator: With 0.13.7 there was loading indicator when refreshing a page, but with 1.0.0-rc.7 it doesn't seem to show up anymore. I tested both versions by basically following the Getting started guide with a somewhat bigger MDX file and a reduced connection speed in Chrome while refreshing.
My question is: why is this the case? Did I miss something somewhere? I wasn't able to find anything regarding this. Thanks for any hints!

**Comment by pedronauck** [comment]
Oh my bad, I was using the wrong method for suspense with `@loadable/component`. It's fixed, will be released in the next version 🙏
