### ISSUE TITLE
Loading CSS

### ISSUE THREAD

**Issue by o-t-w** [pedronauck/docz#767]
## Bug Report

I am getting the error 
```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

**To Reproduce**

In the Button.js component file I am importing CSS: `import "./button.css";`. 
I am using Docz in a create-react-app where the CSS is working fine. 

**Expected behavior**

The CSS should style the button when it is displayed in the documentation.

**Environment**

* OSMojave
* Node/npm version: [e.g. Node 10.15.2/npm 6.9.0]

Also, when I apply global styles using index.css, they do not show up on the components when displayed by Docz. How do I get them to work? Shouldn't that be explained in the documentation?! I can't see it anywhere.

**Comment by zarabotaet** [comment]
https://github.com/pedronauck/docz-plugin-css
