### ISSUE TITLE
[v1.0.0-rc.8] Browser freezes when pressing sub-menu (hash–anchor)

### ISSUE THREAD

**Issue by draperunner** [pedronauck/docz#768]
## Bug Report

When I select a heading 2 anchor in the menu, the browser tab freezes (Chrome), and I have to close it. I.e. the "Hey there" and "Tell me more" in the image below.

![image](https://user-images.githubusercontent.com/4339443/55623482-6bb7bc80-57a3-11e9-9e58-a9e2509c1a83.png)

It's easily reproducible. Initialize a clean project, something like this:

```
mkdir docz-test
cd docz-test
npm init -y
npm i -D docz@next docz-theme-default@next
touch hello.mdx
```

Fill `hello.mdx` with this:

```
---
name: Hello
menu: Intro
---

# Welcome

How are you doing?

## Hey there

We can talk.

## Tell me more

Contact us for more talking.
```

Run `node_modules/.bin/docz dev`, go to `localhost:3000` and click one of the two links in the menu. Freeze! 🍧 

I am using these versions:

```
"docz": "^1.0.0-rc.8",
"docz-theme-default": "^1.0.0-rc.8"
```

**Environment**

* MacOS Mojave 10.14.4
* Node 10.13.0/npm 6.4.1

**Comment by pedronauck** [comment]
Thanks to warning me @draperunner, I seeing what's happening 🤔

**Comment by pedronauck** [comment]
Fixed, I don't know why but was something related to `React.Suspense`. I was using the `lazy` method of `@loadable/component` with suspense, it works fine for routes and code splitting, but was crashing when some location has a hash, so awkward, I just change to the `loadable` method without suspense and now it's working.

Btw, will be released in the next version.

**Comment by lixiaoyan** [comment]
I'm running into this problem, too. Is there any schedule for next release?

**Comment by dannyrb** [comment]
[v1.0 was just released](https://github.com/pedronauck/docz/releases/tag/v1.0.0) and resolved this issue for me :+1:
