### ISSUE TITLE
Playground components show syntax error, but only when deployed to Netlify

### ISSUE THREAD

**Issue by dannyrb** [pedronauck/docz#788]
## Question

**Description**

All playgrounds for all of my components show the following error when deployed to Netlify:

`SyntaxError: Unexpected token (1:7) 1 : (<React.Fragment><State ^`

But when built and served locally, render as expected. I'm hoping someone that uses `docz` has come across this before, and can point me toward what's causing this particular issue. I realize it's likely not a problem with `docz` itself.

*Give more information about your doubt*

![image](https://user-images.githubusercontent.com/5797588/55990817-87b4d580-5c5d-11e9-9480-12703d3453bd.png)

I'm using RC8 of `docz`

**Comment by dannyrb** [comment]
I'll close this. Related to an environment issue where I needed to set an explicit version of `yarn` to run, and to make sure `YARN_FLAGS` were properly set.

**Comment by Symboler** [comment]
i meet the quesstion too,and when i use npm locally,it happend,how to solve?
