### ISSUE TITLE
Sub-menu doesn't work with umlauts

### ISSUE THREAD

**Issue by MaluNoPeleke** [pedronauck/docz#792]
Clicking on sub-menu entries that contain umlauts doesn't do anything.
Expected behaviour is that you will scroll to the position of that headline.
![image](https://user-images.githubusercontent.com/1446541/56115966-f008fd00-5f64-11e9-937b-7ada119cbd43.png)
Clicking on "Übersicht" (//src-content-german#%C3%BCberblick) doesn't do anything, clicking on "Medien" (//src-content-german#medien) scrolls to the desired position within the document.

**Comment by NexxLuo** [comment]
I have the seem problem. because the submenu item name is not English  character

**Comment by draperunner** [comment]
@MaluNoPeleke is this still a problem in versions >= 1.1.0? This PR was included in v1.1.0: https://github.com/pedronauck/docz/pull/840

 https://github.com/pedronauck/docz/releases/tag/v1.1.0

**Comment by MaluNoPeleke** [comment]
Yes, issue was solved with 1.1, thanks for reminding me :)
