### ISSUE TITLE
Built-in component for controlled components

### ISSUE THREAD

**Issue by danburzo** [pedronauck/docz#8]
_Disclaimer: I'm just now reading through the docs, maybe I have missed it. Apologies in advance :)_

Since React 16.4, having mixed-control components (that work either via a `value` prop and `onChange` callback, or with an internal state) are discouraged, if cumbersome to build.

I wonder if there could be a built-in component that can manage the state for a controlled component:

```jsx
<Controller>
{ (state, setState) => 
    <MyComponent value={state.value} onChange={ value => setState({ value }) } />
}
</Controller>
```

**Comment by denisborovikov** [comment]
Have you seen [react-powerplug](https://github.com/renatorib/react-powerplug)?

**Comment by danburzo** [comment]
@denisborovikov no, I haven't, that's exactly what I was looking for, thank you very much! :)
I'll leave this open for now, in case a built-in component is still on the table, but I'm very happy with this resolution ✌️

**Comment by pedronauck** [comment]
Hi @danburzo. Isn't our plans create something like that exactly because [react-powerplug](https://github.com/renatorib/react-powerplug) is awesome and can fit so good with docz. Built-in components need to be something that have some dependency from docz data or environment!

**Comment by danburzo** [comment]
Makes sense, thank you!

**Comment by pedronauck** [comment]
I think that is not a good idea @jedrichards, this will put extra concerns for Playground. In the future, we'll put knobs on it, and this can bloat the component a lot.
