### ISSUE TITLE
Default theme global styles change components look and feel

### ISSUE THREAD

**Issue by fzaninotto** [pedronauck/docz#80]
## Bug Report

The default theme exports global styles using emotion. These styles affect the style of the components I display in my docz.

Most notably, the global `a` style affects all buttons. 

I think the bug started to appear when I installed emotion to style my own doc component helpers.

Solution:

Don't set global styles. Normalize.css already does that. The themes should only add styles related to their components.

**Comment by marceloavf** [comment]
🎉 This issue is now fixed in version 0.3.2 🎉

The release is available on:
- [npm package (@latest)](https://www.npmjs.com/package/docz)
- [GitHub release](https://github.com/pedronauck/docz/releases/tag/v0.3.2)

Feel free to reopen if the problem remains, thank you!

**Comment by fzaninotto** [comment]
Thanks, it works 👍
