### ISSUE TITLE
Props background color to not use sideBar bg color

### ISSUE THREAD

**Issue by rupification** [pedronauck/docz#804]
I think it would be better to have its own theme variable as oppose to using the sidebar bg color this way you can have a black sidebar while maintaining the clean white page on the right. Using the same sidebar color will look a bit odd since it will show up as black boxes.

line:
https://github.com/pedronauck/docz/blob/master/core/docz-theme-default/src/components/ui/Props.tsx#L37
`${get('colors.sidebarBg')}`

**Comment by Glazy** [comment]
Hey @rupification,

Thanks for the suggestion! I think it would be good to have the props background colour be the same as the sidebar unless the user explicitly sets one in the theme. What do you think @pedronauck?

Would be awesome if you could whip up a PR for this :muscle:

**Comment by rupification** [comment]
It seems like there has been some commits made recently post 1.0.4 which introduced propsBg theme color. If yes we can close this

**Comment by Glazy** [comment]
You're right, I can see `propsBg` added, will close your issue!

Thanks once again for the suggestion though :muscle:
