### ISSUE TITLE
Title link does not refer to base url

### ISSUE THREAD

**Issue by WesselKuipers** [pedronauck/docz#814]
## Bug Report

**Describe the bug**

It looks like the title link referring back to the root does not inherit the same `base` property that the side menu nav items gets. This causes the title link to refer to the wrong page.

For example:  
Let's say I'm hosting my documentation on example.com/foo. I set the `base` property in `doczrc.js` to `/foo/`. This causes every item in the side menu to correctly prepend `/foo/`, including my Getting Started page which has a `route: '/'` property in its frontmatter. 

The Getting Started link simply refers to `example.com/foo`, but if I hover over the title, it's pointing to `example.com` instead.

**To Reproduce**

Using Docz's `basic` example project:  
1. Set `base` in `doczrc.js` to `/foo/`
2. Run `yarn dev`
3. Hover over menu items and `Docz Example Basic` title

**Expected behavior**

The title link should respect the `basename` property from the Router component, so in the above example it should link to `/foo/`. 

**Environment**

* OS: Ubuntu 18.04
* Node/npm version: Node v10.15.3 / npm 6.4.1

**Comment by fi3ework** [comment]
Confirmed. I'd like to fix it. Guess it's easy to fix. 😉

**Comment by WesselKuipers** [comment]
Just checked out the new release and it works, cheers! :raised_hands:
