### ISSUE TITLE
Component Props not rendering

### ISSUE THREAD

**Issue by jsplopes** [pedronauck/docz#825]
The component props isn't rendering.

On prop component the **stateProps** key have "/" as path separator (unix slash):

![image](https://user-images.githubusercontent.com/35458912/56505599-f6bee380-6513-11e9-8592-3b6e5c23a48c.png)

And in the **filename** is used the "\" as path separator (windows backslash):

![image](https://user-images.githubusercontent.com/35458912/56505543-dabb4200-6513-11e9-94d6-c494936e495b.png)

The path validation must be agnostic, so maybe in the conditional found the path separator
on both must be normalized to a unix slash.

I'm using:
- Docz v.1.0.0
- Typescript
- dev compile on windows 10

regards,
Júlio Lopes

PS: Nice job...

**Comment by fi3ework** [comment]
Could be fixed in next released version.

**Comment by Glazy** [comment]
Closing, follow this issue in #777 :muscle:
