### ISSUE TITLE
Failing to compile when exporting default object with reserved word attribute

### ISSUE THREAD

**Issue by andrewkshim** [pedronauck/docz#826]
## Bug Report

**Describe the bug**

Docz is failing to compile when it encounters a module that default exports an object that contains an attribute that is a Javascript reserved word (e.g. `delete`).

**To Reproduce**

1. Create a module that default exports an object that contains an attribute that is a Javascript reserved word:

```js
export default {
    delete: () => {}
}
```

2. Import that module into an `.mdx` file.

3. See error:
```shell
Module parse failed: Unexpected token (13:18)
You may need an appropriate loader to handle this file type.
| export default _default;
| 
> if (typeof delete !== 'undefined' && delete && delete === Object(delete) && Object.isExtensible(delete)) {
|   Object.defineProperty(delete, '__filemeta', {
|     enumerable: true,
``` 

Minimum reproduction: https://codesandbox.io/s/zw84kmjl3l

**Expected behavior**

Compiles successfully.

**Environment**

* OS: any
* Node/npm version: node 10/npm 6

**Additional context/Screenshots**

Related to https://github.com/pedronauck/docz/issues/790. That issue was specifically for  `default`, but this issue applies to all reserved words.

In my case, I have an HTTP request utility library that's used in some of my components. That library default exports an object with HTTP methods e.g.
```js
export default {
    get: () => {},
    post: () => {},
    delete: () => {},
}
```

And, as in the example, the `delete` is breaking the build.

There is a workaround. If you assign the export to a variable, and default export that variable, then `babel-plugin-export-metadata` will only attach metadata to that variable (and not its keys): https://github.com/pedronauck/docz/blob/4d96db60fa5d3b4600be465b46d4c1a82c3d8ff2/other-packages/babel-plugin-export-metadata/src/index.js#L114-L119

The reason it breaks when you directly export the object is because `babel-plugin-export-metadata` treats `ObjectExpressions` differently. It will go through each of the keys and attach metadata to them: https://github.com/pedronauck/docz/blob/4d96db60fa5d3b4600be465b46d4c1a82c3d8ff2/other-packages/babel-plugin-export-metadata/src/index.js#L121-L129

But the file metadata cannot take reserved words as identifiers since the end result isn't valid Javascript: https://github.com/pedronauck/docz/blob/4d96db60fa5d3b4600be465b46d4c1a82c3d8ff2/other-packages/babel-plugin-export-metadata/src/index.js#L5-L17

P.S. Thanks for all the work on `docz`. It's a great tool!

**Comment by fi3ework** [comment]
hi @andrewkshim 
Now reserved words are transformed to another dummy word to bypass. Such as
```js
export default from './a`
```
to
```js
import __DOCZ_DUMMY_EXPORT_DEFAULT from './a.js'
export default __DOCZ_DUMMY_EXPORT_DEFAULT
```
As you know, there is a number of reserved words and keywords. I think it's a good habit to prevent using these words no matter whether you're using docz. 😀

**Comment by andrewkshim** [comment]
> As you know, there is a number of reserved words and keywords. I think it's a good habit to prevent using these words no matter whether you're using docz.

@fi3ework Yeah, I agree it's a good habit to avoid those words.

However, I don't think babel plugins should prevent you from doing things Javascript itself doesn't prevent. In the case I describe above, I think it's a reasonable exception to have a `delete` attribute on an object that represents a request utility. That said, this is an edge case and there is a workaround, so I'll close this issue.
