### ISSUE TITLE
CRA with docz: doesn't work

### ISSUE THREAD

**Issue by dalisoft** [pedronauck/docz#858]
## Bug Report

**Describe the bug**
I have error when typing `docz:dev`
```bash
./node_modules/docz/dist/index.esm.js 23:38
Module parse failed: Unexpected token (23:38)
You may need an appropriate loader to handle this file type.
| import { MDXProvider } from '@mdx-js/react';
| 
> const BasePlayground = loadable(() => import('./chunk.esm2.js'));
| const Playground = props => typeof window !== 'undefined' ? createElement(Suspense, {
|   fallback: null

```
*A clear and concise description of what the bug is.*

**To Reproduce**

Created simple file after seen this [documenting React.js components](https://medium.com/trabe/document-your-react-components-using-docz-1b8bd888ebe3) and loved it at first look, of course :)

```shell
FOR BUGS: Insert debug trace
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: macOS 10.13.6
* Node/npm version: Node.js 12 / NPM v6.9.0

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by AryanJ-NYC** [comment]
Likely dupe of https://github.com/pedronauck/docz/issues/704.

Hope that helps.

**Comment by dalisoft** [comment]
Yea. I already know. Also fixed already
