### ISSUE TITLE
CRA with docz: components relative (base) url not working properly

### ISSUE THREAD

**Issue by dalisoft** [pedronauck/docz#859]
## Bug Report

**Describe the bug**

Docz required files to be absolutely imported, relative imports does not works

**To Reproduce**

1. Go to Install docz and configure on any CRA app
2. Run docz dev server.
3. See error (when relative file-paths)

```shell
 ERROR  Failed to compile with 1 errors                                                                                         16:08:59

This dependency was not found:

* redux/rest in ./src/pages/Counter/reducers.js

To install it, you can run: npm install --save redux/rest
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by pedronauck** [comment]
You need to configure your alias using custom webpack configuration to has the same shape of u're using inside CRA.
