### ISSUE TITLE
MDX not works

### ISSUE THREAD

**Issue by talisonfc** [pedronauck/docz#860]
## Bug Report

I tried to use docz in a started project with react 16.8.6 but does not work. After install docz using `npm isntall docz docz-theme-default --dev`, set scripts docz:dev and docz:build on package.json and run using `npm run docz:dev`, I get the follow error:

```
./node_modules/docz/dist/index.esm.js 23:38
Module parse failed: Unexpected token (23:38)
You may need an appropriate loader to handle this file type.
| import { MDXProvider } from '@mdx-js/react';
| 
> const BasePlayground = loadable(() => import('./Playground.esm.js'));
| const Playground = props => typeof window !== 'undefined' ? createElement(Suspense, {
|   fallback: null
```

**Comment by AryanJ-NYC** [comment]
Please see https://github.com/pedronauck/docz/issues/704.

**Comment by talisonfc** [comment]
Thank you

**Comment by Glazy** [comment]
Closing this issue for now as it seems you have sorted your problem @talisonfc :+1:
