### ISSUE TITLE
v1 scrolling on mobile seems to be broken

### ISSUE THREAD

**Issue by madou** [pedronauck/docz#870]
## Bug Report

When scrolling on a mobile it just.. doesn't seem to work past a certain point. Check yourself at yubabajs.com. Was fine on v0.

**To Reproduce**

1. go to yubabajs.com on a mobile browser (chrome)
2. try to scroll down the page
3. notice that you can't

**Expected behavior**

Scrolling works as expected

**Environment**

* Android Chrome

**Comment by madou** [comment]
Nvm seems to be ok.

**Comment by madou** [comment]
Ok no it's definitely broken.

1. Go to yubabajs.com on Android Chrome
2. Navigate to another page in nav
3. Try scroll down, you cant

**Comment by lemon-31** [comment]
Hello @madou 

I ran into this issue myself a couple weeks ago. Here is the issue I raised: https://github.com/pedronauck/docz/issues/850

Also, here is the pull request I made to fix the issue, hopefully it will be merged into master soon: https://github.com/pedronauck/docz/pull/880

**Comment by madou** [comment]
cool man i'll close this then, thanks for looking into it!
