### ISSUE TITLE
Webpack dev server Validation error

### ISSUE THREAD

**Issue by adeelibr** [pedronauck/docz#879]
## Bug Report

**Describe the bug**

This is my `package.json` file

```
{
  "name": "dummy",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "npm run docz:dev",
    "docz:dev": "docz dev",
    "docz:build": "docz build"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "docz": "^1.2.0",
    "docz-theme-default": "^1.2.0"
  }
}
```

This is `.doczrc.js`

```js
export default {
  title: 'Dummy',
  description: 'Foo bar',
  source: './src-docs',
  debug: false,
  theme: 'docz-theme-default',
  themeConfig: {
    mode: 'dark',
    colors: {
      primary: '#ee212e',
    },
  },
  codeSandbox: false,
};
```

& all in my `/src-doc` files are `.mdx` files.

When I run

```
npm run docz dev 
```

or with yarn

```
yarn docz dev
```

I get the following error.

<img width="1108" alt="Screenshot 2019-05-17 at 17 48 17" src="https://user-images.githubusercontent.com/16651811/57940115-10add500-78cc-11e9-9e65-053983c2283d.png">

I am not sure what I can do here, to resolve this 😞 

<strike>
**To Reproduce**

</strike>

**Expected behavior**

To run docz successfully.

**Environment**

* OS: [e.g. OSX 10.14.5]
* Node/npm version: [e.g. Node v11.10.1/npm v6.7.0]
* yarn v1.15.2

**Comment by adeelibr** [comment]
Please do let me know if I can share any other kind of log to help in tracing the issue. @sw-yx 😭 😞

**Comment by sw-yx** [comment]
this seems to be a breaking change from webpack. fortunately we already have a PR! https://github.com/pedronauck/docz/pull/878

**Comment by sw-yx** [comment]
@pedronauck i merged the bugfix if you can release

**Comment by adeelibr** [comment]
@sw-yx Any rought ETA as to when the next release will happen? 😅 😅

**Comment by sw-yx** [comment]
i dont control the releases, sorry
