### ISSUE TITLE
TypeError: Cannot read property 'presets' of null

### ISSUE THREAD

**Issue by nicolasbettag** [pedronauck/docz#9]
Hi there!

I started to integrate docz into my project. Installed according the getting started.
When I'm running docz dev, I'm running into the following error:

```
> docz dev

TypeError: Cannot read property 'presets' of null
    at /Users/xxx/Projects/xxx/node_modules/deepmerge/dist/umd.js:56:57
    at Array.forEach (<anonymous>)
```

Tried with Node Version v9.11.1 and v10.4.0.

**Comment by beeant** [comment]
I'm also having this problem

**Comment by pedronauck** [comment]
Are you using some babel config on your project?

**Comment by nicolasbettag** [comment]
Hey! 

Yeah, I'm using a babel config in my project.
When I delete the .babelrc file, I'm getting the following error:

```
TypeError: Cannot read property 'name' of undefined
    at new Entry (/Users/xx/Projects/xxx/node_modules/docz-core/dist/index.js:1:5189)
``

This is my .babelrc - if you need it for debugging:

```
{
	"presets": ["env", "stage-0", "react"],

	"plugins": [
		["transform-react-jsx", { pragma: "h"}],
		["transform-class-properties", { spec: true}],
		["emotion"]
	]
}
```

**Comment by pedronauck** [comment]
Babel 6 support now is possible by using [docz-plugin-babel6](https://github.com/pedronauck/docz/tree/master/packages/docz-plugin-babel6) release in [v0.2.6](https://github.com/pedronauck/docz/releases/tag/v0.2.6)

```js
// doczrc.js
import { babel } from 'docz-plugin-babel6'

export default {
  plugins: [babel()]
}
```

**Comment by AliMol** [comment]
import {AfterViewInit, Component, ElementRef} from '@angular/core';

import SwaggerUI from 'swagger-ui';
import 'swagger-ui/dist/swagger-ui.css';

//import { SwaggerUIBundle, SwaggerUIStandalonePreset } from "swagger-ui-dist";


@Component({
  selector: 'app-swagger',
  templateUrl: './swagger.component.html',
  styles: ['./swagger.component.scss']
})
export class swaggerComponent implements AfterViewInit {

  constructor(private el: ElementRef) {
  }

  ngAfterViewInit() {
    const ui = SwaggerUI({
      url: '../../swagger.json',
      domNode: this.el.nativeElement.querySelector('.swagger-container'),

      presets: [
        SwaggerUI.presets.apis
      ]
    });
  }
}


This is my code : and this is the error :

swaggerComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'presets' of undefined
    at swaggerComponent.push../src/app/swagger/swagger.component.ts.swaggerComponent.ngAfterViewInit
