### ISSUE TITLE
NEW DOCZ THEME - ZTOPIA

### ISSUE THREAD

**Issue by zicodeng** [pedronauck/docz#914]
![demo](https://user-images.githubusercontent.com/24593509/59324775-35ac2280-8c95-11e9-9247-fd7055c1feef.gif)

Home page: http://docz-theme-ztopia.surge.sh/

# Why Ztopia Theme?

For a long time, Docz has been lonely with just one look, [the default theme](https://github.com/pedronauck/docz/tree/master/core/docz-theme-default). Now, let's embrace its new look with the Ztopia theme! Well, creating a new look is just one of many reasons I want to start this project. Below are more reasons why you should switch to the Ztopia theme:

- **Aesthetically pleasing design**: inspired by [Ant Design React](https://ant.design/docs/react/introduce) and [Material UI](https://material-ui.com/), 40% of my time was devoted to the Ztopia UI&UX when I built this theme. Why? because I believe great UI&UX can attract people reading documentation :)

- **One theme, two looks**: Ztopia theme comes with light and dark mode. You can click the light bulb in top right corner to see the difference. If your component also supports light and dark theme, you can import `ThemeConsumer` from this library,  and use it to theme your components. See [Button.mdx](https://github.com/zicodeng/docz-theme-ztopia/blob/master/example/Button.mdx) for an example

- **Gracefully handle complex prop shape**: it is common to have component props that accept complex shapes. Inlining them as plain text like this `PropTypes.shape({ firstName: PropTypes.string.isRequired, lastName: PropTypes.string.isRequired, ...})` is probably not a best way to show. Fortunately, Ztopia handles complex shapes automatically for you. Whenever you see `Shape` type in props table, it means you can hover it and see your complex shape. Check out examples in [Design](http://docz-theme-ztopia.surge.sh/docs/design) page

- **Description with inline code**: when you write descriptions for props, you can embed inline code like this /\*\* This is `code` \*/

- **Playground with built-in iframe support**: the default Docz `<Playground>` is really cool, but it does not serve your components in an isolated browsing context. This makes developers hard to test component responsiveness and lead to possible CSS collisions between Docz default theme style and component style. There is a [GitHub issue](https://github.com/pedronauck/docz/issues/789) discussing about it. With the above reasons in mind, Ztopia theme `<Playground>` is built with `<iframe>` support in mind, so that you can build your components in isolation. See [Button](http://docz-theme-ztopia.surge.sh/components/button) page for an example. (If you are not thinking about switching to Ztopia theme, but still need `<iframe>` Playground support, check out this [plugin](https://github.com/zicodeng/docz-iframe-playground) I wrote)

# Star Ztopia Theme on GitHub

This project is completely open source and free of charge. If you like it, [star Ztopia theme](https://github.com/zicodeng/docz-theme-ztopia) on GitHub. Your support is my biggest motivation :)

@pedronauck would it be possible to add this theme to the Docz site theme page here: https://www.docz.site/themes

Thank you all!

**Comment by Glazy** [comment]
Hi @zicodeng!

Great job on the theme, it looks cool :+1:

We would be happy to accept a pull request that adds this theme to the Docz site 🙂

**Comment by zicodeng** [comment]
Thanks, will do!

**Comment by zicodeng** [comment]
@Glazy PR is here: https://github.com/pedronauck/docz-website/pull/66
