### ISSUE TITLE
After upgrading docz from 0.12.9 to 1.2.0, `docz dev` won't serve files from my public folder

### ISSUE THREAD

**Issue by adrianschmidt** [pedronauck/docz#917]
## Question

After upgrading docz from 0.12.9 to 1.2.0, `docz dev` won't serve files from my public folder. Whatever I try, I haven't been able to load any files that aren't part of docz's own build output. I just get the 404-page.

In more detail, what I'm doing is building a StencilJS-app and placing it in the `.docz/public/` folder, then loading a file from the path `.docz/public/stencil/build/my-app.js` from the url `/stencil/build/my-app.js`.

This worked in 0.12.9, but does not work in 1.2.0.

I've also tried eliminating any issues with my StencilJS output, by creating a minimal json-file in the `public` folder, and trying to load that, both from `http://localhost:3000/test.json` and from `http://localhost:3000/public/test.json`. Both give me the 404 page.

I couldn't find any recent issues describing a similar problem, so I'm guessing I'm simply missing something here?

Any help would be much appreciated!

**Comment by ejuo** [comment]
Try to explicitly specify the folder in the config `doczrc.js`:
```javascript
export default {
title: "your-app",
'public': ".docz/public",
...
}
```

**Comment by adrianschmidt** [comment]
Thanks! I'll try that as soon as possible! (I've been out sick for a while, hence my late reply.) I'll return with a result as soon as I've tried it.

**Comment by adrianschmidt** [comment]
Yes! It works! Thank you so much!
