### ISSUE TITLE
Setting dist in doczrc.js doesn't do anything

### ISSUE THREAD

**Issue by antony** [pedronauck/docz#92]
## Bug Report

When I try to set the `dist` attribute of `doczrc.js`, no matter what I set it to, dist is still built to `.docz/dist/`.

*A clear and concise description of what the bug is.*

**To Reproduce**

1.  yarn add docz --dev

```shell
 14:44:41  ant@vanta  ~/Projects/style-guide  ⬡ v9.5.0   master ✘ ✖ ✹ ✭  6s 
$ cat doczrc.js 
export default {
  title: 'My Components',
  description: 'Styleguide for Me',
  dist: 'dist'
}%                                                                                                                                                   
 14:48:45  ant@vanta  ~/Projects/style-guide  ⬡ v9.5.0   master ✘ ✖ ✹ ✭ 
$ yarn docz build
yarn run v1.7.0
$ /home/ant/Projects/style-guide/node_modules/.bin/docz build
▶  start     Creating an optimized production build...
✔  success   Compiled successfully.

File sizes after gzip:

  125.02 KB     dist/static/js/vendors.b1171617.js
  7.35 KB       dist/static/js/components-logo-logo.37633655.js
  1.15 KB       dist/static/js/runtime~app.00554158.js
  958 B         dist/static/js/components-button-button.f8fdf6cf.js
  845 B (-2 B)  dist/static/js/app.e6da3127.js

Done in 6.75s.
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

I expect the built static files to be written to `dist`.

**Enviroment**

* OS: [Ubuntu 18.04]
* Node/npm version: [Node v9.5.0, 5.6.0]

**Comment by pedronauck** [comment]
the right property there's `dest`, not `dist`... if you have any question about the `doczrc` you can see the [Project Configuration](https://www.docz.site/documentation/project-configuration#basic-config) section on website!

**Comment by antony** [comment]
Whoops! Thanks for that :)

**Comment by Jonarzz** [comment]
I think it should also be changed on this Introduction page: https://www.docz.site/introduction/deploying-your-docs

**Comment by antony** [comment]
Ah yes, I knew I wasn't crazy! The docz docs are wrong :)
