### ISSUE TITLE
What is status this project? deprecated?

### ISSUE THREAD

**Issue by adrianoresende** [pedronauck/docz#930]
When checking the list of commits, it seems that this project is stopping, or I am wrong?

**Comment by pedronauck** [comment]
Hi @adrianoresende, thanks to asking! The answer is NO, I'm working a lot in order to launch a new version with a lot of improvements, because of that the project it's kinda a stopped. Soon as possible I'll launch a new version and get more time to help with fixes ✌️

**Comment by danielbayerlein** [comment]
@pedronauck Maybe `docz` should change to an organization and add some core contributors.

**Comment by fraincs** [comment]
> @pedronauck Maybe `docz` should change to an organization and add some core contributors.

Exactly, I would gladly help as I use it daily, when it works

**Comment by pedronauck** [comment]
I could do that @danielbayerlein, this can be a thing since I very busy right now and it's hard to keep maintaining here 😕 if anyone wants to help with that, ping me 🙏

**Comment by danielbayerlein** [comment]
@pedronauck If you need any help, let me know.
