### ISSUE TITLE
\n character in Props description instead of new line

### ISSUE THREAD

**Issue by jaikiratsingh** [pedronauck/docz#949]
## Bug Report

**If PropTypes take more than 1 line, Docz prints the character "\n" rather than going on a new line**

**To Reproduce**

1. Create a dummy component, TestComponent

<img width="304" alt="Screenshot 2019-07-10 at 11 06 40 AM" src="https://user-images.githubusercontent.com/22212270/60943214-df1d1d00-a302-11e9-9d5b-867bd31790b1.png">

2. Create the documentation for this components in TestComponent.mdx for Docz and include the Props component.

<img width="644" alt="Screenshot 2019-07-10 at 11 08 48 AM" src="https://user-images.githubusercontent.com/22212270/60943276-1be91400-a303-11e9-9e9d-7ee2cb77f6e5.png">

**Expected behavior**

The PropTypes description will describe the prop : **a** in multiple lines. Instead it shows the following.

<img width="540" alt="Screenshot 2019-07-10 at 11 02 07 AM" src="https://user-images.githubusercontent.com/22212270/60943351-5ce12880-a303-11e9-82e1-ebec74d11f80.png">

It shows the \n character where it was supposed to give a new line. 

It looks ugly, is there any way to solve this.

Thanks.

**Environment**

* OS: OSX 10.14.5
* Node/npm version: Node 8.15.0

**Comment by zicodeng** [comment]
Docz the default theme does not handle `PropTypes.shape` very well. It just prints everything inline. Check out this new [theme](http://docz-theme-ztopia.surge.sh/). It handles complex prop shape gracefully

**Comment by jaikiratsingh** [comment]
Thanks :)
