### ISSUE TITLE
docz with typescript is not working properly

### ISSUE THREAD

**Issue by n0ruSh** [pedronauck/docz#952]
## Bug Report

When I setup a typescript project with docz, running `docz dev` reports an error 

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema. - configuration should be an object.`

**To Reproduce**

1. Clone https://github.com/n0ruSh/react-material
2. npm i
3. npm run start
4. See the error

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

https://github.com/n0ruSh/react-material

**Expected behavior**

It should runs properly

**Environment**

* OS:   macOs
* Node/npm version: [e.g. Node 9.2.0/npm 5.5.1]

**Comment by zicodeng** [comment]
I think you forgot to return config in `modifyBundlerConfig` hook?

**Comment by n0ruSh** [comment]
@zicodeng  oh yes. thanks!
