### ISSUE TITLE
Can't resolve objectSpread2

### ISSUE THREAD

**Issue by mbrochh** [pedronauck/docz#953]
## Question

**Description**
I just started a new Razzle project and I keep getting an error that crashes Docz completely. It looks like this:

```
Failed to compile.

./src/components/buttons/ButtonToggleBucket.tsx
Module not found: Can't resolve '/Users/martin/Projects/ash/react/src/artshare/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/objectSpread2' in '/Users/martin/Projects/ash/react/src/artshare/src/components/buttons'
```

Before I spam this thread with package.json info and all that, does anyone have an idea if there are workarounds for this?

**Comment by zicodeng** [comment]
Try deleting your `.docz`, `node_modules`, and 'package-lock.json/yarn.lock` and reinstall modules again?

**Comment by mbrochh** [comment]
@zicodeng I'm shocked. This helped. At least with the component that was crashing it earlier today. Let's see if this error re-surfaces later when I add other complex components to my mdx files.

Thanks a lot!
