### ISSUE TITLE
Unknown word - adding sass-loader

### ISSUE THREAD

**Issue by MattiaVorstenbosch** [pedronauck/docz#969]
## How to add sass-loader?

I'm trying to add sass-loader via `onCreateWebpackConfig` and using `actions.setWebpackConfig` like shown here: [gatsby-api-and-hooks](https://www.docz.site/docs/powered-by-gatsby#gatsby-api-and-hooks)

### Implementation
```
// gatsby-node.js in root folder.
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: /\.s?css$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
      ],
    },
  });
};

```

### Output
```
Compiling...
 ERROR  Failed to compile with 1 errors                                                                                                                                                 3:17:01 PM
⠀
 error  in ./node_modules/gatsby-theme-docz/src/index.css
⠀
Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Syntax Error

(2:1) Unknown word

  1 |
> 2 | var content = require("!!../../css-loader/index.js!../../sass-loader/lib/loader.js!./index.css");
```

Does anyone know what I'm doing wrong? It seems so simple, yet i've been working all day trying to get gatsby to compile my .scss files.

**Comment by MattiaVorstenbosch** [comment]
Closing the issue. Changing `test: /\.s?css$/,` to `test: /\.scss$/,` fixes it.

**Comment by yuripramos** [comment]
Same problem here, unfortunately, the community didn't help me with this question... tried to use this approach here (https://www.docz.site/docs/usage-with-css-preprocessors) without any luck, so I'm giving up the usage of this library
