### ISSUE TITLE
A Problem about Dogen Ergodic Filtering

### ISSUE THREAD

**Issue by jinxin0112** [pedronauck/docz#971]
```
Button
    ├── index.tsx
    ├── __test__
    └── style
```

Why `filterComponents` do not match components like Button/index.tsx, a structure that is common in projects

**Comment by jinxin0112** [comment]
[https://github.com/pedronauck/docz/blob/master/core/docz-core/src/config/docz.ts#L27](url)

**Comment by zicodeng** [comment]
You can override it by using this config entry. Something like: `filterComponents: files =>
    files.filter(file => /([^d]\.(t|j)sx?)$/.test(file))`

**Comment by jinxin0112** [comment]
@zicodeng  Thank you! I'll try it.
