### ISSUE TITLE
Gatsby theme failed with graphql

### ISSUE THREAD

**Issue by theo-mesnil** [pedronauck/docz#972]
## Bug Report

**I try to use gatsby-theme-docz and when i start the project with Gatsby i have this error :** 
![Capture d’écran 2019-07-22 à 15 52 34](https://user-images.githubusercontent.com/50322149/61638100-02e44980-ac99-11e9-9cee-c96930fcdd47.png)

**To Reproduce**

Update my package.json
<img width="494" alt="Capture d’écran 2019-07-22 à 15 55 05" src="https://user-images.githubusercontent.com/50322149/61638152-18f20a00-ac99-11e9-9b7d-6795c7bdc811.png">

Add `gatsby-config.js`
`module.exports = {
  plugins: ['gatsby-theme-docz']
}`

And lunch command `yarn gatsby develop`

I have nothing in doczrc.js

**Environment**

* OS: OSX 10.15.15
* Node v10.15.1 / Npm 6.4.1

Thanks :)

**Comment by wcastand** [comment]
have you tried to use `gatsby-theme-docz@next` instead. 1.2 is probably not compatible with the latest gatsby and theme.

**Comment by theo-mesnil** [comment]
Thanks this works :)
