### ISSUE TITLE
Error migrating from 0.13 : Unknown field 'doczDb' on type 'Query'

### ISSUE THREAD

**Issue by Bluesmile82** [pedronauck/docz#974]
## Question

I'm trying to migrate from version 0.13 to the latest and I have some problems. First, the documentation doesn't explicitly says if you have to install Gatsby to make docz run so I didn't. When I change the docz version it compiles but I get this error message:

```
 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'doczDb' on type 'Query'.

File: node_modules/gatsby-theme-docz/src/hooks/useDbQuery.js
```

This is my doczrc.js:
```
export default {
  files: '**/*.{md,markdown,mdx}',
  dest: './docs/dist',
  title: 'Trase',
  public: './public/docs',
  themeConfig: {
    colors: {
      primary: '#34444C',
      sidebarBg: '#fff0c2'
    }
  },
};
```

And this my gatsby.config.js:

```
const path = require('path')

const srcPath = path.join(__dirname, '..', 'scripts');

module.exports = {
  siteMetadata: {
    title: 'Trase documentation',
  },
  plugins: [
    {
      resolve: `gatsby-plugin-alias-imports`,
      options: {
        alias: {
          'react-components': path.resolve(srcPath, 'react-components'),
        },
        extensions: ['jsx', 'js', 'mdx']
      }
    }
  ]
}

```

Both are in the root of my project.

In package.json:

```
    "docz": "^2.0.0-rc.1",
    "docz-theme-default": "^1.2.0"
```

**Comment by p77u4n** [comment]
Why did you close this issue, I have the one same, it has occurred after I set gatsby-configs to replace default docz theme with docz-theme-ztopia. :(

**Comment by bricelp** [comment]
Could you please provide detail on how you solved this issue ?

**Comment by zicodeng** [comment]
@p77u4n hi, author of `docz-theme-ztopia` here. Ztopia theme doesn't work with Docz v2, it only works with v1. I will make it compatible with v2 once it gets more stable :)
