### ISSUE TITLE
Steps to deploy dist/ to heroku, please.

### ISSUE THREAD

**Issue by ranand** [pedronauck/docz#987]
## Question

Please describe the steps to deploy "dist" folder to heroku, if possible. 

I have tried following resources such as:
https://github.com/mars/create-react-app-buildpack
https://blog.heroku.com/deploying-react-with-zero-configuration
https://hackernoon.com/deploying-any-react-app-to-heroku-1ee6db9b97d3

But, I have not been successful in getting the static site to be up and running yet. Any help is much appreciated.

static.json
```
{
  "root": ".docz/dist/",
  "clean_urls": true,
  "routes": {
    "/**": "index.html"
  }
}
```

Thanks much in advance!

**Comment by bryanberger** [comment]
https://github.com/heroku/heroku-buildpack-static

**Comment by ranand** [comment]
@bryanberger - I did try it, but to no avail. is my `static.json` right?

Little backstory:
- The repo I'm trying to deploy to heroku, contains common components we use at work (so it is not an app by itself). docz is used for documentation purposes.

**Comment by bryanberger** [comment]
@ranand I didn't need clean-urls, also I build to `dist/` not `.docz/dist` so, `"root": "dist/"`

**Comment by ranand** [comment]
ok @bryanberger - i will give it a try today. thanks!

**Comment by ranand** [comment]
closing this since @bryanberger's suggestion worked. thanks!

**Comment by nopito** [comment]
FWIW, I wrote a post about how to deploy to Heroku https://nopitown.com/deploy-your-docz-site-with-heroku/ . You can also deploy it in one-click https://github.com/nopito/docz-with-heroku
